### ISSUE TITLE
Incoming mail

### ISSUE THREAD

**Issue by mc0e** [sameersbn/docker-redmine#103]
As of 0.8.0, Redmine can be configured to allow issue creation or comments via email. It is also able to recognize and incorporate email replies to forum messages.

http://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails

I'm personally leaning towards the IMAP approach.  A cron job is needed, and some configuration variables need to be handled for that

**Comment by sameersbn** [comment]
@mc0e I have not tried this. Does it work with google app. If yes, then I can give it a shot

**Comment by mc0e** [comment]
It should work with any imap account, and yes, google provides IMAP access to gmail accounts.


    Server: imap.gmail.com
    Port: 993
    Requires SSL:Yes
    User Name: your full Gmail address (username@gmail.com). Google Apps users, please enter username@your_domain.com
    Password: your Gmail password

**Comment by frdmn** [comment]
Would be really nice to reply by mail, :+1: for this

**Comment by sameersbn** [comment]
feature is available only in `latest`, `2.6-latest` and `3.0-latest` tags until next release.

**Comment by mc0e** [comment]
Excellent.  Will try it out soon.
