### ISSUE TITLE
redmine@postgres ERROR:  database "redmine_production" already exists

### ISSUE THREAD

**Issue by alexwhen** [sameersbn/docker-redmine#104]
Creating root_postgresql_1...
Creating root_redis_1...
Creating root_gitlab_1...
➜  ~  cd redmine
➜  redmine  dc -f redmine.yml up
Creating redmine_postgresql_1...
Creating redmine_redmine_1...
Attaching to redmine_postgresql_1, redmine_redmine_1
postgresql_1 | |------------------------------------------------------------------|
postgresql_1 | | PostgreSQL User: postgres, Password: Cangaevai9FiBi              |
postgresql_1 | |                                                                  |
postgresql_1 | | To remove the PostgreSQL login credentials from the logs, please |
postgresql_1 | | make a note of password and then delete the file pwfile          |
postgresql_1 | | from the data store.                                             |
postgresql_1 | |------------------------------------------------------------------|
postgresql_1 | Creating user "redmine"...
postgresql_1 | Creating database "redmine_production"...
postgresql_1 | Granting access to database "redmine_production" for user "redmine"...
postgresql_1 | Starting PostgreSQL server...
postgresql_1 | 2015-05-13 11:01:56 UTC [26-1] LOG:  database system was shut down at 2015-05-13 11:01:56 UTC
postgresql_1 | 2015-05-13 11:01:56 UTC [25-1] LOG:  database system is ready to accept connections
postgresql_1 | 2015-05-13 11:01:56 UTC [30-1] LOG:  autovacuum launcher started
redmine_1    | Waiting for database server to accept connections
redmine_1    | Migrating database. Please be patient, this could take a while...
redmine_1    | redmine_production already exists
postgresql_1 | 2015-05-13 11:02:03 UTC [33-1] redmine@postgres ERROR:  database "redmine_production" already exists
postgresql_1 | 2015-05-13 11:02:03 UTC [33-2] redmine@postgres STATEMENT:  CREATE DATABASE "redmine_production" ENCODING = 'unicode'
redmine_1    | rake aborted!
redmine_1    | NameError: undefined local variable or method `login' for main:Object
redmine_1    | /home/redmine/redmine/config/initializers/smtp_settings.rb:11:in `<top (required)>'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:166:in `instrument'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/engine.rb:651:in `load_config_initializer'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/engine.rb:615:in `each'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `each'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `tsort_each_child'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
redmine_1    | /home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
redmine_1    | Tasks: TOP => db:migrate => environment
redmine_1    | (See full trace by running task with --trace)
redmine_redmine_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping redmine_postgresql_1...

**Comment by alexwhen** [comment]
it is the new container

**Comment by sameersbn** [comment]
@alexwhen more details please. Perhaps you can share a minimal `docker-compose.yml` file that shows this error. I tested using the sample `docker-compose.yml` and have no issues.

**Comment by alexwhen** [comment]
postgresql:
  image: sameersbn/postgresql:9.4
  environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
  volumes:
    - /srv/docker/redmine/postgresql:/var/lib/postgresql
redmine:
  image: sameersbn/redmine:3.0.3
  links:
    - postgresql:postgresql
  environment:
    - TZ=Asia/Chongqing
    - REDMINE_PORT=10083
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=xxx.com 
    - SMTP_HOST=smtp.xxx.com 
    - SMTP_PORT=25
    - SMTP_USER=user@xxx.com
    - SMTP_PASS=123456
    - SMTP_STARTTLS=false
    - SMTP_AUTHENTICATION=login
  ports:
    - "83:80"
  volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data

**Comment by alexwhen** [comment]
same as sample,only change the something about SMTP and TIMEZONE

**Comment by sameersbn** [comment]
@alexwhen the `SMTP_AUTHENTICATION` value is incorrect, should be `SMTP_AUTHENTICATION=:login`

**Comment by alexwhen** [comment]
thank you very much,it works! thank you !!!
