### ISSUE TITLE
cannot access '/home/redmine/data/tmp/'

### ISSUE THREAD

**Issue by mauron85** [sameersbn/docker-redmine#105]
I'm getting error:

```
chown: cannot access '/home/redmine/data/tmp/': No such file or directory
```

when I run dockerized redmine version 2.5.3 on Ububntu 14.04 with following script:

``` sh
#!/bin/sh
docker run --name=redmine -it --rm \
  --env='DB_TYPE=postgres' \
  --env='DB_HOST=192.168.1.100' --env='DB_NAME=redmine' \
  --env='DB_USER=redmine' --env='DB_PASS=redmine' \
  --volume=/srv/docker/redmine/redmine:/home/redmine/data \
  sameersbn/redmine:2.5.3
```

**Comment by sameersbn** [comment]
@mauron85 are you seeing this on ubuntu:14.04 host? or is it inside a VM or cloud provider such as linode?

**Comment by mauron85** [comment]
@sameersbn on my personal Ubuntu 14.04 box

**Comment by sameersbn** [comment]
What is your docker version. Can provide the details as requested in the issues section of the readme.

**Comment by mauron85** [comment]
Sorry, didn't read readme.
Here it is:

Host distribution: Ubuntu 14.04 LTS SMP x86_64, kernel version: 3.13.0-52-generic
docker version:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

docker info
```
Containers: 2
Images: 26
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.789 GiB
Name: dhcppc8
ID: IP2J:ZS7Y:GP3T:JIY5:YSFR:2AE3:4J3P:PMDA:KT2C:NJPH:K46E:PBIB
WARNING: No swap limit support
```
docker run:
```
docker run --name=redmine -it --rm \
  --env='DB_TYPE=postgres' \
  --env='DB_HOST=192.168.1.100' --env='DB_NAME=redmine' \
  --env='DB_USER=redmine' --env='DB_PASS=redmine' \
  --volume=/srv/docker/redmine/redmine:/home/redmine/data \
  sameersbn/redmine:2.5.3
```

**Comment by sameersbn** [comment]
@mauron85  environment looks fine. can you try removing all existing docker images, then pull from the index and try. This is to make sure that the image has not gone corrupt during the download (yes, its a thing)

**Comment by sameersbn** [comment]
@mauron85 this used to happen a lot before.

**Comment by mauron85** [comment]
OK, it seems that version 2.5.3 is erratic (i tried to redownload, but it didn't help). 
Upgraded to 2.6.5 and it seems fine.

**Comment by sameersbn** [comment]
@mauron85 oh.. I didn't realize you were using an older version
