### ISSUE TITLE
where can i find the error log

### ISSUE THREAD

**Issue by divramod** [sameersbn/docker-redmine#106]
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back

how can i access the error log file?

many regards

**Comment by sameersbn** [comment]
@divramod you can exec into the container and file the logs at `/var/log/redmine/`

**Comment by Zonork** [comment]
Hell ill have the same error.

i try to run redmine 2.6.5 

step 1
docker run --name=postgresql-redmine -d \
  --env='DB_NAME=redmine_production'\
  --env='DB_USER=redmine' --env='DB_PASS=password'\
  --volume=/srv/docker/redmine/postgresql:/var/lib/postgresql \
  sameersbn/postgresql:9.4

step 2:
docker run --name=redmine -d \
  --link=postgresql-redmine:postgresql --publish=10083:80 \
  --env='REDMINE_PORT=10083'\
  --volume=/srv/docker/redmine/redmine:/home/redmine/data \
  sameersbn/redmine:2.6.5

when ill try to access to redmine show this:
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back

error directory have this:
 redmine redmine   77 May 25 16:30 ./
 root    root      49 May 25 16:23 ../
 redmine redmine 1014 May 25 16:24 production.log
 redmine redmine  465 May 25 16:23 unicorn.stderr.log
 redmine redmine    0 May 25 16:23 unicorn.stdout.log

production.log:
root@c40b30cda268:/var/log/redmine/redmine# ll                    
total 8
drwxr-xr-x 2 redmine redmine   77 May 25 16:30 ./
drwxr-xr-x 5 root    root      49 May 25 16:23 ../
-rw-r--r-- 1 redmine redmine 1014 May 25 16:24 production.log
-rw-r--r-- 1 redmine redmine  465 May 25 16:23 unicorn.stderr.log
-rw-r--r-- 1 redmine redmine    0 May 25 16:23 unicorn.stdout.log

production.log 
Connecting to database specified by database.yml
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Started GET "/" for 127.0.0.1 at 2015-05-25 16:24:36 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
Completed 500 Internal Server Error in 168.2ms

NoMethodError (undefined method `mail' for #<GroupAnonymous:0x00000004855cd8>):
  app/models/principal.rb:113:in `set_default_empty_values'
  app/models/group_builtin.rb:47:in `create_instance'
  app/models/group_builtin.rb:40:in `load_instance'
  app/models/group_anonymous.rb:28:in `instance_id'
  app/models/group.rb:99:in `builtin_id'
  app/models/user.rb:501:in `projects_by_role'
  app/models/project.rb:194:in `allowed_to_condition'
  app/models/news.rb:39:in `block in <class:News>'
  app/models/news.rb:71:in `latest'
  app/controllers/welcome_controller.rb:22:in `index'

unicorn.stderr.log 
I, [2015-05-25T16:23:39.507206 #83]  INFO -- : Refreshing Gem list
I, [2015-05-25T16:23:43.149453 #83]  INFO -- : listening on addr=/home/redmine/redmine/tmp/sockets/redmine.socket fd=11
I, [2015-05-25T16:23:43.149826 #83]  INFO -- : listening on addr=127.0.0.1:8080 fd=12
I, [2015-05-25T16:23:43.154742 #83]  INFO -- : master process ready
I, [2015-05-25T16:23:43.194809 #90]  INFO -- : worker=0 ready
I, [2015-05-25T16:23:43.197352 #93]  INFO -- : worker=1 ready

and unicorn.stdout.log is empty

**Comment by sameersbn** [comment]
If you tried using 3.x release and the switched to the 2.6.x release without purging the existing database, then I don't think it will work. Just saying.

Can you switch to the readme from the 2.6-stable branch on github and try the quick start guide.

**Comment by Zonork** [comment]
i delete all conteiners and try to start using this:

Step 1. Launch a postgresql container

docker run --name=postgresql-redmine -d \
  --env='DB_NAME=redmine_production' \
  --env='DB_USER=redmine' --env='DB_PASS=password' \
  --volume=/srv/docker/redmine/postgresql:/var/lib/postgresql \
  sameersbn/postgresql:9.4

Step 2. Launch the redmine container

docker run --name=redmine -d \
  --link=postgresql-redmine:postgresql --publish=10083:80 \
  --env='REDMINE_PORT=10083' \
  --volume=/srv/docker/redmine/redmine:/home/redmine/data \
  sameersbn/redmine:2.6.5

but still the tame error

**Comment by sameersbn** [comment]
@Zonork also make sure you delete the `/srv/docker/redmine/redmine` and `/srv/docker/redmine/postgresql` directories cause they may contain leftover data.

**Comment by Zonork** [comment]
I had not removed the folders.

thats was my error.

thanks for the help, excellent repository.

**Comment by dropfen** [comment]
to see the redmine logs you need to enter the containers shell.
you can do it for any docker container with `docker exec`
`docker exec -t -i redmine /bin/bash`
then you can look for logs in the containers shell

**Comment by vergelli** [comment]
> to see the redmine logs you need to enter the containers shell.
> you can do it for any docker container with `docker exec`
> `docker exec -t -i redmine /bin/bash`
> then you can look for logs in the containers shell

Sorry to reopen but in case I don't see any file in the log folder?

(once inside the docker container)

```
/usr/src/redmine/log# ls -lrt
total 0
```
Seems is nothing there, any tip?

**Comment by jcormier** [comment]
The logs should be in `/var/log/redmine`

fyi i updated the docker-compose files as examples for mounting the log dir to the host filesystem.
https://github.com/sameersbn/docker-redmine/blob/e5a1549a1bee48b06eabc7d3982f44156898a379/docker-compose.yml#L64

**Comment by vergelli** [comment]
I found no folder called "redmine" inside` /var/log/`. It seems weird to me that I can't see the logs in `/redmine/log` either.
am I missing something? Maybe some configuration or a permission thing? I need to check the production log to help fix some bugs.

**Comment by jcormier** [comment]
Are you sure you're using this docker container?  We don't place anything inside /usr/src or /redmine
