### ISSUE TITLE
redmine-git-hosting.io plugin...

### ISSUE THREAD

**Issue by nothing-fr** [sameersbn/docker-redmine#108]
Hi, I want to use the http://redmine-git-hosting.io/ plugin, i need to install Gitolite3 / Sidekiq and do some configuration... Do you think it's possible ?

I don't know really well Docker and i dont know where to start... if you have some hints.

Thanks.

**Comment by sameersbn** [comment]
@nothing-fr Please refer to #34. You will find some insights in this subject there.

Basically, I would recommend using gitlab for your git repository management and redmine for project management and issue tracking. Gitlab can be configured such that the issue management is handled by redmine and also using the `--volumes-from` docker option you can source your git repositories into the redmine container such that you can browse the git repos from redmine.

The relavant information can be found in the indicated issue.

**Comment by nothing-fr** [comment]
My Synology will die if i have too use redmine + gitlab...
gitlab is too expensive in ressources... that's why i like the redmine + git hosting solution, it's lighter for my NAS.

**Comment by sameersbn** [comment]
in that case you have to follow the discussion at issue #34.
If you intend to go with that route I will be happy to support for running a custom init script to get the git stuff loaded.
