### ISSUE TITLE
Database Back UP

### ISSUE THREAD

**Issue by Zonork** [sameersbn/docker-redmine#110]
Hello.

How i can make a database bakup?

**Comment by sameersbn** [comment]
@Zonork well you need to do it the regular way by using tools like `mysqldump` or `pg_dump`

**Comment by Zonork** [comment]
But i need make the mysqldump or pg_dump inside the conteiner or outside like "docker exec"? i try inside the psql conteiner but i cant get out  of the conteiner the .sql file

**Comment by sameersbn** [comment]
If you are using a mysql container then you can use  the `mysqldump` using docker exec,

```bash
docker exec -it mysql mysqldump [OPTIONS] redmine_production > redmine_production.mysql
```

In case of postgresql container you can use

```bash
docker exec -it postgresql sudo -u postgres -H pg_dump [OPTIONS] redmine_production > redmine_production.psql
```

**Comment by sameersbn** [comment]
@Zonork were you able to take the backup?

**Comment by Zonork** [comment]
Hi @sameersbn, yes i take it, thanks, sorry for the late answer.
