### ISSUE TITLE
504 errors

### ISSUE THREAD

**Issue by joshuacox** [sameersbn/docker-redmine#111]
I am getting a user who continues to receive 504 errors,  I fixed this in the past by ensuring the server line had a `fail_timeout=0` at the end of it like so:
```
server 192.168.0.9:8080 fail_timeout=0;
```
like the example unicorn file says
http://unicorn.bogomips.org/examples/nginx.conf

but that is how nginx is currently setup inside the container:
https://github.com/sameersbn/docker-redmine/blob/master/assets/config/nginx/redmine-ssl

I do have a second nginx proxy setup to do name based routing that then connects to individual containers, the upstream block looks like this:
```
upstream redmine {
  server 127.0.0.1:11081 fail_timeout=0;
}
```
and most users are using the redmine server just fine, but one of the users intermittently is getting 504 errors.

has anyone else seen this behavior crop up with this redmine container?

**Comment by sameersbn** [comment]
@joshuacox you should probably retry after flushing the browser cache of the particular user and/or try with a different browser.

**Comment by joshuacox** [comment]
ya that is always my first response, ctrl-shift-N and pull up a private browsing window (that prevents the usage of all caching etc).  And he definitely saw another 504 after that.  I'll post back with anymore info I can uncover, I'll leave this open for a few days in case there is anyone else out there in the same predicament.  I'll close after that though, if I can't come up with a solution.

**Comment by sameersbn** [comment]
@joshuacox can you try increasing the `UNICORN_TIMEOUT` parameter. Maybe the ruby script could just be timing out.

**Comment by joshuacox** [comment]
I'm increasing it another 25% to 75, but I'm thinking he hit those 504s before 60 seconds (the previous value),  I'll continue investigating.

**Comment by sameersbn** [comment]
@joshuacox One thing you can try is disabling proxy-buffering at the load balancer. Add `proxy_buffering         off;` to the location block of the vhost. However, I don't think this will resolve your issue.

I think this could be a user rights issue. I suggest you login from the problematic computer with a user name that does not see this issue. If you do not see the problem with this user, then it is definitely a user rights issue and not a computer/browser/cache issue.

You might need to check the user/group privileges and/or maybe some plugin is causing this issue by not handling user access rights correctly. In which case you can start isolating the plugins one by one until you find the errant one.

**Comment by joshuacox** [comment]
the problem has not reared it's head again, I doubt it was the 15 second bump in the unicorn timeout though, I'm going to close for now, I might reopen in the future as there's a decent amount of information here, I encourage anyone else to make another issue and reference this one, include a @joshuacox and I'll be sure to try and help as well
