### ISSUE TITLE
apt package required for plugin

### ISSUE THREAD

**Issue by Slind14** [sameersbn/docker-redmine#115]
Hey,

I was wondering what the recommended way would be to install an apt package that is required for a plugin. e.g. https://github.com/a-ono/redmine_ckeditor

**Comment by sameersbn** [comment]
@Slind14 at the moment there is not direct method of installing packages using `apt`. You need to create a custom image from this image using `FROM sameersbn/redmine:3.0.1` and install the required packages there.

That package do you need to install?

**Comment by sameersbn** [comment]
@Slind14 p.s. i was able to install and use the redmine_ckeditor plugin in the image without installing any packages. The `imagemagick` package listed on the https://github.com/a-ono/redmine_ckeditor is already installed in the image.

**Comment by Slind14** [comment]
oO, thanks
