### ISSUE TITLE
Problem with linked mysql Container

### ISSUE THREAD

**Issue by sja87** [sameersbn/docker-redmine#116]
I try to create a new docker-redmine Container with a linked mysql Container.

First I create a new mysql Container

docker run --name=mysql-redmine -d --env='DB_NAME=redmine_production'  --env='DB_USER=redmine' --env='DB_PASS=password' --volume=/srv/docker/redmine/mysql:/var/lib/mysql sameersbn/mysql:latest

After that I try to create the docker-redmine container with version 2.5.2

docker run --name=redmine -it --rm --link=mysql-redmine:mysql --volume=/srv/docker/redmine/redmine:/home/redmine/data sameersbn/redmine:2.5.2

My error:

User: root Password: aesh4aeYohf6
Starting memcached...
Generating secure token...
rake aborted!
Access denied for user 'root'@'172.17.0.31' (using password: NO)
/var/lib/gems/2.1.0/gems/mysql2-0.3.16/lib/mysql2/client.rb:70:in `connect'
/var/lib/gems/2.1.0/gems/mysql2-0.3.16/lib/mysql2/client.rb:70:in `initialize'
/var/lib/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `new'
/var/lib/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `mysql2_connection'
/var/lib/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
/var/lib/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
/var/lib/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
/var/lib/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
/var/lib/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
/var/lib/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
.
.
.
.
.

**Comment by sja87** [comment]
With Redmine Version 3.0.3 everything work fine! What is the problem with Versions < 3 ?

**Comment by sameersbn** [comment]
@sja87 Did you first try using version `3.x.x` and then switch to `2.x.x` version. Then in that case, the `3.x` database schema is probably not compatible with the `2.x` schema. You need to purge your database schema and reinstall.

**Comment by sameersbn** [comment]
@sja87 ok.. I think i know what the problem is. The image tagged `2.5.2-3` does not support fetching the database configuration parameters from the linked database container. You need to specify them in the docker command line. Here is a link to the [README](https://github.com/sameersbn/docker-redmine/tree/v2.5.2-3#linking-to-mysql-container) for the particular image.

**Comment by sameersbn** [comment]
please reopen if your still facing issues.
