### ISSUE TITLE
SMTP SSL not working without SSL=true

### ISSUE THREAD

**Issue by brlo** [sameersbn/docker-redmine#117]
Hello.

Can't send mail through Yandex SMTP until option `ssl => true` was added to `./setup/config/redmine/smtp_settings.rb`

```
if Rails.env.production?
  ActionMailer::Base.delivery_method = :{{SMTP_METHOD}}
  ActionMailer::Base.perform_deliveries = true
  ActionMailer::Base.raise_delivery_errors = true
  ActionMailer::Base.{{SMTP_METHOD}}_settings = {
    :address              => "{{SMTP_HOST}}",
    :port                 => {{SMTP_PORT}},
    :domain               => "{{SMTP_DOMAIN}}",
    :user_name            => "{{SMTP_USER}}",
    :password             => "{{SMTP_PASS}}",
    :authentication       => {{SMTP_AUTHENTICATION}},
    :ssl                  => true,              
    :openssl_verify_mode  => "{{SMTP_OPENSSL_VERIFY_MODE}}",
    :enable_starttls_auto => {{SMTP_STARTTLS}}
  }                                       
end
```

**Comment by sameersbn** [comment]
@brlo I have added `SMTP_TLS` configuration option. Please test with this and let me know if it works or not. Thanks.

**Comment by zoell** [comment]
@sameersbn The SMTP_TLS option won't resolve this. This is still not working as that one only adds TLS, but not SSL. You have to add ssl: true/false as @brlo stated.

I had to add ssl: true to make it work. So you will need a new option, SMTP_SSL.

**Comment by radoslavius** [comment]
Hello, @sameersbn 
"ssl: true" - is still missing. Without this config parameter email can not send.
Thanks
