### ISSUE TITLE
Create a full script installation

### ISSUE THREAD

**Issue by Ange7** [sameersbn/docker-redmine#118]
Hi all o/

In the wiki it's specify « You now have the Redmine application up and ready for testing. If you want to use this image in production the please read on. » 

* What is the step to use this image in production ? 

Do you think is it possible to create a bash script to deploy one redmine environement fastly ?

1. Create MySQL container
2. Create Email container
3. Create Redmine container - Mount data storage location

Thank you all 

Note : Actually redmine is accessible to : IP:PORT do you think is it possible to configure one access for example : track.domain.tld ?

Thank you

**Comment by sameersbn** [comment]
@Ange7 Technically you can use the image in production. I should probable change that like to read "To customize redmine please read on." or something along those line.

**Comment by sameersbn** [comment]
> Do you think is it possible to create a bash script to deploy one redmine environement fastly ?

You can use the docker-compose.yml file to orchestrate the startup.

**Comment by Ange7** [comment]
Thank you

Have you one example how to use docker-compose.yml ?

**Comment by sameersbn** [comment]
@Ange7 a sample `docker-compose.yml` file is already present in the project repository.

**Comment by Ange7** [comment]
cool thank you
