### ISSUE TITLE
Quick Start via docker-compose is not working

### ISSUE THREAD

**Issue by jokogr** [sameersbn/docker-redmine#119]
Hello,

I would like to use docker-redmine 3.0.3 (f7e679395bdf11f653cfeb32b54e93fdcd671000) on an ArchLinux host (Linux 4.0.5-1-ARCH and Docker v1.6.2), but apparently it is not working properly.

I am using the docker-compose.yml that you provide in this repository and these are the last lines:
> redmine_1    | 2015-06-11 17:27:45,030 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> redmine_1    | 2015-06-11 17:27:45,030 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> redmine_1    | 2015-06-11 17:27:45,030 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

Unfortunately pointing the browser to http://localhost:10083 shows nothing. Is there anything more I could try?

**Comment by sameersbn** [comment]
@jokogr the output looks fine to me. If your docker host is a virtual machine, then you will not be able to access the redmine application using `http://localhost:10083`, you should rather use the ip address of the docker host.

**Comment by jokogr** [comment]
@sameersbn you were right, it was an issue with iptables. Everything is working as intended now.
