### ISSUE TITLE
i Can't Link my mysql container to other container.

### ISSUE THREAD

**Issue by Zonork** [sameersbn/docker-redmine#121]
Hello.

I want create anothe container for a DB admin.

i have this:
redmine container
mysql container

redmine linked to mysql 

that works but now i want create another container for a DB admin with phpmyadmin for control the database like this 

redmine container
mysql container
phpmyadmin container

redmine linked to mysql 
phpmyadmin linked to mysql 

but i cant connect to mysql from phpmyadmin

Thanks

**Comment by sameersbn** [comment]
@Zonork can you provide sample docker run or docker-compose.yml configuration for my testing?

**Comment by Zonork** [comment]
Mysql container:  
docker run --name mysql -it --rm \
  -v /srv/docker/redmine/mysql:/var/lib/mysql \
  sameersbn/mysql:latest
  
Redmine Container:
  docker run --name=redmine -it --rm --link mysql:mysql \
  -e "DB_USER=redmine" -e "DB_PASS=password" \
  -e "DB_NAME=redmine_production" \
  -v /srv/docker/redmine/redmine:/home/redmine/data \
  sameersbn/redmine:2.5.2-2

phpmyadmin container:

docker run -i -t --name app_apache_DEV --link mysql:mysql -v /srv/docker/app:/var/www/html -d -p 10080:80 zonork/ubuntu:1

phpmyadmin container: have apache, php5 and phpmyadmin only

**Comment by sameersbn** [comment]
@Zonork have you configured the database connection settings in `config.inc.php` of phpmyadmin? if yes, then please note that the database host should be set to the ip address of the container, or you can use the `mysql` entry added by docker in `/etc/hosts`

**Comment by Zonork** [comment]
in the phpmyadmincontainer or in the mysql container?

**Comment by sameersbn** [comment]
in the `phpmyadmin` container. you do not have to do anything in the `mysql` container. If you want remote root access to the mysql server you might want to start the mysql container with DB_REMOTE_ROOT_NAME` and `DB_REMOTE_ROOT_PASS` variables. Please refer the readme for usage details.

**Comment by nevries** [comment]
@Zonork if you want it quick, I suggest trying https://github.com/corbinu/docker-phpmyadmin for phpmyadmin. It automatically generates a phpmyadmin-config for accessing the mysql-instance in the mysql-container it is linked to. Example:

docker run -d --link mariadb-redmine:mysql --name phpmyadmin-redmine -p 80 corbinu/docker-phpmyadmin

**Comment by sameersbn** [comment]
@Zonork you might want to try @nevries suggestion.

**Comment by Zonork** [comment]
GREAT!! really thanks for your suggestion @nevries, Sorry for the long time for reply, one more time, awesome container @sameersbn
