### ISSUE TITLE
Docker redmine container version 3.0.3-1 failed to start when host machine is disconnected from the Internet

### ISSUE THREAD

**Issue by kcao3** [sameersbn/docker-redmine#122]
Hello,

I would like to use docker-redmine version 3.0.3-1 on my Centos7 host machine, which running Docker version 1.6.0. 
My host machine has a public network interface that allows the machine to send and receive 
network traffic to the Internet. When the host machine is connected to the Internet, everything runs just fine - i.e. I was able to start both of the "postgresql" and "redmine" containers. However, when I move the host machine to an isolated network environment and disconnect it from the Internet, I am no longer able to start the "redmine"" container. The following is the exact error I received from the terminal console while starting the "redmine" docker container:

[root@localhost docker-redmine]# docker run --name=redmine -d \
--link=postgresql-redmine:postgresql --publish=10083:80   \
--env='REDMINE_PORT=10083'  \
--volume=/srv/docker/redmine/redmine:/home/redmine/data  \
sameersbn/redmine:3.0.3-1
d23df9e5f1b004cdaa0acfac7aa76dc03da2af7b1c40dbb66afb2eb3653bab65
FATA[0057] Error response from daemon: Cannot start container d23df9e5f1b004cdaa0acfac7aa76dc03da2af7b1c40dbb66afb2eb3653bab65: Timed out proxy starting the userland proxy 

Does anyone know the root cause for this error and have any idea how to resolve it? I think it is 
a common usecase to have Redmine running in a private network environment. So, any suggestion 
would be highly appreciated here! Thanks for your time and support.

**Comment by sameersbn** [comment]
Can you check to ensure that the `10083` port is not already in use? 
This is some docker port binding issue 
https://github.com/docker/docker/issues/8883. If the port is not in use 
and you are facing the issue try rebooting the system.

**Comment by kcao3** [comment]
Yeah. I am 100% sure that the '10083' port is not currently in use. I also tried rebooting the system but it did NOT make any difference. I was able to reproduce this problem so it's pretty consistent. Specifically, when I re-connect the host machine back to the Internet, this problem does no longer occur.

**Comment by sameersbn** [comment]
Can you check if the issue is present with the following command

```bash
docker run -it --rm --publish=10083:80 ubuntu:14.04 echo "hello, world!"
```

**Comment by kcao3** [comment]
I feel like an "idiot" right now. I have to admit I am not a Linux guru. Could you please tell me what the command ```bash ``` would do?  When running this whole command on my machine, I got this error exact: "bash: !": event not found".

**Comment by kcao3** [comment]
This is the result I received when executing the docker command on my host machine is connected to the Internet:
[root@localhost docker-redmine]# docker run -it --rm --publish=10083:80 ubuntu:14.04 /bin/echo 'Hello world!'
Hello world!

And here is the result I received when executing the same docker command when my host machine is disconnected to the Internet:

[root@localhost docker-redmine]# docker run -it --rm --publish=10083:80 ubuntu:14.04 /bin/echo 'Hello world!'
FATA[0056] Error response from daemon: Cannot start container ad6824efcd496caf89e257de6fdc042e751dca46d0b1fe041d5ac39f7e21bd25: Timed out proxy starting the userland proxy 

Do you think this is an issue with Docker version 1.6.0 rather?

**Comment by sameersbn** [comment]
@kcao3 is the host machine the same when you connect it the internet and otherwise?

**Comment by kcao3** [comment]
Just FYI. I was able to "work around" the issue. It turned out, when my host machine was disconnected from the Internet, I was able to start a Docker container from the ubuntu:14.04 image and expose port 80 from the container and publish it to port 10083 on the host machine by adding this flag "--net=host" to the command:  

docker run -it --rm --publish=10083:80 --net=host ubuntu:14.04 /bin/echo 'Hello world!'

Unfortunately, the flag "--net" is NOT COMPATIBLE with the flag "--link", which was used by the command that starts the Docker Redmine container. 

Fortunately, my actual workaround was to install flannel as an additional virtual network layer, which runs underneath of docker0. This additional configuration allows the container to publish port 80 to port 10083 of the host machine. 

Thank you again for your support yesterday.

**Comment by sameersbn** [comment]
@kcao3 it is weird though. you should probably report the issue on the docker project

**Comment by kcao3** [comment]
It turned out this is a bug in Docker-1.6 version. After rolling back to use the previous docker version of 1.5, I was able to start both of these containers without flannel.

**Comment by sameersbn** [comment]
@kcao3 btw, 1.7 is just out with a new networking stack. You might want to give it a try

**Comment by kcao3** [comment]
I just did. It turned out docker 1.7 is a new beast - i.e it does not seem to support private registry any more. For example, the --add-registry flag was removed from the command line starting docker service.

**Comment by sameersbn** [comment]
@kcao3 first.. did your issue go away?
 You might need to go through the changelog to make sense of the changes.
