### ISSUE TITLE
Git repository 404

### ISSUE THREAD

**Issue by rainyear** [sameersbn/docker-redmine#123]
> The entry or revision was not found in the repository.

**Comment by sameersbn** [comment]
@rainyear please elaborate on the issue you are facing. Possibly share sample commands to reproduce this behaviour

**Comment by sunsided** [comment]
I had the same problem. I'm currently using GitLab directly on the host (planning to upgrade to the dockerized variant someday). The repositories are available under `/srv/git`, which is symlinked to `/home/git/repositories` and are owned by `git:git`. 

When I mount them into the container (`latest` flavor) by using `--volume=/home/git/repositores:/src/git:ro` (with or without `:ro` in both combinations with the the symlinked and real path) they appear in the container under `/srv/git`, owner `1005:1008`. If I `docker exec -it redmine bash` into the container, I can browse the path (albeit finding an invalid `hooks` symlink into gitlab land). When using this path as a repository path in Redmine however, the said error occurs. `docker logs` doesn't give anything useful there (maybe `ruby_12factor` should be included as is in OpenProject?)

I also tried binding the whole gitlab home directory into the container, without success.

I see the very same behavior on OpenProject by the way, using the [abevoelker/docker-openproject](https://github.com/abevoelker/docker-openproject) image.

**Comment by sunsided** [comment]
Just checked the `unicorn.stderr.log` and it states `fatal: Not a git repository: '/home/git/repositories/abc/xyz.git'`.

**Comment by sunsided** [comment]
Another one: I managed to get it working by

1. manually creating a `git` group in the container with the correct GID (`groupadd -g 1234 git`)
2. adding the `redmine` user to that group `usermod -aG git redmine`
3. committing the running container
4. restarting the container

After that, everything worked as expected. Can such a thing be integrated into the `entrypoint.sh`?

**Comment by sameersbn** [comment]
@sunsided the redmine image makes available `USERMAP_UID` and `USERMAP_GID` parameters. You can specify the UID and GID using these parameters and the redmine user will adapt to these settings. Eg.  `-e USERMAP_UID=1005 -e USERMAP_GID=1008`. This will rid you of all the manual steps. https://github.com/sameersbn/docker-redmine/blob/master/entrypoint.sh#L150-L160

I hope this helps.

P.S. Sorry for the late response.

**Comment by sunsided** [comment]
@sameersbn Wouldn't this just make redmine/unicorn run as the git user, preventing access from, say, local svn repositories?

**Comment by sameersbn** [comment]
@sunsided yes.. this will make the redmine user have the same uid/gid of the git user. If your SVN repos are not accessible by your git user then maybe you can set the gid to one that can access the svn repos i guess.

**Comment by sunsided** [comment]
@sameersbn That honestly doesn't sound like a good solution. Is there a hard reason not to extend the entrypoint script? A problem is that the git (and svn, filesystem repo, ...) user group needs to be created before the `redmine` account is used, but from what I can see, the entrypoint is executed as root, so that should be possible (otherwise there's [this](http://superuser.com/a/345051/53942) hack).

**Comment by sameersbn** [comment]
@sunsided well I agree that this is no the most elegant solution. Custom entrypoint script is on my todo list. However at the moment you can work around it by using the plugins init script to setup the user.

**Comment by GordonKiomon** [comment]
@sameersbn i am using sameersbn/redmine:latest with 
docker run --name=redmine -it --rm \
  --env='DB_HOST=HOST_IP' --env='DB_NAME=redmine' \
  --env='DB_USER=USERNAME' --env='DB_PASS=PASSWORD' \
  --env='DB_TYPE=mysql' --publish=80:80\
  --volume=/root/redmine:/home/redmine/data \
  28fcb0db3fcc

and got "404: The entry or revision was not found in the repository" on project repository page. could you suggest. thanks in advance

**Comment by sameersbn** [comment]
@GordonKiomon I don't see a `--volume` or `--volumes-from` argument in your docker command that mounts the git repo's into the container. Where do the git repo's reside in your filesystem? If you do a `docker exec -it redmine bash` can you see them in the filesystem?

**Comment by sameersbn** [comment]
@sunsided fyi, https://github.com/sameersbn/docker-redmine/commit/5f038c010b216156d62b6f4ed112a9d3f78ea123 allows users to launch a custom `entrypoint.custom.sh` script before launching the daemon processes (via `supervisord`).

**Comment by sunsided** [comment]
@sameersbn Will have a look, thanks.

**Comment by GordonKiomon** [comment]
@sameersbn are you referring to "--volume=/root/redmine:/home/redmine/data".
i have it at the end of the docker start command

**Comment by Sawn** [comment]
I don't understand what I'm doing wrong.

I have the same "Not a git repository" message in the logs and 404 error in redmine.

Here are my launch parameters :

> docker run --name redmine -d -v /docker/persistent/redmine:/home/redmine/data --env="USERMAP_UID=5013" --env="USERMAP_GID=5014" -p 10083:80 --env='REDMINE_HTTPS=true' --link=mysql-server:mysql --env='DB_HOST=mysql-server' --env='DB_NAME=redmine' --env='DB_USER=xxx' --env='DB_PASS=xxx' --env='SMTP_USER=xxx' --env='SMTP_PASS=xxx' --env='VIRTUAL_HOST=xxx' sameersbn/redmine

> [root@host ~]# ls -alh /docker/persistent/redmine/repositories/git-repo/
> total 0
> drwxr-xr-x 1 5013 5014  8 22 juin  16:51 .
> drwxr-xr-x 1 5013 5014 30 22 juin  16:51 ..
> drwxr-xr-x 1 5013 5014 98 23 juin  13:48 .git

> [root@host ~]# docker exec -it redmine bash
> root@ea2d9607f69a:/home/redmine/redmine# su - redmine
> redmine@ea2d9607f69a:~$ cd data/repositories/git-repo/
> redmine@ea2d9607f69a:~/data/repositories/ladvelh-android$ git status
> On branch master
> 
> Initial commit
> 
> nothing to commit (create/copy files and use "git add" to track)

What am I missing here please ?

**Comment by sameersbn** [comment]
@Sawn did you copy `git-repo` at `/docker/persistent/redmine/repositories/git-repo/` on the host?

**Comment by jcormier** [comment]
Closed due to age
