### ISSUE TITLE
MySQL default character set forbids 4-byte unicode characters

### ISSUE THREAD

**Issue by nevries** [sameersbn/docker-redmine#126]
This is annoying if you receive emails containing emojis or something like that. The solution is to switch to character set 'uft8mb4'. Can this be done in the Dockerfile init or is to be implemented by redmine?

Please also see http://www.redmine.org/issues/20143 and the tickets references therein.

**Comment by sameersbn** [comment]
@nevries I think it has to be configured in the redmine `database.yml` under encoding. For mysql it is set to `utf8`. Can you try the suggestions in http://www.redmine.org/issues/10772#note-7 and update the `init` script to set the DB_ENCODING to `utf8mb4`.

Changing this value in the init script might break things for existing users. I can provide the option to specify the encoding via a `DB_ENCODING` paramater

**Comment by nevries** [comment]
@sameersbn I surely did that to get my installation working with 4-byte characters ;-)

I would highly recommend to make this parameter (DB_ENCODING) available as you proposed. But please keep in mind that the db init script (is this from Dockerfile or from redmine?) must also set this character encoding and appropriate collation for mysql tables.

Adding this functionality also would enable Japanese users to use the correct encoding (see the redmine.org tickets for what I mean, there is a collation problem with default utf8), so it would really improve your container onto the way to "enterprise ready" ;-)

BTW, I really like this container, great work.
