### ISSUE TITLE
LDAP Conection

### ISSUE THREAD

**Issue by Zonork** [sameersbn/docker-redmine#129]
Hi, im trying connect my redmine to a LDAP server, i can make that directly from my redmine?

**Comment by sameersbn** [comment]
LDAP configuration should be configured directly from the redmine administration panel.
On Monday 06 July 2015 07:00 PM, Pablo Javier wrote:
> Hi, im trying connect my redmine to a LDAP server, i can make that directly from my redmine
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sameersbn/docker-redmine/issues/129
>

-- 
--
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com

**Comment by Zonork** [comment]
Ok, thanks

**Comment by cidhuang** [comment]
Hi Zonork, 

Do you succeed in setting LDAP for redmine?

I don't, could you share your experience for me?

Thank you.

Cid
