### ISSUE TITLE
Docker maps redmine user to non-root user on host

### ISSUE THREAD

**Issue by DeX3** [sameersbn/docker-redmine#130]
Hello,

I was running your awesome container just fine. Recently I had to create an additional user on my host which got assigned UID 1000 (it's the first non-root user on there). The redmine user within your container also has UID 1000. Now, everytime I run the container, all files in the volume that `/home/redmine/data` is mapped to are `chown`'ed to the user with UID 1000 on the host.

I am experiencing `Internal Server Error` for file uploads, and I guess that this is probably the cause of it (because earlier all the files created in the volume belonged to `root`). How do I fix this issue?

**Comment by sameersbn** [comment]
@DeX3 At the moment the redmine images does not have the option to map the redmine user like the gitlab image. You can get around this by changing the UID/GID of you user to not be `1000`

**Comment by DeX3** [comment]
:thumbsup:
