### ISSUE TITLE
Can't run with HTTPS

### ISSUE THREAD

**Issue by Zonork** [sameersbn/docker-redmine#131]
Hi, im trying to enable htts with the guide steps but im still having this:

in firefox : ssl_error_rx_record_too_long

on chrome: ERR_SSL_PROTOCOL_ERROR
Unable to make a secure connection to the server. This may be a problem with the server, or it may be requiring a client authentication certificate that you don't have.

logs are empty.

**Comment by sameersbn** [comment]
@Zonork I would suggest recreating the SSL certificate. p.s. if you were able to setup ssl support with the gitlab container, then the process is exactly the same here.

**Comment by Zonork** [comment]
but if i have a container redmine running without https, i can enable on that container or i need stop and run another container.

PD: im working in a virtual machine. I dont know some much of ssl, i do all the steps of open ssl in my virtual machine and copy the certificate and run the new container.

**Comment by sameersbn** [comment]
@Zonork you need to stop and start it after configuring SSL.

**Comment by Zonork** [comment]
Ok i need do like this:
i have my container running by this commands

docker run --name=mysql -d --env='DB_NAME=redmine_production' --env='DB_USER=redmine' --env='DB_PASS=password' --volume=/srv/docker/redmine/mysql:/var/lib/mysql sameersbn/mysql:latest
docker run --name=redmine -d --link=mysql:mysql --publish=10088:80 --env='REDMINE_PORT=10088' --volume=/srv/docker/redmine/redmine:/home/redmine/data sameersbn/redmine:3.0.3

then i start the open ssl steps:
openssl genrsa -out redmine.key 2048
openssl req -new -key redmine.key -out redmine.csr
openssl x509 -req -days 365 -in redmine.csr -signkey redmine.key -out redmine.crt
openssl dhparam -out dhparam.pem 2048

mkdir -p /srv/docker/redmine/redmine/certs
cp redmine.key /srv/docker/redmine/redmine/certs/
cp redmine.crt /srv/docker/redmine/redmine/certs/
cp dhparam.pem /srv/docker/redmine/redmine/certs/
chmod 400 /srv/docker/redmine/redmine/certs/redmine.key

now i need stop the container like this?

docker stop redmine

and 

docker run --name=redmine -d --link=mysql:mysql --publish=10088:80 --env='REDMINE_PORT=10088' --env='REDMINE_HTTPS=true' --volume=/srv/docker/redmine/redmine:/home/redmine/data sameersbn/redmine:3.0.3

**Comment by Zonork** [comment]
still the same error from a clean docker engine i do that:

docker run --name=mysql -d --env='DB_NAME=redmine_production' --env='DB_USER=redmine' --env='DB_PASS=password' --volume=/srv/docker/redmine/mysql:/var/lib/mysql sameersbn/mysql:latest

docker run --name=redmine -d --link=mysql:mysql --publish=10088:80 --env='REDMINE_PORT=10088' --volume=/srv/docker/redmine/redmine:/home/redmine/data sameersbn/redmine:3.0.3

openssl genrsa -out redmine.key 2048

openssl req -new -key redmine.key -out redmine.csr

openssl x509 -req -days 365 -in redmine.csr -signkey redmine.key -out redmine.crt

openssl dhparam -out dhparam.pem 2048

mkdir -p /srv/docker/redmine/redmine/certs

cp redmine.key /srv/docker/redmine/redmine/certs/

cp redmine.crt /srv/docker/redmine/redmine/certs/

cp dhparam.pem /srv/docker/redmine/redmine/certs/

chmod 400 /srv/docker/redmine/redmine/certs/redmine.key

docker rm -f redmine

docker run --name=redmine -d --link=mysql:mysql --publish=10088:80 --env='REDMINE_PORT=10088' --env='REDMINE_HTTPS=true' --volume=/srv/docker/redmine/redmine:/home/redmine/data sameersbn/redmine:3.0.3

**Comment by sameersbn** [comment]
@Zonork You need to update your docker run command, like this

```bash
docker run --name=redmine -d \
  --link=mysql:mysql \
  --publish=10088:443 --env='REDMINE_PORT=10088' \
  --env='REDMINE_HTTPS=true' \
  --volume=/srv/docker/redmine/redmine:/home/redmine/data \
  sameersbn/redmine:3.0.3
```
and access redmine using https://localhost:10080

**Comment by sameersbn** [comment]
ps. i have updated the docs to add the missing pieces of information. It surprises me that nobody ever faced this problem before.

**Comment by Zonork** [comment]
Thank's that works, sorry for the late answer

**Comment by gekmcfh** [comment]
Hi!
Trying to run same commands with 3.4.4-2 version with no result.
`docker run --name=redmine_prod -it \
  --env='DB_ADAPTER=mysql2' \
  --env='DB_HOST=x.x.x.x' --env='DB_NAME=redmine_prod' \
  --env='DB_USER=redmine_prod' --env='DB_PASS=pass' \
  --volume=/srv/docker/redmine/redmine_prod:/home/redmine/data \
  --publish=10083:80 --publish=10445:443 \
  --env='REDMINE_PORT=10445' --env='REDMINE_HTTPS=true' \
  sameersbn/redmine:3.4.4-2`

Container runs and working on port 10083. But 443 does even not opened inside the container:

`netstat -atnlp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      229/nginx -g daemon
tcp6       0      0 :::80                   :::*                    LISTEN      229/nginx -g daemon
`
