### ISSUE TITLE
Files Backup

### ISSUE THREAD

**Issue by Zonork** [sameersbn/docker-redmine#132]
Hi. i have my redmine application running with this commands: 

docker run --name=mysql -d --env='DB_NAME=redmine_production' --env='DB_USER=redmine' --env='DB_PASS=password' --volume=/srv/docker/redmine/mysql:/var/lib/mysql sameersbn/mysql:latest

docker run --name=redmine -d --link=mysql:mysql --publish=10088:80 --env='REDMINE_PORT=10088' --volume=/srv/docker/redmine/redmine:/home/redmine/data sameersbn/redmine:3.0.3

but my server was down, how i can restore or make a backup of my files? like images a attached files?
they are been copied to /srv/docker/redmine/redmine directory?

**Comment by sameersbn** [comment]
@Zonork The uploaded files etc will be in the `/srv/docker/redmine/redmine`. Mysql database can be backed up in same way you would normally backup a mysql database. The upgrading section has some instruction on mysql database backup.

**Comment by Zonork** [comment]
Thank's @sameersbn i find my files in /srv/docker/redmine/redmine/files
