### ISSUE TITLE
Redmine upgrade to 3.0.4

### ISSUE THREAD

**Issue by Zonork** [sameersbn/docker-redmine#134]
Hi, i want to upgrade mi redmine 3.0.3 to 3.0.4, i have 9 plugins installed, with plugins the steps are the same to upgrade? or i must do another steps?

**Comment by sameersbn** [comment]
The existing plugins will be picked up automatically after the upgrade. You only need to make sure that they are compatible with the new version.

**Comment by Zonork** [comment]
Thanks, my upgrade was solved, sorry for the late answer
