### ISSUE TITLE
no default tracker/status

### ISSUE THREAD

**Issue by chaseadam** [sameersbn/docker-redmine#135]
Loving how easy and memory efficient your docker containers are. Just started up using the quickstart and :latest of postgresql and redmine and noticed there were no trackers or statuses set. This is not clearly indicated in the UI (just no ability to create issues). Is this expected? Maybe this is a "feature" of 3.x I am not aware of yet.

**Comment by sameersbn** [comment]
@chaseadam you need to visit the administration link and select the "Load default configuration" when you see the popup before creating any projects. Did you do it?

**Comment by chaseadam** [comment]
I did not... Thanks for the pointer, works well. I just dove in and created a project which prevented that from displaying. Keep up the good work!
