### ISSUE TITLE
REDMINE_PORT not working

### ISSUE THREAD

**Issue by acabin** [sameersbn/docker-redmine#138]
According to entrypoint.sh , the REDMINE_PORT env should be put into the nginx conf file which at assets/config/nginx/redmine .

However, the conf file has a hard code 80.

The fix should be easy and I'm lazy, so I would not give a pull request.

**Comment by sameersbn** [comment]
@acabin the `REDMINE_PORT` variable does not alter the port on which the internal nginx server listens on. It merely indicates the port on which the redmine application will be accessible to the outside world.

**Comment by acabin** [comment]
But what does entrypoint.sh:279 do?

sed 's/{{REDMINE_PORT}}/'"${REDMINE_PORT}"'/' -i /etc/nginx/sites-enabled/redmine

**Comment by sameersbn** [comment]
It configures http -> https redirection.

**Comment by acabin** [comment]
but it seems have not any effect -- according to the origin conf file

发自我的 iPhone

**Comment by sameersbn** [comment]
It only kicks in when you try to enable SSL. The `sed` command will have 
effect only when the redmine-ssl nginx template is picked.

On Thursday 27 August 2015 06:34 PM, Garveen wrote:
> but it seems have not any effect -- according to the origin conf file
>
> 发自我的 iPhone
>
>  > 在 2015年8月27日，17:41，Sameer Naik <notifications@github.com> 写道：
>  >
>  > It configures http -> https redirection.
>  >
>  > —
>  > Reply to this email directly or view it on GitHub.
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-redmine/issues/138#issuecomment-135418232>.
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com
