### ISSUE TITLE
can't run docker on 10083

### ISSUE THREAD

**Issue by yev** [sameersbn/docker-redmine#139]
Hi,

I'm using the last stable versions of VirtualBox and DockerToolbox for Mac.

I used the provided docker compose script. Everything is started on container. I checked with ps command.

But I can't access the running redmine thong port 10083. telnet localhost 10083 tells me: telnet: connect to address 127.0.0.1: Connection refused

Seems the port forwarding does not work. Any idea?

Tnx in advance.

**Comment by sameersbn** [comment]
You will need to open the ports in virtualbox i think.

**Comment by Estebanv** [comment]
Had the same issue. You have to map the port 80 from the container on the docker-compose.yml.

**Comment by sameersbn** [comment]
@yev did you resolve the issue?

**Comment by yev** [comment]
@sameersbn yep but I dont't remember how I solved it
