### ISSUE TITLE
enable log level and log rotation

### ISSUE THREAD

**Issue by allustin** [sameersbn/docker-redmine#140]
In production we need to shrink and rotate production log, like describe in the http://www.redmine.org/projects/redmine/wiki/RedmineInstall#Logging-configuration

```
config.logger = Logger.new('/path/to/logfile.log', 2, 1000000)
config.logger.level = Logger::INFO
```

whats why it will be usefull to set default log level in container and set the enviroment variable to change that.

in my production it looks like this

```
config.logger = Logger.new(Rails.root.join("log",Rails.env + ".log"),3,5*1024*1024)
config.logger.level = Logger::WARN
```

**Comment by sameersbn** [comment]
The logs are already being rotated using logrotate. In the future if I 
remove crond and logrotate from the image I will use this. Thanks

On Sunday 06 September 2015 03:43 AM, Alexey Lustin wrote:
> In production we need to shrink and rotate production log, like describe
> in the
> http://www.redmine.org/projects/redmine/wiki/RedmineInstall#Logging-configuration
>
> |config.logger = Logger.new('/path/to/logfile.log', 2, 1000000)
> config.logger.level = Logger::INFO |
>
> whats why it will be usefull to set default log level in container and
> set the enviroment variable to change that.
>
> in my it looks like this
>
> |config.logger = Logger.new(Rails.root.join("log",Rails.env +
> ".log"),3,5*1024*1024) config.logger.level = Logger::WARN |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-redmine/issues/140>.
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com
