### ISSUE TITLE
how to request: install additional package on host ubuntu

### ISSUE THREAD

**Issue by allustin** [sameersbn/docker-redmine#141]
there is two redmine plugins

https://github.com/danmunn/redmine_dmsf
and
https://github.com/jbox-web/redmine_git_hosting

the plugins require install some packages

http://redmine-git-hosting.io/get_started/ - i must enable perl, and generate ssh key for redmine user. 

and in redmine_dmsf i must invoke apt-get
```
sudo apt-get install libxapian-ruby1.9.1 xapian-omega libxapian-dev xpdf antiword\ unzip catdoc libwpd-0.9-9 libwps-0.2-2 gzip unrtf catdvi djview djview3 uuid uuid-dev
```

how to install this correctly - through init file for plugin ? now i have error in container when invoke apt-get in the init file

**Comment by sameersbn** [comment]
@allustin In the most recent image releases you can specify additional commands to run before the server is started using a `entrypoint.custom.sh` script. You should add your apt-get commands to this script and copy this script at the root of your redmine data volume.

However this script is executed after the plugin installation step is completed, so it might not work out for you as I believe the plugin installation will fail unless the packages are installed before the plugin installation step is completed.

Please I will try to remedy this issue and let you know.

**Comment by sameersbn** [comment]
@allustin you can now create a `plugins/pre-install.sh` script to install additional packages. Please refer the changes in the readme for details.
