### ISSUE TITLE
Add custom cron task

### ISSUE THREAD

**Issue by miramir** [sameersbn/docker-redmine#142]
For example:
I install plugin https://www.redmine.org/plugins/redmine_email_fetcher, and I need add cron task:
```
*/5 * * * *   www-data /usr/bin/rake -f /opt/redmine/Rakefile --silent redmine:plugins:email_fetcher:fetch_all_emails RAILS_ENV=production 2>&- 1>&-
```

Solution:
1. Create сron.d directory in /srv/docker/redmine/redmine with collection of files with tasks
2. entrypoint.sh syncs /srv/docker/redmine/redmine/cron.d to /etc/cron.d on container start

**Comment by sameersbn** [comment]
@miramir please refer https://github.com/sameersbn/docker-redmine/tree/v3.1.0-2#installing-plugins. In the example, you can see how to install a cronjob as required by a plugin. This is added in a `plugins/init` script.

**Comment by miramir** [comment]
Ok, this solution solve my problem in this case.
