### ISSUE TITLE
Docker - flag provided but not defined: -–publish

### ISSUE THREAD

**Issue by shinhermit** [sameersbn/docker-redmine#150]
The command for the postgresql image works fine, but the command to run the redmine image does not:

```
bash-3.2$ docker run --name=redmine -d \
>   --publish=10083:80 -–publish=10445:443 \
>   --env='REDMINE_PORT=10445' --env='REDMINE_HTTPS=true' \
>   --link=postgresql-redmine:postgresql \
>   --volume=/Users/Josuah/docker/redmine:/home/redmine \
> sameersbn/redmine:3.1.1
flag provided but not defined: -–publish
See 'docker run --help'.
```

I'm using MAC OSX 10.9.5, and installed docker using [the docker tool box](https://www.docker.com/toolbox). I'm running it in a terminal, following [these instructions](https://docs.docker.com/installation/mac/#from-your-shell).

I don't know what additional information may be useful, so please feel free to ask me.

Thanks in advance, cheers.

**Comment by sameersbn** [comment]
@shinhermit i haven't used docker toolbox. but you can try replacing `--publish=` with `-p `

**Comment by jcormier** [comment]
Closing due to old age
