### ISSUE TITLE
hang when creting new issue

### ISSUE THREAD

**Issue by dmrzh** [sameersbn/docker-redmine#152]
steps to reproduce:
1)docker-compose up
2)login and create project
3)create new issue -> save

**Comment by dmrzh** [comment]
log entries:

Completed 500 Internal Server Error in 60316ms (ActiveRecord: 40.4ms)

Net::ReadTimeout (Net::ReadTimeout):
  app/models/mailer.rb:455:in `deliver_mail'
  config/initializers/10-patches.rb:154:in `deliver'
  app/models/mailer.rb:61:in `block in deliver_issue_add'
  app/models/issue.rb:909:in `each_notification'
  app/models/mailer.rb:60:in `deliver_issue_add'
  app/models/issue.rb:1626:in `send_notification'
  app/models/issue.rb:175:in `create_or_update'
  app/controllers/issues_controller.rb:141:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by allustin** [comment]
@dmrzh  May be you need to load default data in Admin area ?

**Comment by sameersbn** [comment]
@dmrzh as @allustin indicated, before creating any projects/issues you need to login to admin area and load default configurations. Only then you can create issues. Please check this.

**Comment by dmrzh** [comment]
I fixing this bug by correcting smtp confoguration.  Probably this bug of redmine.

**Comment by sameersbn** [comment]
Oh. Redmine does not use background job processing. So creation of issues will hang while it is trying to send emails. Which means that if SMTP configuration is not corrent, then redmine hangs.

**Comment by fzerorubigd** [comment]
There is an async mail option for that,  (async_smtp, async_sendmail) http://www.redmine.org/projects/redmine/wiki/EmailConfiguration

**Comment by sameersbn** [comment]
@fzerorubigd remember checking it out. but cannot recollect if i got it working or if there was some issue. Will take a look when I find the time.

**Comment by sameersbn** [comment]
@fzerorubigd actually it is already support using the `SMTP_METHOD` option. Please refer the README for details.
