### ISSUE TITLE
Tag 3.1.1-3 not found in repository sameersbn/redmine

### ISSUE THREAD

**Issue by kt1024** [sameersbn/docker-redmine#153]
~ $ docker pull sameersbn/redmine:3.1.1-3
Pulling repository sameersbn/redmine
Tag 3.1.1-3 not found in repository sameersbn/redmine

only found 3.1.1-1 in tag page.
https://hub.docker.com/r/sameersbn/redmine/tags/

thanks.

**Comment by sameersbn** [comment]
p.s. the images have been moved to quay.io, use `docker pull quay.io/sameersbn/redmine:3.1.1-3`

**Comment by kt1024** [comment]
noted.ths.

**Comment by kt1024** [comment]
pull failed.

---

CoreOS stable (766.4.0)
core@docker01 ~ $ docker pull quay.io/sameersbn/redmine:3.1.1-3
Pulling repository quay.io/sameersbn/redmine
7c6185e9212b: Error pulling image (3.1.1-3) from quay.io/sameersbn/redmine, endpoint: https://quay.io/v1/, Server error: Status 0 while fetching image layer (3fd0c2ae8ed2bb486a1e33dbe7c6185e9212b: Error pulling image (3.1.1-3) from quay.io/sameersbn/redmine, Server error: Status 0 while fetching image layer (3fd0c2ae8ed2bb486a1e33dbe1fb82a26622bad39e699a047cb6a9317be23012)

Error pulling image (3.1.1-3) from quay.io/sameersbn/redmine, Server error: Status 0 while fetching image layer (3fd0c2ae8ed2bb486a1e33dbe1fb82a26622bad39e699a047cb6a9317be23012)

**Comment by sameersbn** [comment]
I am able to pull the image from quay.io

```bash
# docker pull quay.io/sameersbn/redmine:3.1.1-3
Pulling repository quay.io/sameersbn/redmine
7c6185e9212b: Pulling dependent layers 
3fd0c2ae8ed2: Download complete 
9e19ac89d27c: Download complete 
ac65c371c3a5: Download complete 
a5a467fddcb8: Download complete 
c0c063e4bd19: Download complete 
5abcd8bf13a6: Download complete 
54e0f1eed74e: Download complete 
87573b9eac9c: Download complete 
a7f73ee3b0c5: Download complete 
b9e4bc482a52: Downloading [====>                                              ] 10.25 MB/118.5 MB
```

**Comment by kt1024** [comment]
think quay.io was interfere by china's "gfw" firewall. (coreos update is confirmed, and quay.io belongs to coreos).
