### ISSUE TITLE
Container does not (re-)start after host reboot

### ISSUE THREAD

**Issue by arnoldse** [sameersbn/docker-redmine#157]
Hi,
first of all - thanks for this great work!

I used your quick start guide with a postgres and a docker container. Everything works fine - except that the "redmine" container does not start after a reboot of the host system. The postgres container runs smoothly. 

Since I'm very new to Docker, I have no clue where to look first. I checked the Docker reference, but I don't think that the "restart policies" are the right way to fix this.

Thanks.
-Sebastian

BTW: Starting the container manually by "docker start redmine" works fine!

**Comment by sameersbn** [comment]
@arnoldse You can use the `--restart` argument or setup a init.d or systemd startup script. You may refer to https://docs.docker.com/engine/articles/host_integration/ for the available options.

**Comment by arnoldse** [comment]
Hi,

I fixed it with a daily cron job which starts the container. The --restart argument did not work for me.
But thanks again ...
