### ISSUE TITLE
QuickStart procedure fails

### ISSUE THREAD

**Issue by prokher** [sameersbn/docker-redmine#158]
Following Quick Start procedure (described in https://github.com/sameersbn/docker-redmine/blob/master/README.md#quick-start ) leads to the error "Tag 3.2.0 not found in repository docker.io/sameersbn/redmine":

    > docker-compose up
    Pulling postgresql (sameersbn/postgresql:9.4-10)...
    9.4-10: Pulling from sameersbn/postgresql
    813635f4de54: Pull complete
    0b6e7e7fa437: Pull complete
    865e9645cdd2: Pull complete
    337cba9fc8a6: Pull complete
    a453305f189d: Pull complete
    128d15b61bcf: Pull complete
    c79f7c04baaa: Pull complete
    bfa4197a384d: Pull complete
    0838a5b719e1: Pull complete
    81a9ee9a4ae2: Pull complete
    0003a56b4db4: Pull complete
    8010578e47fc: Pull complete
    7ac1ecfda9f0: Pull complete
    Digest: sha256:19febec65d00b1feead70ae417aebbe92423872c6636f6b7fca1122e56caf73f
    Status: Downloaded newer image for sameersbn/postgresql:9.4-10
    Creating prokher_postgresql_1...
    Pulling redmine (sameersbn/redmine:3.2.0)...
    Pulling repository docker.io/sameersbn/redmine
    Traceback (most recent call last):
      File "/usr/bin/docker-compose", line 9, in <module>
        load_entry_point('docker-compose==1.3.1', 'console_scripts', 'docker-compose')()
      File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 31, in main
        command.sys_dispatch()
      File "/usr/lib/python2.7/dist-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
        self.dispatch(sys.argv[1:], None)
      File "/usr/lib/python2.7/dist-packages/compose/cli/command.py", line 34, in dispatch
        super(Command, self).dispatch(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/compose/cli/docopt_command.py", line 24, in dispatch
        self.perform_command(*self.parse(argv, global_options))
      File "/usr/lib/python2.7/dist-packages/compose/cli/command.py", line 66, in perform_command
        handler(project, command_options)
      File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 460, in up
        do_build=not options['--no-build'],
      File "/usr/lib/python2.7/dist-packages/compose/project.py", line 230, in up
        do_build=do_build,
      File "/usr/lib/python2.7/dist-packages/compose/service.py", line 320, in execute_convergence_plan
        do_build=do_build,
      File "/usr/lib/python2.7/dist-packages/compose/service.py", line 208, in create_container
        insecure_registry=insecure_registry,
      File "/usr/lib/python2.7/dist-packages/compose/service.py", line 236, in ensure_image_exists
        self.pull(insecure_registry=insecure_registry)
      File "/usr/lib/python2.7/dist-packages/compose/service.py", line 694, in pull
        stream_output(output, sys.stdout)
      File "/usr/lib/python2.7/dist-packages/compose/progress_stream.py", line 37, in stream_output
        print_output_event(event, stream, is_terminal)
      File "/usr/lib/python2.7/dist-packages/compose/progress_stream.py", line 50, in print_output_event
        raise StreamOutputError(event['errorDetail']['message'])
    compose.progress_stream.StreamOutputError: Tag 3.2.0 not found in repository docker.io/sameersbn/redmine

which I fix by manually removing ""3.2.0" from docker-compose.yml file replacing:

    image: sameersbn/redmine:3.2.0

with:

    image: sameersbn/redmine

After that procedure goes well till the end but attempt to open http://localhost:10083/ gives me 500 error:

    Internal error
    An error occurred on the page you were trying to access.
    If you continue to experience problems please contact your Redmine administrator for assistance.
    If you are the Redmine administrator, check your log files for details about the error.

and ERROR in the terminal:

    ...
    redmine_1    | 2015-12-12 19:05:35,027 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
    postgresql_1 | ERROR:  relation "settings" does not exist at character 323
    postgresql_1 | STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
    postgresql_1 | 	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
    postgresql_1 | 	                FROM pg_attribute a LEFT JOIN pg_attrdef d
    postgresql_1 | 	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
    postgresql_1 | 	               WHERE a.attrelid = '"settings"'::regclass
    postgresql_1 | 	                 AND a.attnum > 0 AND NOT a.attisdropped
    postgresql_1 | 	               ORDER BY a.attnum
    postgresql_1 | 	

Obviously restarting does not help.

I think it is worth fixing. I use Ubuntu 15.10 if it matters.

Best regards,
Alexander.

**Comment by sameersbn** [comment]
I forgot to tag the 3.2.0 release. Corrected the error. Please retry after the 3.2.0 build is ready. You can watch the build status here https://hub.docker.com/r/sameersbn/redmine/builds/

**Comment by prokher** [comment]
Thank you for quick respond!

Anyway I already installed Redmine with

    docker run -p 3000:3000 -d --name my-redmine redmine

that raised the question, why do we need "sameersbn/redmine" ?

**Comment by sameersbn** [comment]
> why do we need "sameersbn/redmine"

I have not used the "official" redmine image as a result I cannot tell you which one is better.

What I can tell you is that this image was created before the official redmine image and a lot of people use this image and hence continues to be maintained and updated. Apart from that you can refer to the readme to see if there is anything that interests you. 

Closing the issue since you have it resolved.

**Comment by daks** [comment]
I got this exact problem just now, and using sameersbn/redmine:3.2.0 solved the problem.

**Comment by sabeen-chocolatecoded** [comment]
ERROR:  relation "settings" does not exist at character 323
postgresql_1  | STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
postgresql_1  | 	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
postgresql_1  | 	                FROM pg_attribute a LEFT JOIN pg_attrdef d
postgresql_1  | 	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
postgresql_1  | 	               WHERE a.attrelid = '"settings"'::regclass
postgresql_1  | 	                 AND a.attnum > 0 AND NOT a.attisdropped
postgresql_1  | 	               ORDER BY a.attnum

I am using the version 3.3.2
