### ISSUE TITLE
Redmine not working with data of dump file

### ISSUE THREAD

**Issue by taniadaniela** [sameersbn/docker-redmine#159]
I've created a dump file of my old redmine app (version 2.3.1) and I have use the sameersbn/redmine:2.5.0.. I've restore the dump file and the data is in the mysql container (using sameersbn/mysql:latest). The app is working but I can't login with the users of the dump file and I can't see the projects.. There's no error visible in the console.. Any ideas please?

**Comment by taniadaniela** [comment]
checking redmine/config/database.yml I've found that the username and pass arent the same as the docker-compose.yml. I've tried to change manually in this file but still not able to use the data of the dump file.
```production:
  adapter: mysql2
  database: redmine_production
  host: localhost
  port: 3306
  username: root
  password: 
  pool: 5```

**Comment by taniadaniela** [comment]
also when I execute docker-compose up this is show in the console at the end of process:
```
redmine_1 | ==  AddTagsAndTaggings: migrated (0.0384s) ====================================
redmine_1 | 
redmine_1 | Migrating redmine_tweaks (Redmine Tweaks)...
redmine_1 | --2015-12-16 03:15:32--  http://localhost/
redmine_1 | Resolving localhost (localhost)... ::1, 127.0.0.1
redmine_1 | Connecting to localhost (localhost)|::1|:80... failed: Connection refused.
redmine_1 | Connecting to localhost (localhost)|127.0.0.1|:80... connected.
redmine_1 | HTTP request sent, awaiting response... 200 OK
redmine_1 | Length: 3237 (3.2K) [text/html]
redmine_1 | Saving to: `/dev/null'
redmine_1 | 
redmine_1 |      0K ...                                                   100%  313M=0s
```

that Connection refused doesn't seem good.

**Comment by sameersbn** [comment]
The values in `database.yml` reflect the configuration in `docker-compose.yml` so you may need to first update it. Once that is done, in the persistent volume you will see a folder named `tmp`, delete it and start the container. In the absence of the `tmp/VERSION` file, the container will perform the migrations.
