### ISSUE TITLE
Backup DataSource Redmine

### ISSUE THREAD

**Issue by adrianobr** [sameersbn/docker-redmine#165]
Hi, I have the latest version of https://github.com/sameersbn/docker-redmine.

I'm trying to create backups this way:

```
docker run --name = sysmo_redmine_v4 -i -t --link = sysmo_postgres_redmine_v4: postgresql --publish = 10083: 80 --env = 'REDMINE_PORT = 10083' --volume = / srv / docker / redmine / redmine: / home / redmine / sysmo_redmine date: v2 app: Backup: create
```

The result I get is:

```
Waiting for database server to accept connections
```

When running docker docker ps or ps -a:

`054ab25fa010 sysmo_redmine: v2 "/sbin/entrypoint.sh" 5 seconds ago Exited (1) 5 seconds ago sysmo_redmine_v4`

Does not keep the OPTIONS settings.

When running:

```
docker start 054ab25fa010
```

does not start the container

Am I doing something incorrect?

**Comment by sameersbn** [comment]
The log would be helpful and also using `sameersbn/redmine:x.x.x` would be helpful to understand the issue.

Note that `app:backup:create` creates a backup and the container exits after which you have to start the container normally (i.e. without `app:backup:create`)

**Comment by jcormier** [comment]
Closing due to age
