### ISSUE TITLE
Automated backups not working

### ISSUE THREAD

**Issue by fendo64** [sameersbn/docker-redmine#169]
Hello,

The file "database.sql" is empty and have this error on backup.log:

Dumping MySQL database redmine...
/etc/docker-redmine/runtime/functions: line 47: MYSQL_PWD=pswredmine: command not found

**Comment by sameersbn** [comment]
Can you please share sample docker run or docker-compose.yml that will allow me to reproduce the issue?

**Comment by fendo64** [comment]
Hello,

Le 08/01/2016 11:01, Sameer Naik a écrit :
> Can you please share sample docker run or docker-compose.yml that will
> allow me to reproduce the issue?

manual execution of "redmine-backup-create" works as "root", but not
with the user "redmine" and cron is in redmine user.

root@29bbffefa91b:/home/redmine/redmine# su redmine
redmine@29bbffefa91b:~/redmine$ redmine-backup-create
Dumping MySQL database redmine...
/etc/docker-redmine/runtime/functions: line 47: MYSQL_PWD=pswredmine:
command not found


I build the container and uses the files attached:
docker build --tag=local/redmine:3.2.0 .
docker-compose up -d


FROM sameersbn/ubuntu:14.04.20151213
MAINTAINER sameer@damagehead.com

ENV REDMINE_VERSION=3.2.0 \
    REDMINE_USER="redmine" \
    REDMINE_HOME="/home/redmine" \
    REDMINE_LOG_DIR="/var/log/redmine" \
    REDMINE_CACHE_DIR="/etc/docker-redmine" \
    RAILS_ENV=production

ENV REDMINE_INSTALL_DIR="${REDMINE_HOME}/redmine" \
    REDMINE_DATA_DIR="${REDMINE_HOME}/data" \
    REDMINE_BUILD_DIR="${REDMINE_CACHE_DIR}/build" \
    REDMINE_RUNTIME_DIR="${REDMINE_CACHE_DIR}/runtime"

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E1DD270288B4E6030699E45FA1715D88E1DF1F24 \
 && echo "deb http://ppa.launchpad.net/git-core/ppa/ubuntu trusty main" >> /etc/apt/sources.list \
 && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 80F70E11F0F0D5F10CB20E62F5DA5F09C3173AA6 \
 && echo "deb http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu trusty main" >> /etc/apt/sources.list \
 && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8B3981E7A6852F782CC4951600A6F0A3C300EE8C \
 && echo "deb http://ppa.launchpad.net/nginx/stable/ubuntu trusty main" >> /etc/apt/sources.list \
 && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
 && echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
 && apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y supervisor logrotate nginx mysql-client postgresql-client \
      imagemagick subversion git cvs bzr mercurial darcs rsync ruby2.1 locales openssh-client \
      gcc g++ make patch pkg-config gettext-base ruby2.1-dev libc6-dev zlib1g-dev libxml2-dev \
      libmysqlclient18 libpq5 libyaml-0-2 libcurl3 libssl1.0.0 \
      libxslt1.1 libffi6 zlib1g gsfonts \
 && update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX \
 && gem install --no-document bundler \
 && rm -rf /var/lib/apt/lists/*

COPY assets/build/ ${REDMINE_BUILD_DIR}/
RUN bash ${REDMINE_BUILD_DIR}/install.sh

COPY assets/runtime/ ${REDMINE_RUNTIME_DIR}/
COPY assets/tools/ /usr/bin/
COPY entrypoint.sh /sbin/entrypoint.sh
RUN chmod 755 /sbin/entrypoint.sh

EXPOSE 80/tcp 443/tcp

VOLUME ["${REDMINE_DATA_DIR}", "${REDMINE_LOG_DIR}"]
WORKDIR ${REDMINE_INSTALL_DIR}
ENTRYPOINT ["/sbin/entrypoint.sh"]
CMD ["app:start"]

**Comment by sameersbn** [comment]
Thanks for investigating this issue. It has now need fixed. Please do let me know if you notice any issues.
