### ISSUE TITLE
`dock run --user` parameter should override container's `redmine` user

### ISSUE THREAD

**Issue by endersonmaia** [sameersbn/docker-redmine#171]
When I run this container definif a user, the container won't get up.

I defined this `user: www-data` inside my `docker-compose.yml`.

```
# docker-compose up
Creating redmine_app_1
Attaching to redmine_app_1
app_1 | Initializing logdir...
app_1 | mkdir: cannot create directory '/var/log/redmine/supervisor': Permission denied
redmine_app_1 exited with code 0
```

I think the container should respect the parameters from the `docker run`, letting them override the default parameters from the container's initialization scripts.

**Comment by sameersbn** [comment]
@endersonmaia there is a setup taking place in the container that require `root` privileges. This includes but is not limited to:
 - correcting file/directory permissions
 - starting supervisor

Specifying `--user` while starting the container means that the specified user unless that is `root` will not be able to correctly setup the container for launch.

What is your use case here? Why do you want to launch the container with `--user www-data`? Maybe you need to look at https://github.com/sameersbn/docker-redmine#mapping-host-user-and-group if thats what you are interested in.

Thank you.

**Comment by endersonmaia** [comment]
I get an error when define the `www-data` UID 'cause it already exists (33) on the host system and on the container.

**Comment by sameersbn** [comment]
existence of the user on the host is fine. but i am not sure how to handle the case where a user with the requested UID already exists in the container (`www-data` in this case). Possible solution is to remove the existing user in this case before performing the uid mapping. However I am not sure whether this could have any negative effects.

**Comment by jcormier** [comment]
Closing due to old age
