### ISSUE TITLE
redmine + mysql not working

### ISSUE THREAD

**Issue by YaruTsai** [sameersbn/docker-redmine#173]
$docker info
Containers: 3
Images: 85
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 91
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 19.36 GiB
Name: TS
ID: L67C:GOPN:PR2M:A2EO:QIOO:C6MP:D36E:TBYU:VXNQ:RCUD:EPU6:PQLD
WARNING: No swap limit support

First, I tried redmine + postgresql container that it's working.

but I want to use redmine and mysql, I try below command:

$docker run --name=mysql-redmine -d \
  --env='DB_NAME=redmine_production' \
  --env='DB_USER=redmine' --env='DB_PASS=password' \
  --volume=/srv/docker/redmine/mysql:/var/lib/mysql \
  sameersbn/mysql:latest

$docker run --name=redmine -d \
  --link=mysql-redmine:mysql --publish=10083:80 \
  --env='REDMINE_PORT=10083' \
  --volume=/srv/docker/redmine/redmine:/home/redmine/data \
  sameersbn/redmine:3.2.0-4

$docker ps

CONTAINER ID        IMAGE                       COMMAND                CREATED              STATUS              PORTS                            NAMES
ad049fcf8508        sameersbn/redmine:3.2.0-4   "/sbin/entrypoint.sh   About a minute ago   Up 59 seconds       443/tcp, 0.0.0.0:10083->80/tcp   redmine             
801a4533b1c3        sameersbn/mysql:latest      "/sbin/entrypoint.sh   25 minutes ago       Up 25 minutes       3306/tcp                         mysql-redmine 

After 1 minute, redmine container is missing. Can you tell me how to troubleshooting?

**Comment by sameersbn** [comment]
The mysql container does not seem to be starting. Please check the container logs to find out why `docker logs -f mysql-redmine`

**Comment by YaruTsai** [comment]
cherry@TS:~$ docker logs -f mysql-redmine
Creating database "redmine_production"...
Granting access to database "redmine_production" for user "redmine"...
160127 06:02:26 mysqld_safe Logging to syslog.
160127 06:02:26 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql

just only..

**Comment by YaruTsai** [comment]
I'm so sorry, it's my fault. I knew what happened.
I check mysql database.

```
$mysql -u redmine -p password
mysql> show databases;
mysql> show redmine_production;
mysql> show tables;
```

DB was Empty. Then I import my backup redmine.sql
`
$mysqldump -u redmine -p password redmine_production < redmine.sql`

Now it is working.
