### ISSUE TITLE
`secret_key_base` not set

### ISSUE THREAD

**Issue by lacek** [sameersbn/docker-redmine#174]
I keep seeing this warning in production.log: `DEPRECATION WARNING: You didn't set config.secret_key_base`

With a bit of searching, I found the following info:

* In Rails 4.0, [encrypted cookies is introduced](http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#action-pack) (more secure comparing to signed cookies in Rails 3)
* In Rails 4.1, [`secrets.yml` convention is introduced](http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#config-secrets-yml)
* In Redmine 3.2.0 Installation Guide, `bundle exec rake generate_secret_token` is used for [generating secret token](http://www.redmine.org/projects/redmine/wiki/RedmineInstall/320#Step-5-Session-store-secret-generation), which indeed creates `config/initializers/secret_token.rb` that configures `secret_key_base`

So for minimal change, we could probably add a new parameter `REDMINE_SECRET_KEY_BASE` that is written to `config/configuration.yml` as [Rails is reading from both config and secrets](https://github.com/rails/rails/blob/4-2-stable/railties/test/application/configuration_test.rb#L406).
Or writes both `REDMINE_SECRET_KEY_BASE` and `REDMINE_SECRET_TOKEN` into `config/secrets.yml` if new convention is preferred.

**Comment by sameersbn** [comment]
While i see the issue you reported, the value of `secret_token` (i.e. `REDMINE_SECRET_TOKEN`) in `config/configuration.yml` I believe is supposed to be set by redmine for `config.secret_key_base`. 

I think only one of these values is required. If that is the case, then we can only correct the configuration without adding any new parameters.

**Comment by lacek** [comment]
I believe only `secret_key_base` is required. The `secret_token` is left for compatibility and smooth transition of Rails 3 to 4 according to their upgrade guide:
> Please note that you should wait to set secret_key_base until you have 100% of your userbase on Rails 4.x and are reasonably sure you will not need to rollback to Rails 3.x. This is because cookies signed based on the new secret_key_base in Rails 4.x are not backwards compatible with Rails 3.x.

**Comment by Zandy** [comment]
same for me...
there is a 500 error if not configured config.secret_key_base
```bash
# this work for me
docker exec redmine sed -i "s#:log#:log\n  config.secret_key_base = 'tetx'#" /home/redmine/redmine/config/environments/production.rb
docker exec redmine cat /home/redmine/redmine/config/environments/production.rb
```

**Comment by Zandy** [comment]
same for me...
there is a 500 error if not configured config.secret_key_base
```bash
# this works for me
docker exec redmine sed -i "s#:log#:log\n  config.secret_key_base = 'tetx'#" /home/redmine/redmine/config/environments/production.rb
docker exec redmine cat /home/redmine/redmine/config/environments/production.rb
```

**Comment by Zandy** [comment]
same for me...
there is a 500 error if not configured config.secret_key_base
```bash
# this works for me
docker exec redmine sed -i "s#:log#:log\n  config.secret_key_base = 'xxx'#" /home/redmine/redmine/config/environments/production.rb
docker exec redmine cat /home/redmine/redmine/config/environments/production.rb
```
