### ISSUE TITLE
SMTP Mail is not working from Redmine

### ISSUE THREAD

**Issue by ankurgla22** [sameersbn/docker-redmine#175]
I am trying to configure SMTP mail in from redmine server in following way:

docker run --name=redmine -d -p 80:80 --link mysql:mysql --volume=/var/www/html/docker/:/home/redmine/data --env='SMTP_HOST=Host_name' --env='SMTP_PORT=25' sameersbn/redmine:latest

But it's not working.
Can you help me. Where I am wrong?

**Comment by sameersbn** [comment]
You may need to specify the SMTP_USER, SMTP_PASS, etc. Please refer to https://github.com/sameersbn/docker-redmine#mail for more details.

**Comment by ankurgla22** [comment]
Actually i have a SMTP server address only. There is no need of user and password.
My server is working with simple python code. I can send mails with it.
But I don't know how to configure it in Redmine.

**Comment by ankurgla22** [comment]
Thanks 
I works.
I have to include 
--env='SMTP_OPENSSL_VERIFY_MODE=none' 
--env='SMTP_AUTHENTICATION=none'
 --env='SMTP_ENABLED=true'
