### ISSUE TITLE
SMTP_USER parameters enables IMAP

### ISSUE THREAD

**Issue by lacek** [sameersbn/docker-redmine#178]
When one sets `SMTP_USER` to a truthy value, `IMAP_USER` is set to the same value which turns out [enables IMAP](https://github.com/sameersbn/docker-redmine/blob/46ed502/assets/runtime/env-defaults#L95).
This behavior isn't stated in the README, though usually it won't cause any problem even the mail server doesn't have IMAP supported/enabled.

However, user should be noted that a cron job is appended at every start of the container. In my case, I restarted the container without removing it many times for installing and testing plugins. There are then many duplicated cron entries for receiving mail, which eventually exhaust the machines memory.

**Comment by xhervy** [comment]
Experience the same issue. Running this on a NAS with not that much memory available, this behaviour cause a lot of issue for me.

I also noticed that the backup cronjob is added every time I start the container
