### ISSUE TITLE
Internal error "My page -> Issues assigned to me"

### ISSUE THREAD

**Issue by panou63** [sameersbn/docker-redmine#182]
Hi, 

When trying to browse "My page -> Issues assigned to me" or "My page -> Reported issues " I get "Internal error". I get the error with version 2.6.6-1 and 2.6.9-3.
Any idea on this error ? How can I enable debug log ?

Error in production.log

Completed 500 Internal Server Error in 338.3ms
NoMethodError (undefined method `enabled_modules' for nil:NilClass):
  app/models/query.rb:235:in `build_from_params'
  app/models/issue_query.rb:119:in `build_from_params'
  app/helpers/queries_helper.rb:179:in `retrieve_query'
  app/controllers/issues_controller.rb:56:in `index'

Regards

**Comment by sameersbn** [comment]
was your issue resolved?

**Comment by panou63** [comment]
Hi, 

Yes, the error was caused by a plugin. I uninstalled it and it resolved the issue.

Regrads,
