### ISSUE TITLE
ERROR: Tag 3.2.0-5 not found in repository docker.io/sameersbn/redmine

### ISSUE THREAD

**Issue by mgcrea** [sameersbn/docker-redmine#183]
```
# docker-compose up -d
redmine_postgresql is up-to-date
Pulling backend (sameersbn/redmine:3.2.0-5)...
Pulling repository docker.io/sameersbn/redmine
ERROR: Tag 3.2.0-5 not found in repository docker.io/sameersbn/redmine
```

**Comment by yuanying** [comment]
I also faces same problem.
It seems that there is no 3.2.0-5 tag in hub.docker.com.

* https://hub.docker.com/r/sameersbn/redmine/tags/

**Comment by sameersbn** [comment]
appears to be that docker hub did not pick the new git tags. this is really shitty, happens every now and then. anyways I have triggered manual builds of the missing tags. Please check in some time.
