### ISSUE TITLE
use "bundle install --local" in case of new plugins

### ISSUE THREAD

**Issue by EzVoodoo** [sameersbn/docker-redmine#184]
Thank you for the awesome work!

For some reason, I can only use Redmine in local servers. Thus when a plugin requires a new gem to be installed, the bundle process will fail as it cannot access the internet while trying to fetch a gem from https://rubygems.org and the docker container will exit.

To work around this, I wonder if it is viable to use the pre-install.sh script to manually install the gems first and then trigger  "bundle install --local" when new plugins are copied into the host volume plugin directory?

**Comment by sameersbn** [comment]
did you give it a try>

**Comment by frank-dspeed** [comment]
@EzVoodoo did you try it? did it work ? 
i will close that as i am not sure if this still is a issue if it is please reopen thanks for reporting
