### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by previa** [sameersbn/docker-redmine#185]
root@viralrank:/tmp# docker-compose up
Creating tmp_postgresql_1
Creating tmp_redmine_1
Attaching to tmp_postgresql_1, tmp_redmine_1
postgresql_1 | Initializing datadir...
redmine_1    | Initializing logdir...
redmine_1    | Initializing datadir...
redmine_1    | Symlinking dotfiles...
redmine_1    | Installing configuration templates...
redmine_1    | Configuring redmine...
postgresql_1 | Initializing certdir...
postgresql_1 | Initializing logdir...
postgresql_1 | Initializing rundir...
postgresql_1 | Setting resolv ACLs...
postgresql_1 | Creating database user: redmine
postgresql_1 | Creating database: redmine_production...
postgresql_1 | ‣ Granting access to redmine user...
postgresql_1 | Starting PostgreSQL 9.4...
postgresql_1 | LOG:  database system was shut down at 2016-03-02 08:10:24 UTC
postgresql_1 | LOG:  MultiXact member wraparound protections are now enabled
postgresql_1 | LOG:  autovacuum launcher started
postgresql_1 | LOG:  database system is ready to accept connections
redmine_1    | Configuring redmine::database...
redmine_1    | Configuring redmine::unicorn...
redmine_1    | Configuring redmine::secret_token...
redmine_1    | Generating a session token...
redmine_1    | Note:
redmine_1    |   All old sessions will become invalid.
redmine_1    |   Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
redmine_1    |   **SHOULD** be defined if you have a load-balancing Redmine cluster.
redmine_1    | Configuring redmine::max_concurrent_ajax_uploads...
redmine_1    | Configuring redmine::sudo_mode...
redmine_1    | Configuring redmine::backups...
redmine_1    | Configuring nginx...
redmine_1    | Configuring nginx::redmine...
redmine_1    | Migrating database. Please be patient, this could take a while...
postgresql_1 | FATAL:  password authentication failed for user "redmine"
postgresql_1 | DETAIL:  Connection matched pg_hba.conf line 94: "host all all 0.0.0.0/0 md5"
redmine_1    | FATAL:  password authentication failed for user "redmine"
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
redmine_1    | /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
redmine_1    | /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:87:in `connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/tasks/postgresql_database_tasks.rb:6:in `connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/tasks/postgresql_database_tasks.rb:15:in `create'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:93:in `create'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:107:in `block in create_current'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:275:in `block in each_current_configuration'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:274:in `each'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:274:in `each_current_configuration'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:106:in `create_current'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
redmine_1    | /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
redmine_1    | Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "database"=>"redmine_production", "host"=>"postgresql", "port"=>5432, "username"=>"redmine", "password"=>"password", "pool"=>5}
postgresql_1 | FATAL:  password authentication failed for user "redmine"
postgresql_1 | DETAIL:  Connection matched pg_hba.conf line 94: "host all all 0.0.0.0/0 md5"
redmine_1    | rake aborted!
redmine_1    | PG::ConnectionBad: FATAL:  password authentication failed for user "redmine"
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:87:in `connection'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/model_schema.rb:230:in `table_exists?'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/primary_key.rb:97:in `get_primary_key'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/primary_key.rb:85:in `reset_primary_key'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/primary_key.rb:73:in `primary_key'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/attribute_assignment.rb:15:in `attributes_protected_by_default'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:337:in `block in protected_attributes_configs'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:222:in `yield'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:222:in `protected_attributes'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:126:in `block in attr_protected'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:125:in `each'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:125:in `attr_protected'
redmine_1    | /home/redmine/redmine/app/models/custom_field.rb:36:in `<class:CustomField>'
redmine_1    | /home/redmine/redmine/app/models/custom_field.rb:18:in `<top (required)>'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:360:in `require_or_load'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:494:in `load_missing_constant'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:526:in `load_missing_constant'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:526:in `load_missing_constant'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:526:in `load_missing_constant'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
redmine_1    | /home/redmine/redmine/lib/redmine/field_format.rb:87:in `field_attributes'
redmine_1    | /home/redmine/redmine/lib/redmine/field_format.rb:90:in `<class:Base>'
redmine_1    | /home/redmine/redmine/lib/redmine/field_format.rb:48:in `<module:FieldFormat>'
redmine_1    | /home/redmine/redmine/lib/redmine/field_format.rb:19:in `<module:Redmine>'
redmine_1    | /home/redmine/redmine/lib/redmine/field_format.rb:18:in `<top (required)>'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
redmine_1    | /home/redmine/redmine/lib/redmine.rb:38:in `<top (required)>'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
redmine_1    | /home/redmine/redmine/config/initializers/30-redmine.rb:6:in `<top (required)>'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:652:in `block in load_config_initializer'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:651:in `load_config_initializer'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `each'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `block in <class:Engine>'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
redmine_1    | /home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:328:in `require_environment!'
redmine_1    | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:457:in `block in run_tasks_blocks'
redmine_1    | Tasks: TOP => db:migrate => environment
redmine_1    | (See full trace by running task with --trace)
tmp_redmine_1 exited with code 1

how to trace about this error ? thanks.

**Comment by previa** [comment]
I am stupid. It's because I already manually start a postgresql using docker run with different password before.

**Comment by sameersbn** [comment]
Glad you got it resolved :+1:
