### ISSUE TITLE
Redmine session random timeout

### ISSUE THREAD

**Issue by ClaymorePT** [sameersbn/docker-redmine#187]
Hi!
I don't know if this is the correct place for this issue, but since it happens with a default instance of this redmine docker, I wonder if anyone can help me with this issue.

After I login with the default admin account, the session expires after a random time.
Sometimes it expires right away, sometimes it can take about 30 seconds. But it always end up expiring.

This is the "docker run" attributes that I use:

`sudo docker run -d --name=RedmineDock -ti -e TERM=xterm -e DB_ADAPTER=mysql2 -e DB_HOST=192.168.80.40 -e DB_NAME=redmine -e DB_USER=redmine -e DB_PASS=xyz -v /mnt/glusterfs/redmine:/home/redmine/data -p 192.168.80.40:80:80 sameersbn/redmine
`

Thank you!

**Comment by CombatCode** [comment]
Maybe some cron jobs are running inside the remdine? to fetch emails or repositories

**Comment by wq163** [comment]
me too ,when I upgrade to 3.2.1-2

**Comment by ClaymorePT** [comment]
The problem occurs for a default installation.

On 21 April 2016 at 09:34, jenwang <notifications@github.com> wrote:

> me too ,when I upgrade to 3.2.1-2
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-redmine/issues/187#issuecomment-212808339>
>



-- 

Carlos Miguel Ferreira
Researcher at Telecommunications Institute
Aveiro - Portugal
Work E-mail - cmf@av.it.pt
Skype & GTalk -> carlosmf.pt@gmail.com
LinkedIn -> http://www.linkedin.com/in/carlosmferreira

**Comment by sameersbn** [comment]
Thanks for reporting. I will take a look. Maybe related to #174

**Comment by ClaymorePT** [comment]
Thank you :)

On 21 April 2016 at 16:54, Sameer Naik <notifications@github.com> wrote:

> Thanks for reporting. I will take a look. Maybe related to #174
> <https://github.com/sameersbn/docker-redmine/issues/174>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-redmine/issues/187#issuecomment-212984749>
>



-- 

Carlos Miguel Ferreira
Researcher at Telecommunications Institute
Aveiro - Portugal
Work E-mail - cmf@av.it.pt
Skype & GTalk -> carlosmf.pt@gmail.com
LinkedIn -> http://www.linkedin.com/in/carlosmferreira

**Comment by sameersbn** [comment]
Sorry for the delay. I have made fixes related to #174 
Can you please test against the latest releases and let me know if the issue goes away?

**Comment by ClaymorePT** [comment]
Thanks for the heads-up but we are no longer using your docker-redmine
image. Be decided not to use docker at all because of all the limitations
with the network configurations and customisation.


On 13 June 2016 at 07:45, Sameer Naik <notifications@github.com> wrote:

> Sorry for the delay. I have made fixes related to #174
> <https://github.com/sameersbn/docker-redmine/issues/174>
> Can you please test against the latest releases and let me know if the
> issue goes away?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sameersbn/docker-redmine/issues/187#issuecomment-225500723>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHTtIbnXuJeRdDNXKGAwxTgVO_bI3L67ks5qLPx7gaJpZM4Hu4Id>
> .
>



-- 

Carlos Miguel Ferreira
Researcher at Telecommunications Institute
Aveiro - Portugal
Work E-mail - cmf@av.it.pt
Skype & GTalk -> carlosmf.pt@gmail.com
LinkedIn -> http://www.linkedin.com/in/carlosmferreira

**Comment by sameersbn** [comment]
@CombatCode @wq163 can any of you guys please check?

**Comment by wq163** [comment]
I have resolved this problem. 
I found many `bundle exec rake redmine:email:receive_imap host=imap.gmail.com port=993 ...` process running on server.  
Maybe the default settings of imap is change in 3.2.1-2 ?   
I set `IMAP_ENABLED=false` ,then everything is ok !

**Comment by jcormier** [comment]
Closing due to old age
