### ISSUE TITLE
restart the app without restarting the container

### ISSUE THREAD

**Issue by taniadaniela** [sameersbn/docker-redmine#196]
Hi. CAn somebody indicate me how to restart the redmine app without restarting the container? 
touch tmp/restart.txt doesn't work.

**Comment by sameersbn** [comment]
try `docker exec -it redmine supervisorctl restart unicorn `

**Comment by taniadaniela** [comment]
thanks!. that worked.

**Comment by karippery** [comment]
hello @sameersbn  
what is supervisorctl  and unicorn.
i got error like
`: exec failed: container_linux.go:344: starting container process caused "exec: /"supervisorctl"/ `

my task is install plugin to redmine 
after installing i try to restart redmine  (docker restart redmine) 
my container got fail exited(1)
i tried docker container restart redmine
again i got fail
my question is how can i restart redmine(docker) after installing plugin 

please help me

**Comment by jjcf89** [comment]
> please help me

Please create a new issue.  Your problem does not appear related to the issue from 2016.

**Comment by jjcf89** [comment]
Also please provide a log of the commands you are running and their output.
