### ISSUE TITLE
redmine 3.2.3, ubuntu 16.04, mysql 5.7 not currently supported

### ISSUE THREAD

**Issue by krdi** [sameersbn/docker-redmine#201]
Need redmine 3.2.3, ubuntu 16.04, mysql 5.7 ?.  I have updated your scripts and the build is working and can upload if you want.
Very nice work done here.  Well thought out. -thx

kr

**Comment by syntacticvexation** [comment]
+1

**Comment by sameersbn** [comment]
Have upgraded to 3.2.3 at the moment.
Will upgrade the base images soon.

**Comment by syntacticvexation** [comment]
Great, just upgraded now, thanks heaps. :)

**Comment by sameersbn** [comment]
ubuntu 16.04 base image appears to be having issues. I'll eventually be updating to it, but at the moment I am of the opinions that it may be a risky move.

**Comment by sameersbn** [comment]
leaving the issue open.

**Comment by frank-dspeed** [comment]
@sameersbn @syntacticvexation i will close this as nothing happend here please reopen if i am wrong
