### ISSUE TITLE
Permission denied when trying to install plugins

### ISSUE THREAD

**Issue by dj-hedgehog** [sameersbn/docker-redmine#209]
Every time I put the redmine-agile-plugin into the plugins directory and restart the container I get the following error:

Installing the EasyGantt plugin worked fine but both [Redmine Agile](https://github.com/RCRM/redmine_agile) and Redmine Dashboard lead to the error below.
What can I do about this?

```
rake aborted!
Errno::EACCES: Permission denied @ rb_sysopen - /home/redmine/redmine/db/schema.rb
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/railties/databases.rake:239:in `initialize'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/railties/databases.rake:239:in `open'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/railties/databases.rake:239:in `block (3 levels) in <top (required)>'
/home/redmine/redmine/lib/tasks/redmine.rake:132:in `block (3 levels) in <top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:schema:dump
(See full trace by running task with --trace)
```

**Comment by StefanCristian** [comment]
Hey. Solved the issue with this?
Are there any suggestions on how to install that plugin? ( Never works for me in no version of redmine )

**Comment by frank-dspeed** [comment]
it looks like a permission issue not a redmine issue check your operating system appamor and linux file permissions and so on

**Comment by StefanCristian** [comment]
@jcormier hey. I made the specific folder have the same permissions as the container user:group
Such as **1000:1000**, which apparently is supported by default at container start

i.e. I let the container start with docker-compose, I've put the redmine_agile within /src/docker/redmine/redmine/plugins/, and changed permissions to match the container's

Then, the obvious step: execute redmine-install-plugins in the container, in order for redmine to catch it and make it work successfully
This container also works if you restart it or start a new one over the old volumes, so backup is assured 👍

**Comment by jcormier** [comment]
> execute redmine-install-plugins in the container, in order for redmine to catch it and make it work successfully

The container should auto detect that a new folder was added to the plugin folder and run redmine-install-plugins.  Otherwise, your steps look correct.
