### ISSUE TITLE
Tag 3.2.3-1 and 3.3.0-1 not found 

### ISSUE THREAD

**Issue by linlinlinlin** [sameersbn/docker-redmine#210]
I am using the latest release version.
But cannot found ``Tag 3.2.3-1 not found in repository docker.io/sameersbn/redmine``
Same issue of ``Tag 3.3.0-1 not found in repository docker.io/sameersbn/redmine``

Ref: https://hub.docker.com/r/sameersbn/redmine/tags/

**Comment by linlinlinlin** [comment]
Same issue of ``Tag 3.3.0-1 not found in repository docker.io/sameersbn/redmine``

**Comment by sameersbn** [comment]
Seems like DockerHub didn't pick those tags. Have issued the builds again.
