### ISSUE TITLE
How to setup incoming mail support?

### ISSUE THREAD

**Issue by frdmn** [sameersbn/docker-redmine#213]
Hello,

I noticed this image now supports incoming mails via IMAP. I've set the proper env variables (`IMAP_ENABLED`, `IMAP_HOST`, `IMAP_PORT`, `IMAP_USER`, `IMAP_PASS`, `IMAP_SSL` and `IMAP_INTERVAL`) but the receiving doesn't work though. 

Do I need to do any additional setup steps or is there any other way to troubleshoot this?

Thanks in advance

**Comment by sameersbn** [comment]
@frdmn those are the only required parameters. can you login to the container and execute:

```bash
sudo -HEu redmine bundle exec rake redmine:email:receive_imap \
  host=$IMAP_HOST \
  port=$IMAP_PORT \
  ssl=$IMAP_SSL \
  username=$IMAP_USER \
  password=$IMAP_PASS \
  unknown_user=ignore \
  no_permission_check=0 \
  no_account_notice=true \
  RAILS_ENV=production
```

**Comment by frdmn** [comment]
@sameersbn Thanks for the reply. Worked fine as soon as I fetched the mail via your given command. 

Then I retried to reply without the manual execution of the rake task and noticed: it worked the whole time. I just didn't notice the ticket updates because apparently there's a little timezone issue and they end up in between previous updates, instead of at the very end.

Any idea how to fix this?

**Comment by sameersbn** [comment]
No idea. Can you report the issue to the upstream project and check what they have to say?
Closing the issue, please reopen if required
