### ISSUE TITLE
gem install problem 

### ISSUE THREAD

**Issue by joyhope** [sameersbn/docker-redmine#216]
I use docker-compose up to start the redmine.
### 

redmine_1     | Configuring redmine::max_concurrent_ajax_uploads...
redmine_1     | Configuring redmine::sudo_mode...
redmine_1     | Configuring redmine::autologin_cookie...
redmine_1     | Configuring redmine::backups...
redmine_1     | Configuring nginx...
redmine_1     | Configuring nginx::redmine...
redmine_1     | Installing plugins...
redmine_1     | Installing gems required by plugins...
redmine_1     | An error occurred while installing mysql2 (0.3.21), and Bundler cannot continue.
redmine_1     | Make sure that `gem install mysql2 -v '0.3.21'` succeeds before bundling.
redmine_redmine_1 exited with code 5
### 

How to solve the problem?  thanks

**Comment by movcale** [comment]
Yours redmine plugin require additional libs to be installed inside container.

I`ve solved this by creating extended image.
For example, my Dockerfile:

FROM sameersbn/redmine:3.3.0-4
MAINTAINER my@email.com
ENV DEBIAN_FRONTEND noninteractive

#for dmsf plugin + xapian
RUN apt-get update \
	&& apt-get install -y gawk zip unzip \
  libmysqlclient-dev \
  libmagickwand-dev imagemagick \
  xapian-omega libxapian-dev xpdf poppler-utils antiword unzip catdoc libwpd-tools libwps-tools gzip unrtf catdvi djview djview3 uuid uuid-dev xz-utils

Or you may directly modify container if do the same for one time in file
/srv/share/redmine/redmine/plugins/pre-install.sh

Also you need to do at least one time after adding any new plugin in pre-install.sh
bundle update

**Comment by frank-dspeed** [comment]
i close this as i don't understand the error if there is still a error please reopen
