### ISSUE TITLE
IMAP_SSL=false not working

### ISSUE THREAD

**Issue by psi-4ward** [sameersbn/docker-redmine#220]
Hi,

Redmine ignores the value of `IMAP_SSL` in `redmein:mail:receive`. Regardless of the value, if the key is set redmine uses SSL. 

So for `-e IMAP_SSL=false` we have to strip the `SSL=false` param from the cronjob.

**Comment by frank-dspeed** [comment]
https://github.com/sameersbn/docker-redmine/issues/215 maybe related

**Comment by jcormier** [comment]
Closing due to old age
