### ISSUE TITLE
as of 2016. 09. 20  latest sameersbn/redmine. cannot start redmine server

### ISSUE THREAD

**Issue by safedata** [sameersbn/docker-redmine#222]
this is linked to sameersbn/redminemysql:latest. 

docker logs redminedockername

Migrating database. Please be patient, this could take a while...
/rubygems/dependency.rb:298:in 'to_specs": Could not find 'handler' amount 8 total gems

from /usr/lib/ruby/2.1.0/rubygems/dependency.rb:309:in 'to_spec'

**Comment by frank-dspeed** [comment]
i close this please reopen if error still exists
