### ISSUE TITLE
Problem when using external memcached and several containers on one machine

### ISSUE THREAD

**Issue by carukc** [sameersbn/docker-redmine#225]
Hello,

I discovered a problem today when running multiple containers (using same image) when using the option for an external memcached server that I thought everyone should be aware of.

It seems that both containers were using the same cache so if I changed a setting on one then the change would also appear on the second container.  I've temporarilly resolved the problem by disabling memcache on these containers but think that the best long term solution would be to either run memcache in the container itself or find a way to give each container it's own memcache namespace.  I think that dalli may provide namespacing for memcache/redmine but I am not sure.

If possible a priviate memcache manespace would probibly be better and might be configured using a a new configuration variable or perhaps the database name.

Chris

**Comment by carukc** [comment]
This issue seems to suggest that you can create a seperate namespace in dalli / redmine:

https://project.altservice.com/issues/196

I will try to find some time to experiment but I do not yet know enough about how redmine works (internally) to get teh right setting.

Chris

**Comment by frank-dspeed** [comment]
I thin Option for setting namespaces on memcache is well

**Comment by frank-dspeed** [comment]
@carukc i tclose this as this is not happening any more i think feel free to reopen if you still got a issue with that
