### ISSUE TITLE
No way to config rmagick_font_path

### ISSUE THREAD

**Issue by ihipop** [sameersbn/docker-redmine#228]
For CJK users ,we have to set `rmagick_font_path` for the png export  function of GANTT to work
thers is no way to config this via env and we have to (do for example:
`apt-get install fonts-arphic-bkai00mp fonts-arphic-bsmi00lp fonts-arphic-gbsn00lp fonts-arphic-gbsn00lp` and ) set it manully in config file `/etc/docker-redmine/runtime/config/redmin
e/configuration.yml
`

**Comment by frank-dspeed** [comment]
#281 - will allow setting of ```rmagick_font_path``` via docker ENV

**Comment by frank-dspeed** [comment]
@ihipop track issue #281 for updates thanks for your feedback

**Comment by ihipop** [comment]
there is no update after these years

**Comment by ihipop** [comment]
https://github.com/sameersbn/docker-redmine/pull/331

**Comment by ihipop** [comment]
I will do this job
