### ISSUE TITLE
Configuring redmine::databasefind: `/usr/lib/postgresql/': No such file or directory

### ISSUE THREAD

**Issue by taniadaniela** [sameersbn/docker-redmine#231]
I'm having this error when trying to put my container up using docker-compose.. Any ideas?
```
postgresql_1  | LOG:  database system was shut down at 2016-11-04 14:52:52 UTC
postgresql_1  | LOG:  MultiXact member wraparound protections are now enabled
postgresql_1  | LOG:  database system is ready to accept connections
postgresql_1  | LOG:  autovacuum launcher started
redmine_1     | Initializing logdir...
redmine_1     | Initializing datadir...
redmine_1     | Symlinking dotfiles...
redmine_1     | Installing configuration templates...
redmine_1     | Configuring redmine...
redmine_1     | Configuring redmine::databasefind: `/usr/lib/postgresql/': No such file or directory
redevm_redmine_1 exited with code 1
```

**Comment by movcale** [comment]
Path should be '/var/lib/postgresql' rather than '/usr/lib/postgresql/'
See my docker-compose as example. May be it help.

> dev-postgresql:
  image: sameersbn/postgresql:9.5-3
  environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
    - USERMAP_UID=1000
    - USERMAP_GID=999
  ports:
    - "5003:5432"
  volumes:
    - /u01/docker/redmine/postgresql:/var/lib/postgresql
    - /u01/docker/redmine/postgresql-additional:/mnt/additional
  restart: always

>memcached:
  image: sameersbn/memcached:latest
  ports:
    - "11211:11211"
  restart: always
  
>dev-redmine:
  image: sameersbn/redmine:3.3.1
  links:
    - dev-postgresql:postgresql
    - memcached:memcached
  environment:
    - DEBUG=true
    - TZ=Europe/Moscow
    - REDMINE_PORT=80
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=
    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15
    - REDMINE_CONCURRENT_UPLOADS=2
    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=
    - SMTP_ENABLED=true
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=smtp.yandex.ru
    - SMTP_HOST=smtp.yandex.ru
    - SMTP_PORT=465
    - SMTP_USER=user@yandex.ru
    - SMTP_PASS=passwd
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login
    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_INTERVAL=30
    - USERMAP_UID=1000
    - USERMAP_GID=999
  ports:
    - "80:80"
  volumes:
    - /u01/docker/redmine/redmine:/home/redmine/data
  restart: always

**Comment by movcale** [comment]
Corrected yml file above.
Actually I use sameersbn/redmine:3.3.0-4 and maybe sameersbn/memcached:latest also has been changed

**Comment by frank-dspeed** [comment]
Closing this as its working at present for me you can reopen if you got still this issue
