### ISSUE TITLE
Docker Run Bump out NoMethodError in Application class while migrate db.

### ISSUE THREAD

**Issue by stanleyc1982** [sameersbn/docker-redmine#233]
Configuring redmine::max_concurrent_ajax_uploads...
stdout
02:51:49
Configuring redmine::sudo_mode...
stdout
02:51:49
Configuring redmine::autologin_cookie...
stdout
02:51:49
Configuring redmine::email_delivery...
stdout
02:51:50
Configuring redmine::backups...
stdout
02:51:50
Configuring nginx...
stdout
02:51:50
Configuring nginx::redmine...
stdout
02:51:50
Migrating database. Please be patient, this could take a while...
stdout
02:51:54
rake aborted!
stdout
02:51:54
NoMethodError: private method `gem' called for #&lt;Rails::Application::Configuration:0x00000003bab730&gt;
stdout
02:51:54
/home/redmine/redmine/config/application.rb:80:in `instance_eval'
stdout
02:51:54
(eval):1:in `&lt;class:Application&gt;'
stdout
02:51:54
/home/redmine/redmine/config/application.rb:80:in `instance_eval'
stdout
02:51:54
/home/redmine/redmine/config/application.rb:80:in `&lt;class:Application&gt;'
stdout
02:51:54
/home/redmine/redmine/config/application.rb:8:in `&lt;module:RedmineApp&gt;'
stdout
02:51:54
/home/redmine/redmine/config/application.rb:7:in `&lt;top (required)&gt;'
stdout
02:51:54
/home/redmine/redmine/Rakefile:5:in `require'
stdout
02:51:54
/home/redmine/redmine/Rakefile:5:in `&lt;top (required)&gt;'
stdout
02:51:54
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/exe/rake:27:in `&lt;top (required)&gt;'
stdout
02:51:54
(See full trace by running task with --trace)

**Comment by frank-dspeed** [comment]
@stanleyc1982 i close this as this is currently not happening any more i think if it still is please reopen
