### ISSUE TITLE
redmine fails to start after putting redmine_tweaks into plugins directory.

### ISSUE THREAD

**Issue by liangsuilong** [sameersbn/docker-redmine#237]
I am using Redmine 3.2.4. Here is log.

Initializing logdir...
Initializing datadir...
Symlinking dotfiles...
Installing configuration templates...
Configuring redmine...
Configuring redmine::database
Configuring redmine::unicorn...
Configuring redmine::secret_token...
Generating a session token...
Note:
  All old sessions will become invalid.
  Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
  **SHOULD** be defined if you have a load-balancing Redmine cluster.
Configuring redmine::max_concurrent_ajax_uploads...
Configuring redmine::sudo_mode...
Configuring redmine::autologin_cookie...
Configuring redmine::email_delivery...
Configuring redmine::incoming_email...
Configuring redmine::backups...
Configuring nginx...
Configuring nginx::redmine...
Installing plugins...
Installing gems required by plugins...
Migrating plugins. Please be patient, this could take a while...
rake aborted!
NoMethodError: undefined method `=~' for #<Pathname:0x00000005950b00>
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/deface-1.0.2/lib/deface/railtie.rb:50:in `block (3 levels) in <class:Railtie>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/deface-1.0.2/lib/deface/railtie.rb:50:in `reject!'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/deface-1.0.2/lib/deface/railtie.rb:50:in `block (2 levels) in <class:Railtie>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/deface-1.0.2/lib/deface/railtie.rb:48:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/deface-1.0.2/lib/deface/railtie.rb:48:in `block in <class:Railtie>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine/plugins/a_common_libs/lib/tasks/saas.rake:1:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/home/redmine/redmine/lib/tasks/redmine.rake:186:in `block in <top (required)>'
/home/redmine/redmine/lib/tasks/redmine.rake:186:in `each'
/home/redmine/redmine/lib/tasks/redmine.rake:186:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `run_tasks_blocks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:452:in `run_tasks_blocks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:453:in `load_tasks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
/home/redmine/redmine/Rakefile:7:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by movcale** [comment]
Looks like it is plugins conflict
[See this](https://github.com/AlphaNodes/redmine_tweaks/issues/32)

**Comment by frank-dspeed** [comment]
i close this please feel free to reopen if error still exists
