### ISSUE TITLE
file upload request entity error

### ISSUE THREAD

**Issue by ankurgla22** [sameersbn/docker-redmine#239]
I want to upload a file of 100 MB on my redmine server.
But it is giving "Request Entity error".
I have set max file size to 500 MB in Redmine Setting.

![capture](https://cloud.githubusercontent.com/assets/10428843/20737072/e1937542-b6ed-11e6-81d0-5065260d33d1.JPG)

Any help?

**Comment by jcormier** [comment]
In assets/runtime/config/nginx/redmine
```
## Increase this if you want to upload large attachments
client_max_body_size {{NGINX_MAX_UPLOAD_SIZE}};
```

Searching source for NGINX_MAX_UPLOAD_SIZE
```
README.md
593:- **NGINX_MAX_UPLOAD_SIZE**: Maximum acceptable upload size. Defaults to `20m`.

assets/runtime/env-defaults
123:NGINX_MAX_UPLOAD_SIZE=${NGINX_MAX_UPLOAD_SIZE:-20m}

```

**Comment by ankurgla22** [comment]
Thanks alot.

**Comment by hmkim** [comment]
I modify the size in assets/runtime/env-defaults.

but dose not work.

**Comment by hmkim** [comment]
![Screen Shot 2021-11-09 at 9 23 21 AM](https://user-images.githubusercontent.com/4966343/140839115-36517830-b6ff-4ac7-aeee-69b137f10ee5.png)

I solved this issue by docker-compose.yml modification
