### ISSUE TITLE
Using Multiple SSL Certificates for Multiple Domains with One IP Address

### ISSUE THREAD

**Issue by Mouatez** [sameersbn/docker-redmine#243]
Hello Sameersbn, 

First, Thank you for the great  Redmine Docker image.

My problem is:

How can I use multiple domains with their SSL Certificates in one Redmine using your Redmine Docker image? 

Thank you,

**Comment by Mouatez** [comment]
problem solved, 

I make some change in /etc/nginx/sites-enabled/redmine:

1- I add new server entry in the file.
2- add to each the one domain: server_name exmaple.com 
3- remove: error_page 500 /500.html;
4- update certificate path for each domain/server entry.
5- Finally, I make some directories as Docker volume, so, I will not lose the data.
6- disable auto copy of Nginx configuration, that is in the entrypoint.

Hope this helps people having the same issue.

**Comment by frank-dspeed** [comment]
@Mouatez i close this as it is solved if you need anything you can reopen it thanks for reporting
