### ISSUE TITLE
rm: cannot remove XXX Directory not empty

### ISSUE THREAD

**Issue by llach** [sameersbn/docker-redmine#251]
Hi there,
everytime i try to run the redmine container it exits right away. 
docker logs revealed those errors:

`rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/bin': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/cache': Directory not empty`

well, not only those two, but roughly one hundred more, all regarding to the ruby directory with the same error message.

i tried reinstalling docker, once as showed on the docker install page (ver 1.12) and another time from the official yum repo (ver 1.10.3), but that didn't help. 

Anybody experienced errors like these so far and knows how to deal with them?

P.S. im running centos 7.1 with kernel 3.10.0-514.6.1.el7.x86_64

**Comment by jcormier** [comment]
What version of the redmine docker are you running?  How are you launching the docker?

Have you tried removing the old docker containers?  If using docker-compose this would be `docker-compose down`.  If straight docker, i'm not sure but I think `docker ps -a` to list the containers and `docker rm` to remove them.

**Comment by qinzheng** [comment]
same problem   how to deal with them?

**Comment by jcormier** [comment]
Can you answer any of the questions I asked before?

**Comment by llach** [comment]
Sorry for not answesing, but my "fix" won't be satisfying.

I reinstalled CentOS, after that it worked.

**Comment by aymen-chetoui** [comment]
Having the same issue here. 
Any fix to this yet?

**Comment by jcormier** [comment]
Guys need more information to identify whats going wrong.

**Comment by frank-dspeed** [comment]
@jcormier possible related to ownership problems some how 
@aymen-chetoui @llach please do ls -ahl to find the user it belongs to are you executing the command as the right user?

**Comment by jcormier** [comment]
Closed due to old age
