### ISSUE TITLE
Create issues from email.

### ISSUE THREAD

**Issue by Filipp1232** [sameersbn/docker-redmine#252]
How can i change option for unknown-user?
In documentation is written that i need to change this option  unknown_user=[ignore|accept|create] but 
i cant find it.

**Comment by jcormier** [comment]
Note that you can search this repository to find if this option is available.

https://github.com/sameersbn/docker-redmine/search?utf8=%E2%9C%93&q=+unknown_user

It points out this line
```
INCOMING_EMAIL_OPTIONS="${INCOMING_EMAIL_UNKNOWN_USER:+unknown_user=${INCOMING_EMAIL_UNKNOWN_USER}} \
```

so the environment variable you want to set is: "INCOMING_EMAIL_UNKNOWN_USER"

**Comment by Filipp1232** [comment]
Thank you

**Comment by jcormier** [comment]
You might want to make note of my newly created issue as well #256
