### ISSUE TITLE
Overwriting postgresql existing image

### ISSUE THREAD

**Issue by workmonitored** [sameersbn/docker-redmine#254]
When I do a docker-compose on windows 10, the docker compose for postgresql overwrites the docker-compose created by the sameersbn/gitlab. Is there  a way to stop the service from overwriting the postgresql from the other docker-compose Or run two different postgresql docker images?

**Comment by jcormier** [comment]
docker-compose uses the current folder name as its namespace.  So each docker compose yml would need to be in a different directory name.

There should be a way to manually specify a namespace but I don't recall.

**Comment by workmonitored** [comment]
That works for me. Thanks. I will look up namespace but not crucial to me.
