### ISSUE TITLE
 ERROR:  tuple concurrently updated

### ISSUE THREAD

**Issue by anoduck** [sameersbn/docker-redmine#255]
Installing using docker compose. During migration of database, recieve error then postgres image exits early. Been trying to get the redmine image running for a while now. Even was able to use bitnami-redmine for a while, now that too has stopped. Sad day...

**Comment by jcormier** [comment]
Could use some more details.  Including what the error message was.

**Comment by anoduck** [comment]
Sure thing, 
I am running it now and post the output when it completes. I do remember the last line read something like:
```shell
ERROR: tuple concurrently updated
```

**Comment by anoduck** [comment]
Here is my current output, when I run the "docker-compose up" command. It is not very informative.

```sh
redmine-docker ➜ docker-compose up
Starting redminedocker_postgresql_1
Starting redminedocker_redmine_1
Attaching to redminedocker_postgresql_1, redminedocker_redmine_1
postgresql_1  | Initializing datadir...
redmine_1     | Initializing logdir...
redmine_1     | Initializing datadir...
redmine_1     | Symlinking dotfiles...
redmine_1     | Installing configuration templates...
redmine_1     | Configuring redmine...
postgresql_1  | Initializing certdir...
postgresql_1  | Initializing logdir...
postgresql_1  | Initializing rundir...
postgresql_1  | Setting resolv.conf ACLs...
postgresql_1  | Creating database user: redmine
postgresql_1  | Creating database: redmine_production...
postgresql_1  | ‣ Granting access to redmine user...
postgresql_1  | ERROR:  tuple concurrently updated
redminedocker_postgresql_1 exited with code 1
```

I am going to attempt to run startup of the containers manually, while passing `tail -f /dev/null` to the redmine container, and look at the logs to see if I can find more information. But for now, that is about what I got.

**Comment by jcormier** [comment]
I'm not that familiar with postgresql.  But that error message does return quite a few results in google.

**Comment by anoduck** [comment]
I just really appreciate the help.

I tossed the PostgreSQL container to the wind, and chose to run redmine off of my local mariadb installation. That would eliminate the issue with the PostgreSQL container and tuple. 

So far redmine runs, but I am unable to connect to the installation with my browser. I would like to run it with docker-compose, but so far that appears to hang. My `docker-compose.yml` is posted here on gist:
[docker-compose.yml](https://gist.github.com/anoduck/f139d1c96e4f7fe616048df94bf4d7e2)

Regardless... I am able to get the container running and connected with my mysql installation using the following command:
```sh
sudo docker run --name=redmine -it --rm \   
  --env='DB_ADAPTER=mysql2' \
  --env='DB_HOST=192.168.1.1' --env='DB_NAME=redmine_production' \
  --env='DB_USER=redmine' --env='DB_PASS=password' \
  --volume=/srv/docker/redmine/redmine:/home/redmine/data \
  sameersbn/redmine:latest
```

This boots up redmine and configures the database after a few minutes time. But so far, once booted my browser cannot find the installation. Currently I am rebooting the image and attaching a shell locally to see if I can find more information or configure the image to where I can access it. 

Thanks again.

**Comment by jcormier** [comment]
Hmm could you post the full start log for both the docker-compose start  and the manual docker run one?

**Comment by anoduck** [comment]
__For docker_run_one:__

Redmine docker_run_one currently stalls out when configuring the database. It may not be able to reach the external localized mysql db, just like I was unable to access it via the browser. Currently there are not logs inside of the image itself, and post simply reads:
```sh
Initializing logdir...
Initializing datadir...
Symlinking dotfiles...
Installing configuration templates...
Configuring redmine...
Configuring redmine::database........................................
```
It has been like that for over an hour. But, at least it gets that far.

----

__For docker_compose_custom:__

I get even less post than docker_run_one. It stalls out when configuring redmine:
```sh
docker-compose up
Starting redminedockercustom_redmine_1
Attaching to redminedockercustom_redmine_1
redmine_1  | Initializing logdir...
redmine_1  | Initializing datadir...
redmine_1  | Symlinking dotfiles...
redmine_1  | Installing configuration templates...
redmine_1  | Configuring redmine...
```

I am not sure if removing both the container and image, and cloning a fresh copy of the image to my local install would make a difference.

I am starting to think that this is a docker network issue. Somehow docker is not able to contact it's external resources, causing it to stall out, and I am unable to connect to it because it cannot connect to the DB to finish setup.

**Comment by anoduck** [comment]
Interesting...
I discovered that when running the script manaully, i.e. docker_run_1, that the ports where docker was broadcasting the redmine server were still set at the default 80, which conflict with my webserver naturally. I forgot to add the `--env='REDMINE_PORT=10083' \` flag to the command.

----

But of coarse this made no difference at all when I inserted the flag, and the container still hangs on configurating the database. 

I was able to perform some network recon and attach the container. I was able to ping most hosts, it is just on a network that is being 'nat' translated. I might need to configure a means to bridge docker's network interface with the local one. This would force docker to be on the same network and subnet that it's resources are locate on.

**Comment by anoduck** [comment]
Well, ... I will be the son of a striped monkey. It finally started running...finally!

__This is what I did:__
1. I went with the mysql docker image instead of my local installation and instead of the postgresql database. 
2. I pulled fresh images from the `quay.io` docker repository rather than docker hub.
3. I removed the persistence directory located at `/srv/docker/redmine/mysql` and `/srv/docker/redmine/redmine`.
4. Ran the image with the prescribed manual commands.

And boom goes the dynamite.

**Comment by anoduck** [comment]
...that is... it hangs on installing mysql2 gem.

**Comment by anoduck** [comment]
Remove the `-rm` flag from his `docker run redmine` command. If not, your installation won't be permanent.

**Comment by jcormier** [comment]
> Remove the -rm flag from his docker run redmine command. If not, your installation won't be permanent.
Thats kinda the whole point of docker though.  Is that the docker containers aren't permanent.  The files you want to keep like your mysql db and redmine files/plugins are all stored in volumes or mapped to your local drive.

Any custom changes to the container itself should be contained in a [Dockerfile](https://github.com/sameersbn/docker-redmine/blob/master/Dockerfile).  However the way this docker project is setup, hopefully all customization can be done via the provided ENV variables.

**Comment by jcormier** [comment]
I could be wrong as I'm also learning docker but that is my understanding.

**Comment by anoduck** [comment]
Hmmm... never thought of it like that before....interesting... I mean, I can see so many different ways that developers can find and apply docker to their development infrastructure. Regardless, the plugins `dir` is not mapped to a persistent volume on the host system. Or, at least I am fairly certain it isn't, or that was two hours of my life I want back...And I am reasonably sure the themes directory is not either. The user data stored on the mysql db is, for sure.
Also, Sameer does not include `-rm` flag in the example in the [quick start.](https://github.com/sameersbn/docker-redmine#quick-start) He uses it in some of the examples, and some of the examples he does not. Honestly, I always thought it was a type-o. Secondly, when it comes time to update your Redmine image, things might get pretty messy when your old plugins don't jive with your new redmine image. This would also mean, that if you wanted to patch a security flaw or make a configuration change, you would have to commit the change to a new image everytime.

**Comment by anoduck** [comment]
The dockerfile builds your docker image. But, why would you go through the trouble of building, configuring, and compiling an entire new image everytime you make a change to a configuration file? When you can remove a flag from a command? Sounds a little expensive.

**Comment by anoduck** [comment]
Concerned I came off to strong.

**Comment by anoduck** [comment]
It is my understanding that docker-compose is where those configuration changes should be made, instead of the dockerfile.

**Comment by jcormier** [comment]
> Regardless, the plugins dir is not mapped to a persistent volume on the host system. Or, at least I am fairly certain it isn't, or that was two hours of my life I want back...And I am reasonably sure the themes directory is not either.

I'm not sure I follow. The themes and plugins are copied from the data volume when you start the container.   This is sorta described here: https://github.com/sameersbn/docker-redmine#installing-plugins
```
/export/docker/redmine-data$ ls plugins/
clipboard_image_paste    redmine_favourite_projects     redmine_tags
google_analytics_plugin  redmine_jstoolbar_ext          redmine_wiki_extensions
open_flash_chart         redmine_jstoolbar_ext_buttons  redmine_wiki_notes
post-install.sh          redmine_jstoolbar_ext_images   redmine_xlsx_format_issue_exporter
redmine_banner           redmine_project_alias_2        wiki_issue_fields
redmine_charts2          redmine_release_notes
redmine_checklists       redmine_silencer
/export/docker/redmine-data$ ls themes/
alternate  classic  criticallink  README

```

**Comment by jcormier** [comment]
> The dockerfile builds your docker image. But, why would you go through the trouble of building, configuring, and compiling an entire new image everytime you make a change to a configuration file? When you can remove a flag from a command? Sounds a little expensive.

From my perspective at least, I want to be able to track and reproduce whatever changes I make to my running service.  So if I make manual changes to the docker image itself, I wouldn't be able to reproduce those easily. But if I build them into a Dockerfile then the changes are documented and easily reproducible.

For this project so far because of all the environment variable settings and some of sameersbn setup scripts, I haven't had to modify the docker image.  Actually the only change to the image I've made so far was to the nginx config file. And so instead of creating a Dockerfile, I simply mounted the changed config file in place. And changing the favicon.

```
    volumes:
    - ./../redmine-data:/home/redmine/data
    - ./../redmine-logs:/var/log/redmine
    - ./config/nginx/redmine_3.3.1:/etc/docker-redmine/runtime/config/nginx/redmine:ro
    - ./config/favicon-internal.ico:/home/redmine/redmine/public/favicon.ico
```

> It is my understanding that docker-compose is where those configuration changes should be made, instead of the dockerfile.

Yes the way sameersbn has set this project up, hopefully all configuration to the server can be done via environment variables in the docker-compose file. And thus ideally remove the need to make any modification to the image itself.

> Secondly, when it comes time to update your Redmine image, things might get pretty messy when your old plugins don't jive with your new redmine image. This would also mean, that if you wanted to patch a security flaw or make a configuration change, you would have to commit the change to a new image everytime.

Sadly I'm learning with redmine, plugins are almost always a messy afair.

If you capture applying the security patches in your Dockerfile, then ideally you'd just need to update its `From` line any time you want to use a newer image.  At least thats what sameersbn keeps doing.
https://github.com/sameersbn/docker-redmine/commits/master/Dockerfile

**Comment by anoduck** [comment]
Glad you responded. I can come off a little strong sometimes.

**Comment by anoduck** [comment]
Wow wee. Thanks for the info and the response.
