### ISSUE TITLE
Setting TZ variable in docker-compose causes timestamp problems for incoming email

### ISSUE THREAD

**Issue by jcormier** [sameersbn/docker-redmine#256]
Posted this to redmine forums with no response.  Finally figured out what was going on.

http://www.redmine.org/boards/2/topics/51914?r=52188

> When I run the `redmine:email:receive_imap` rake from the command line the issue journals get created with the correct timestamp. However if I let cron run the rake the timestamps were 5 hours ahead of time.
> 
> I added the following to the receive_imap task to print the ENV variables and compared the two instances.
> 
>       require 'pp'
>       pp ENV
> The cronjob did not have the TZ environment variable set so its date was coming out as 
> 
> 2017-02-19 22:37:09 +0000
> 
> where as the command line version date was 
> 2017-02-19 17:37:51 -0500
> And the server was started with the TZ variable set as well.
> 
> Ensuring that the server was started without the TZ variable set, allowed the cronjob to set the correct timestamp. Of course now all our redmine posts are stated as 5 hours earlier than they were before but hopefully no one notices.

So it seems like the TZ variable should not be set in the docker-compose file.  Or if its set then the redmine cron file should be updated to include the TZ variable as well.

**Comment by Filipp1232** [comment]
Can u tell me how to configure this cron ? And I don't understand where I must write this command redmine:email:receive_imap ? Inside docker image?

Thank you)

**Comment by jcormier** [comment]
I'm not sure what your asking for.  If you set `IMAP_ENABLED=true` in the docker environment, then the cron job will be automatically created.  You don't have to run it yourself.

**Comment by Filipp1232** [comment]
I am asking for that ) thanks. And as I understood  this cron will be automatically create issues from email ?

**Comment by jcormier** [comment]
Well this cron will run the redmine:email:receive_imap rake.  You'll have to read this page and figure out how to configure it to create new issues.  I've only used it to reply to issues.

My guess is you'll have to set the INCOMING_EMAIL_PROJECT atleast, possibly some others.

http://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails

**Comment by jcormier** [comment]
Closing as @sameersbn going to handle this in pr #257
