### ISSUE TITLE
hi sameersbn 

### ISSUE THREAD

**Issue by Jason2002** [sameersbn/docker-redmine#260]
hi sammer , 

there are some errors bellow when i run your image, can u help me too resolve it? thanks .

Initializing logdir...
Initializing datadir...
Symlinking dotfiles...
Installing configuration templates...
Configuring redmine...
Configuring redmine::database
Configuring redmine::unicorn...
Configuring redmine::secret_token...
Generating a session token...
Note:
  All old sessions will become invalid.
  Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
  **SHOULD** be defined if you have a load-balancing Redmine cluster.
Configuring redmine::max_concurrent_ajax_uploads...
Configuring redmine::sudo_mode...
Configuring redmine::autologin_cookie...
Configuring redmine::email_delivery...
Configuring redmine::backups...
Configuring nginx...
Configuring nginx::redmine...
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/bin': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/build_info': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/cache': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/json-1.8.6/json/ext': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/kgio-2.11.0': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/mysql2-0.3.21/mysql2': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.7.0.1/nokogiri': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/pg-0.18.4': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/raindrops-0.17.0': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/redcarpet-3.3.4': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/rmagick-2.16.0': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/unicorn-5.2.0': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.2.7.1/lib/action_mailer': Directory not empty

.......

**Comment by jcormier** [comment]
What steps did you do to create these errors?  I've never run into this.  What version of the docker image are you using?

My guess is that you need to delete the docker container

**Comment by Jason2002** [comment]
thanks for your reply
i user this version

Server Version: 17.03.1-ce

**Comment by jcormier** [comment]
I was looking for which version of the redmine   container.

**Comment by jcormier** [comment]
Closing, please reopen if this is still an issue.

**Comment by nhson02** [comment]
Hello,
I have the same problem with latest redmine containter (3.4.2). I got error just in the step 2, start redmine after loading postgres. The message is the same. Could you help me to solve this
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/tzinfo-1.2.3/test/zoneinfo/America/Argentina': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/tzinfo-1.2.3/test/zoneinfo/Australia': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/tzinfo-1.2.3/test/zoneinfo/Etc': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/tzinfo-1.2.3/test/zoneinfo/Europe': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/tzinfo-1.2.3/test/zoneinfo/posix/Europe': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/tzinfo-1.2.3/test/zoneinfo/right/Europe': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/Documentation': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/archive': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/bin': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/examples': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/ext/unicorn_http': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/lib/unicorn/app/old_rails': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/man/man1': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/t/bin': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/test/benchmark': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/test/exec': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/test/unit': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/specifications': Directory not empty

**Comment by sameersbn** [comment]
@Jason2002 Are you using Docker on RHEL/CentOS 7 with OverlayFS? If yes, RHEL treats OverlayFS as a preview filesystem. The following document https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html lists the problems and possible workarounds for using OverlayFS with Docker on RHEL 7.2.

We hope you find the information contained in this referenced document useful.

**Comment by lingfengchencn** [comment]
@sameersbn 
It seems YES.

centos 7 

```
Filesystem     1K-blocks     Used Available Use% Mounted on
overlay         62898180 16052852  46845328  26% /var/lib/docker/overlay/.../merged
overlay         62898180 16052852  46845328  26% /var/lib/docker/overlay/...
```

**Comment by lingfengchencn** [comment]
Bad news。I buy a new server from another operator with the same environment。
centos 7， docker，docker-compose， docker-compose.yml and use overlay FS too.

but it works fine... :(

**Comment by frank-dspeed** [comment]
@lingfengchencn we don't see that as bad news that simply says its working fine we are glad that it does we expect it to run fine :+1:

**Comment by lingfengchencn** [comment]
But it can't work fine on my first server. 
the second one is just for test.

**Comment by frank-dspeed** [comment]
@lingfengchencn sorry to tell you that but you should ask simply your server admin about that this software has nothing to do with that

**Comment by lingfengchencn** [comment]
I'll try.

**Comment by jcormier** [comment]
If the overlay driver is a problem, perhaps you can switch it to one of the other storage drivers like aufs?
https://docs.docker.com/engine/userguide/storagedriver/aufs-driver/

**Comment by danielmihai** [comment]
I had the same issue on Oracle Enterprise Linux 7 with overlay2. Changing to devicemapper, which is the official docker recommendation for centos, rhel etc systems solved it. 



> - devicemapper storage driver is the only supported storage driver for Docker EE and Commercially Supported Docker Engine (CS-Engine) on RHEL, CentOS, and Oracle Linux. See the Product compatibility matrix.
> - devicemapper is also supported on Docker CE running on CentOS, Fedora, Ubuntu, or Debian.

from https://docs.docker.com/storage/storagedriver/device-mapper-driver/, Prerequisites section .

HTH, 
Daniel.
