### ISSUE TITLE
PlantUML Plugin

### ISSUE THREAD

**Issue by raisin** [sameersbn/docker-redmine#261]
My goal is to get the PlantUML plugin working with docker-redmine.
PlantUML plugin: https://github.com/dkd/plantuml

In order to do this, I had to modify the docker-redmine image. Here is the modified image:
https://github.com/raisin/docker-redmine

After building this image, I did the following:
1. Install the PlantUML plugin in the plugins directory.
2. Specify the PlantUML binary in the plugin configuration. The binary is located at /usr/bin/plantuml.
3. Add the following PlantUML snippet to a newly created project.
{{plantuml(png)
  Bob -> Alice : hello
}}
4. When Redmine tries to generate the associated png for this snippet, we get a 500 error when the PlantUML plugin tries to write to the files directory. This is line #7 of the file:
plugins/plantuml/app/controllers/plantuml_controller.rb

Any ideas what is causing this problem?

Also, I had quite a bit of difficulty trying to send all the log output to the docker shell (The shell where I ran docker-compose up). Adding the following lines did not work.
    tty: true
    stdin_open: true

I also tried adding the following to config/application.rb:
config.logger = Logger.new(STDOUT)
config.log_level = :debug
(I removed the existing config.log_level command)

**Comment by raisin** [comment]
I understand the problem with PlantUML now. The docker image created by my Dockerfile has the /usr/bin/plantuml binary owned by root. However, the redmine application is run by the redmine user. Once I changed the ownership of the /usr/bin/plantuml file to be owned by redmine:redmine, the display of plantuml diagrams worked like a charm.

**Comment by jcormier** [comment]
Glad you figured it out.  Pretty cool plugin, I might check it out.

I'm not certain but I think in this case, since PlantUML isn't likely to be merged into the base docker-redmine project.  It likely would have been better to create your own Dockerfile and "inherit" from this one.

Something like the following. I just copy pasted your changes, didn't try anything.

Dockerfile:
```
FROM sameersbn/redmine:3.3.2-1
MAINTAINER raisin

RUN cd /opt \
+&& wget http://javadl.oracle.com/webapps/download/AutoDL\?BundleId\=218823_e9e7ea248e2c4826b92b3f075a80e441 -O jre-8u121-linux-x64.tar.gz \
 && tar zxvf jre-8u121-linux-x64.tar.gz \
 && ln -s /opt/jre1.8.0_121/bin/java /usr/bin/java \
 && ln -s /opt/jre1.8.0_121/bin/javaws /usr/bin/javaws \
 && wget http://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar \
 && echo '#!/bin/bash' >> /usr/bin/plantuml \
 && echo '/usr/bin/java -Djava.io.tmpdir=/var/tmp -Djava.awt.headless=true -jar /opt/plantuml.jar ${@}' >> /usr/bin/plantuml \
 && chmod u+x /usr/bin/plantuml 

RUN chown ${REDMINE_USER}:${REDMINE_USER} /usr/bin/plantuml
```

Or used the pre-install.sh and post-install.sh scripts to run the above steps. https://github.com/sameersbn/docker-redmine#installing-plugins

**Comment by jcormier** [comment]
Closing as this was answered.
