### ISSUE TITLE
can NOT use LDAP server

### ISSUE THREAD

**Issue by shenngw1127** [sameersbn/docker-redmine#263]
version: 3.1.7-3
version: 3.2.5-1
both failed!

1 start container with sameersbn/postgresql 9.6.2
2 login as admin
3 create ldap auth mode, then report connect ok.
4 new user from ldap auth mode, but can NOT get info from LDAP server.
5 login as the new user, can NOT login.

use official redmine docker 3.1.7 instead. it is all right, no error.

**Comment by frank-dspeed** [comment]
@shenngw1127 i close this issue as updating the image solved the problem if you think thats wrong feel free to reopen and comment thanks for reporting
