### ISSUE TITLE
Add: Let’s Encrypt support

### ISSUE THREAD

**Issue by Glideh** [sameersbn/docker-redmine#265]
It would be great to have a fully automated support of [Let’s Encrypt](https://letsencrypt.org/).
That would ease HTTPS management a little bit more.

**Comment by jcormier** [comment]
Checkout https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion

If someone could figure out how to get it all connected in a compose file and write something up.

**Comment by Maescool** [comment]
Usually people use the let's encrypt on the edge nginx instances, which usually proxy through the request.
So in my opinion this is not needed in this project.

**Comment by Glideh** [comment]
I quite agree with that. Maybe it could simply be a small how to included into the documentation.

**Comment by frank-dspeed** [comment]
@Maescool thats right but this should also run indipendent as we bundle nginx.

**Comment by jcormier** [comment]
@frank-dspeed I'm with @Glideh.  If we can find a way to do this using a separate, preferably existing, container and just provide an example.  I think that would be best but I'm not sure of the complexity of the different options.

**Comment by frank-dspeed** [comment]
@Glideh @jcormier this is related to a lot of other issues will keep you informed in this issue about that simply give me some time :)

**Comment by glego** [comment]
It's actually pretty simple using docker-gen and docker companion example: https://gitlab.intra.glego.be/docker/redmine-nginx-letsencrypt

**Comment by frank-dspeed** [comment]
@glego i don't like the jswilder image.

**Comment by phuicy** [comment]
How do I use docker-gen and docker companion example: https://github.com/glego/redmine-nginx-letsencrypt/ as a template for the sameersbn/docker-redmine image?

**Comment by jcormier** [comment]
Closed due to old age

**Comment by hwiorn** [comment]
For Redmine and LetsEncrypt(Certbot) only without external nginx: https://github.com/sameersbn/docker-redmine/issues/197#issuecomment-1846622553
