### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by sabeen-chocolatecoded** [sameersbn/docker-redmine#266]
ERROR: relation "settings" does not exist at character 323
postgresql_1 | STATEMENT: SELECT a.attname, format_type(a.atttypid, a.atttypmod),
postgresql_1 | pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
postgresql_1 | FROM pg_attribute a LEFT JOIN pg_attrdef d
postgresql_1 | ON a.attrelid = d.adrelid AND a.attnum = d.adnum
postgresql_1 | WHERE a.attrelid = '"settings"'::regclass
postgresql_1 | AND a.attnum > 0 AND NOT a.attisdropped
postgresql_1 | ORDER BY a.attnum

I am using the version 3.3.2

**Comment by jcormier** [comment]
Is this still a problem?

**Comment by bor8** [comment]
Yes, this error occurs if there are no tables in the database.

This can be checked as follows.

```
# Look for postgres container id:
docker ps
# Connect to postgres with your container id:
docker exec -it df045c4d52ed bash
su - postgres
psql
\l+
\c redmine_production
\dt
# Scroll and see settings
```

To restart from the beginning, I have executed the following commands. Attention: Everything will be deleted! The docker containers, images and volumes are deleted!

```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
rm -r /srv/docker/redmine/
```

Then

```
docker-compose up
```

**Comment by jcormier** [comment]
LGTM
