### ISSUE TITLE
plugins easy_gantt An error occurred on the page you were trying to access.

### ISSUE THREAD

**Issue by prostoVladislav** [sameersbn/docker-redmine#267]
please help
http://i.imgur.com/e9Dd5rq.png

postgresql_1  | ERROR:  relation "easy_settings" does not exist at character 323
postgresql_1  | STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
postgresql_1  | 	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
postgresql_1  | 	                FROM pg_attribute a LEFT JOIN pg_attrdef d
postgresql_1  | 	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
postgresql_1  | 	               WHERE a.attrelid = '"easy_settings"'::regclass
postgresql_1  | 	                 AND a.attnum > 0 AND NOT a.attisdropped
postgresql_1  | 	               ORDER BY a.attnum

**Comment by jcormier** [comment]
how can i help?

**Comment by prostoVladislav** [comment]
This is probably the plug-in's problem. Yes?

**Comment by jcormier** [comment]
Its possible.  Don't have enough information.  Which redmine version are you running? Do they say that the plugin supports this version of redmine?  The redmine docker should run a plugin migrate when you first added the plugin, did you see this happen?

**Comment by prostoVladislav** [comment]
redmine version  3.3.2-1
plugin http://www.redmine.org/plugins/easy-gantt download last version from official repository 1.7. 
yes, migration is work.

I will install the old version of Redmain and try with it

question. How can I access the ruby? want to run
  $ bundle install
  (or bundle update)
  $ bundle exec rake db:migrate RAILS_ENV=production
  $ bundle exec rake redmine:plugins:migrate RAILS_ENV=production

**Comment by jcormier** [comment]
These commands automatically get run when the container is started and there are new plugins in the plugins folder.

See the following function which is called from app:start) in entrypoint.sh:
https://github.com/sameersbn/docker-redmine/blob/18231b656e24c8995ce3d9ebef1992d3cb1ebedf/assets/runtime/functions#L917

**Comment by jcormier** [comment]
Note you can force a reinstall by deleting the file ${REDMINE_DATA_DIR}/tmp/plugins.sha1

**Comment by jcormier** [comment]
Closing issue. Please reopen if this is still a problem.

**Comment by alexbevi** [comment]
@prostoVladislav I'm having the exact same problem. Did you ever get this resolved?

**Comment by prostoVladislav** [comment]
@alexbevi nope. I tried different versions. but all the same

**Comment by jcormier** [comment]
Was able to install the easy_gantt plugin using the 3.4.2 image and the default docker-compose.yml file.

```
 $ sudo rm -rf /srv/docker/redmine/
 $ docker-compose rm
Going to remove dockerredmine_redmine_1, dockerredmine_postgresql_1
Are you sure? [yN] y
Removing dockerredmine_redmine_1 ... done
Removing dockerredmine_postgresql_1 ... done
 $ docker pull sameersbn/redmine:3.4.2
3.4.2: Pulling from sameersbn/redmine
Digest: sha256:be1233d7f48af8f13a72e897f5492414107402c948fe47f533820ca02b599b17
Status: Image is up to date for sameersbn/redmine:3.4.2
 $ docker-compose up
...
redmine_1     | 2017-09-26 20:09:38,987 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1     | 2017-09-26 20:09:38,987 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1     | 2017-09-26 20:09:38,987 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
^CGracefully stopping... (press Ctrl+C again to force)
Stopping dockerredmine_redmine_1 ... done
Stopping dockerredmine_postgresql_1 ... done
 $ sudo cp -ar plugins/easy_gantt/ /srv/docker/redmine/redmine/plugins/
 $ ll /srv/docker/redmine/redmine/plugins/
total 0
drwxr-xr-x 1 jcormier-local jcormier-local  20 Sep 26 10:40 ./
drwxr-xr-x 1 jcormier-local jcormier-local  72 Sep 26 10:33 ../
drwxr-xr-x 1 jcormier-local jcormier-local 134 Sep 26 09:42 easy_gantt/
 $ docker-compose up
Starting dockerredmine_postgresql_1
Starting dockerredmine_redmine_1
Attaching to dockerredmine_postgresql_1, dockerredmine_redmine_1
postgresql_1  | Initializing datadir...
redmine_1     | Initializing logdir...
postgresql_1  | Initializing certdir...
postgresql_1  | Initializing logdir...
postgresql_1  | Initializing rundir...
postgresql_1  | Setting resolv.conf ACLs...
redmine_1     | Initializing datadir...
redmine_1     | Symlinking dotfiles...
redmine_1     | Installing configuration templates...
redmine_1     | Configuring redmine...
postgresql_1  | Creating database user: redmine
postgresql_1  | Creating database: redmine_production...
postgresql_1  | ‣ Granting access to redmine user...
postgresql_1  | Starting PostgreSQL 9.6...
postgresql_1  | LOG:  database system was shut down at 2017-09-26 14:40:18 UTC
postgresql_1  | LOG:  MultiXact member wraparound protections are now enabled
postgresql_1  | LOG:  autovacuum launcher started
postgresql_1  | LOG:  database system is ready to accept connections
redmine_1     | Configuring redmine::database..
redmine_1     | Configuring redmine::unicorn...
redmine_1     | Configuring redmine::secret_token...
redmine_1     | Generating a session token...
redmine_1     | Note:
redmine_1     |   All old sessions will become invalid.
redmine_1     |   Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
redmine_1     |   **SHOULD** be defined if you have a load-balancing Redmine cluster.
redmine_1     | Configuring redmine::max_concurrent_ajax_uploads...
redmine_1     | Configuring redmine::sudo_mode...
redmine_1     | Configuring redmine::autologin_cookie...
redmine_1     | Configuring redmine::backups...
redmine_1     | Configuring nginx...
redmine_1     | Configuring nginx::redmine...
redmine_1     | Installing plugins...
redmine_1     | Installing gems required by plugins...
redmine_1     | The latest bundler is 1.16.0.pre.2, but you are currently running 1.15.3.
redmine_1     | To update, run `gem install bundler --pre`
redmine_1     | Migrating plugins. Please be patient, this could take a while...
redmine_1     | Migrating easy_gantt (Easy Gantt plugin)...
redmine_1     | == 20170213152215 AddDefaultPrintableTemplate: migrating ======================
redmine_1     | == 20170213152215 AddDefaultPrintableTemplate: migrated (0.0000s) =============
redmine_1     | 
redmine_1     | == 20170224134615 UpdateRestApiSettings: migrating ============================
redmine_1     | == 20170224134615 UpdateRestApiSettings: migrated (0.0158s) ===================
redmine_1     | 
redmine_1     | Installing themes...
redmine_1     | 2017-09-26 20:10:30,269 CRIT Supervisor running as root (no user in config file)
redmine_1     | 2017-09-26 20:10:30,269 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
redmine_1     | 2017-09-26 20:10:30,269 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
redmine_1     | 2017-09-26 20:10:30,269 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
redmine_1     | 2017-09-26 20:10:30,291 INFO RPC interface 'supervisor' initialized
redmine_1     | 2017-09-26 20:10:30,291 CRIT Server 'unix_http_server' running without any HTTP authentication checking
redmine_1     | 2017-09-26 20:10:30,291 INFO supervisord started with pid 1
redmine_1     | 2017-09-26 20:10:31,293 INFO spawned: 'unicorn' with pid 328
redmine_1     | 2017-09-26 20:10:31,294 INFO spawned: 'cron' with pid 329
redmine_1     | 2017-09-26 20:10:31,295 INFO spawned: 'nginx' with pid 330
redmine_1     | 2017-09-26 20:10:32,625 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1     | 2017-09-26 20:10:32,625 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1     | 2017-09-26 20:10:32,625 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by alexbevi** [comment]
@jcormier when you go to the http://localhost:10083/easy_gantt?set_filter=0 does it load or give you an exception. Installing the plugin wasn't a problem; running it was.

**Comment by jcormier** [comment]
Woops didn't notice that.  I get the same error. Looks like adding this before starting the container works after adding the plugin works.

` $ echo "bundle exec rake db:migrate RAILS_ENV=production" > /srv/docker/redmine/redmine/plugins/post-install.sh`

We only run `bundle exec rake redmine:plugins:migrate RAILS_ENV=production` when installing plugins.  I'm going to blame easy_gantt for relying on db:migrate but idk.

If you want to manually run it.
`docker-compose exec redmine sudo -HEu redmine bundle exec rake db:migrate RAILS_ENV=production`

**Comment by alexbevi** [comment]
@jcormier that worked perfectly. Thank you!

**Comment by RaulToomba** [comment]
Please help me, I am using sameersbn/redmine:4.1.1-8,

When I updated to redmine 4 I am getting this error for the  Easy Gantt plugging:

`Database 'redmine' already exists
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:migrate
rake aborted!
**NameError: uninitialized constant RedmineExtensions::Migration**
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.3.11/db/migrate/20150705172511_create_easy_settings.rb:1:in `<top (required)>'`

I tried the fix of jcormier, adding to my dockerfile:

`RUN echo "bundle exec rake db:migrate RAILS_ENV=production" > /srv/docker/redmine/redmine/plugins/post-install.sh`

The line is in the post-install.sh but that didn't solve the issue

**Comment by jcormier** [comment]
> Looks like adding this before starting the container and after adding the plugin works.
> 
> ` $ echo "bundle exec rake db:migrate RAILS_ENV=production" > /srv/docker/redmine/redmine/plugins/post-install.sh`

Just ran into this again, doing the above worked in redmine 4.2.3
