### ISSUE TITLE
git config for container

### ISSUE THREAD

**Issue by soujiro0725** [sameersbn/docker-redmine#271]
I am trying to install [redmine_knowledgebase](https://github.com/alexbevi/redmine_knowledgebase/tree/v3.2.1), but the container dies.

The reason seems that this particular plugin tries to bundle install from github and "fatal: unable to connect to github.com" error appears.

I can fix it temporarily by executing 
`git config --global url."https://".insteadOf git://`
in the container right after docker-compose up command, but I would rather make it convenient by adding the command to docker-compose.yml (if you have a better solution, appreciated).

Adding 
`command: bash -c 'git config --global url."https://".insteadOf git://'`
does not seem to work.

Any idea?

**Comment by jcormier** [comment]
The plugin install script used in the docker looks for a pre-install.sh script before starting to install plugins.

https://github.com/sameersbn/docker-redmine/blob/18231b656e24c8995ce3d9ebef1992d3cb1ebedf/assets/runtime/functions#L929

**Comment by soujiro0725** [comment]
Thanks!  It should work.
