### ISSUE TITLE
to redmine 3.4 - upgrade - any plans?

### ISSUE THREAD

**Issue by zawadaa** [sameersbn/docker-redmine#273]
I use that docker so I'll be very thankfull.

**Comment by TheTwist76** [comment]
@sameersbn  - Is there a plan when upgrade to Redmine 3.4.2? Thanks

**Comment by jcormier** [comment]
I haven't seen @sameersbn comment on any issues for this project in quite some time.  From his history it seems he may have moved on to bitnami based docker images which includes the https://github.com/sameersbn/bitnami-docker-redmine image. Which does appear to have a 3.4.2 redmine release.  I'm not sure what the big differences between these images are.

**Comment by sameersbn** [comment]
Hi. Sorry for the delay. 
I've merged a couple of pull requests and released a bunch of new tags.
Thanks for your patience.

**Comment by Glideh** [comment]
Still no 3.4 in the pipe ?

**Comment by frank-dspeed** [comment]
@Glideh https://github.com/sameersbn/docker-redmine/issues/315
