### ISSUE TITLE
Move logs to volume 

### ISSUE THREAD

**Issue by ejmvar** [sameersbn/docker-redmine#275]
First things FIRST: I love your docker image. It saved my entire life.

Now, this is my trouble, and a temporary solution, in case anybody sees similar issue:

From time to time, when accessing some data (an old wiki page, searching a document, or anything but new issues), I receive errors like:

`Permission denied @ dir_s_mkdir - /home/redmine/redmine/tmp/cache/BB3/AB1 
`
I thought it could be some permission issue from my host filesystem (all data files used from outside the image: backups, dotfiles, files, plugins, themes).
But, NOP
tmp/cache is not exported
Getting into the running image, i've found the failing dirs where created by root, as exposed:

Good dirs:
`drwxrwxr-x 11 redmine redmine 4096 Jul 14 17:40 tmp
`

Bad dirs:
`drwxr-xr-x 3 root root 4096 Jul 17 18:44 tmp/cache/BB3/
`

Right now, it's solved using:
```
docker exec -it sameersbnredminev36313263133_redmine_1 bash -il" >> /home/bin/DOCKER-exec-bash__sameersbnredminev36313263133_redmine_1__.sh
root@9e6009c0de1d:/home/redmine/redmine# chown -R redmine.redmine tmp/

```
Where:
- sameersbnredminev36313263133_redmine_1 : is your docker image

I'm more or less a newby creating images (more than a dumb one), so my first guess (export tmp to host), will wait for now.

My question is: 
Does anybody have an explanation for this root owned dirs under cache?

Again, THANKS FOR YOUR EXCELLENT JOB and sharing!

Eduardo.

**Comment by jcormier** [comment]
What version of the docker image are you running? I haven't seen this occur in sameersbn/redmine:3.3.1.

Note if you need this fix everytime you start the docker, you could put it in a post-install.sh script in the plugin directory.
https://github.com/sameersbn/docker-redmine/blob/18231b656e24c8995ce3d9ebef1992d3cb1ebedf/assets/runtime/functions#L955

**Comment by ejmvar** [comment]
I'm using 3.1.1
It's running from April, due to this version seemed to adapt to currently
installed plugins.

Not the latest, but recent enough for us.

I'm planning to move logs also to the host, in order to remove temporary
files from the running image.

Right now, it's handling 58k issues and huge wikies and attachments without
a hassle.

Thanks for you asking

Eduardo



El 21 jul. 2017 15:17, "jcormier" <notifications@github.com> escribió:

What version of the docker image are you running? I haven't seen this occur
in sameersbn/redmine:3.3.1.

Note if you need this fix everytime you start the docker, you could put it
in a post-install.sh script in the plugin directory.
https://github.com/sameersbn/docker-redmine/blob/
18231b656e24c8995ce3d9ebef1992d3cb1ebedf/assets/runtime/functions#L955

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sameersbn/docker-redmine/issues/275#issuecomment-317075031>,
or mute the thread

**Comment by jcormier** [comment]
Heres a snippet from my docker-compose for mounting the log directory.  Definitely found having them on host machine to be helpful.

    volumes:
    - ./../redmine-data:/home/redmine/data
    - ./../redmine-logs:/var/log/redmine

**Comment by ejmvar** [comment]
Many thanks!!

El 21 jul. 2017 16:37, "jcormier" <notifications@github.com> escribió:

Heres a snippet from my docker-compose for mounting the log directory.
Definitely found having them on host machine to be helpful.

volumes:
- ./../redmine-data:/home/redmine/data
- ./../redmine-logs:/var/log/redmine

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sameersbn/docker-redmine/issues/275#issuecomment-317093696>,
or mute the thread

**Comment by jcormier** [comment]
Closed due to old age
