### ISSUE TITLE
PR: give frank-dspeed more rights

### ISSUE THREAD

**Issue by frank-dspeed** [sameersbn/docker-redmine#276]
@sameersbn Frank Lemanschik should be able to even create labels at present he can only use them.

I need for example to create labels like P0 till P4 for diffrent prioritys and probally later more to optimize our overall flow

**Comment by frank-dspeed** [comment]
is sollved was only not able to do that on the right side menu

**Comment by sameersbn** [comment]
yea. you need to do it from https://github.com/sameersbn/docker-redmine/labels
Again thanks for offering your valuable time for maintaining the repo :clinking_glasses:

**Comment by jcormier** [comment]
I'm guessing I don't have permissions yet since I can't seem to assign labels.

**Comment by frank-dspeed** [comment]
@sameersbn you have forgotten to add @jcormier maybe :) can not add him my self sorry for disturbing 
@jcormier you need to mention him if you want something from him so he gets an alert else he will not regonize that fast.

**Comment by jcormier** [comment]
Just noticed an invite in my inbox.  Apparently i have to accept it first. :p
