### ISSUE TITLE
Proposal: Create gitter chat room for this

### ISSUE THREAD

**Issue by frank-dspeed** [sameersbn/docker-redmine#280]
@sameersbn please add a https://gitter.im/sameersbn/docker-redmine room for live chat between me and @jcormier i have not enought access rights as i don't belong to the sameersbn github organization we will also add a badge to the readme then for support of existing users

- we could need that for weekly meetings of the core team

**Comment by jcormier** [comment]
I'm not sure I have time to support this full time. Or if weekly meetings are necessary.

**Comment by frank-dspeed** [comment]
@jcormier no problem if you don't attend to a meeting i support this fulltime if your not here or its not needed then it is a fast meeting that ok for me also thats not blocking for this issue as a gitter chat is usefull for the users.

**Comment by jcormier** [comment]
Okay, never used gitter. Could be interesting.

**Comment by frank-dspeed** [comment]
@jcormier created https://gitter.com/direktspeed/docker-redmine if you need anything or want to discusse something in a none issue formart
