### ISSUE TITLE
How "bundle update rake" for installing Line Numbers plugin

### ISSUE THREAD

**Issue by jameswangcnln78** [sameersbn/docker-redmine#294]
when I git clone line number ```plugin into plugins directory and restart my redmine container```, the container claims ```"rake version 10.1.1 is requested"``` and suggests me to ```run "bundle update rake"``` and restart automatically looply. So I have to ```add "bundle update rake"``` in pre-install.sh and it seems work.

However, I think this is not good way since command "bundle update rake" will run at each time the container restart which causes more time consuming during start-up process.

Anyone knows a better way to achieve it? Thanks.

James

**Comment by frank-dspeed** [comment]
@jameswangcnln78 the method  looks good to me maybe run that in background to not interupt current start?

**Comment by jcormier** [comment]
@frank-dspeed I'm not that familiar with the rake/bundle system. But don't we need all the packages/plugins setup before we can start the server. I don't think we can just background this install.

@jameswangcnln78 Hmm from the technical perspective the only way to make an install persistent with docker would be to create your own Dockerfile which inherits this one. Or you could try to use a Volume but that seems like it would add more problems than solve in this case.

Looks like our current docker has  version 11.3.0 so we can't simply updated to the other version.
```
$ docker-compose exec redmine bundle exec rake -V
rake, version 11.3.0
```

**Comment by jameswangcnln78** [comment]
@jcormier thank for your reply. I will try Dockerfile.
@frank-dspeed Yes, my way did work. I wonder whether someone knows better way.

**Comment by frank-dspeed** [comment]
@jameswangcnln78 @jcormier i close this as its solved for the first time till we got something better in newer versions feel free if ther is still a issue to reopen thanks all
