### ISSUE TITLE
https doesn't point to my domain

### ISSUE THREAD

**Issue by ThomasAtome** [sameersbn/docker-redmine#295]
Hi,

My container works great in http. But I have some issue when i try to make it work on https. I don't understand how to point my container to my domain. So, my certificates are generated by Let's encrypt for some others services, they work great and point to my domain, they have some env var like server-url, url, etc but i don't see that on this repo.

Well, how can i say to my container in https to point to the domain that is certified and not to my local ip ?

Thanks

**Comment by jcormier** [comment]
> I don't understand how to point my container to my domain.
I'm not sure I understand what your asking.  What do you mean by point your container?

Note that if you already have a https server (apache or nginx?) that has the certificates setup, you could set them up to proxy the incoming requests to the redmine service.

My docker-compose has the following lines.  The apache server which is running on the same machine then forwards requests to domain.com/redmine to the redmine service on localhost:10080.  I thus don't have to enable https on the docker container as apache handles this.
```
    ports:
# Bind to localhost, apache will proxy user to server
    - "127.0.0.1:10080:80"
```

**Comment by ThomasAtome** [comment]
Well i try your solution, but this doesn't work.

This is my conf in nginx :

`server {
  listen 4489;
  
  # Add headers to serve security related headers
  add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
  add_header X-Content-Type-Options nosniff;
  add_header X-Frame-Options "SAMEORIGIN";
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Robots-Tag none;
  add_header X-Download-Options noopen;
  add_header X-Permitted-Cross-Domain-Policies none;

  gzip off;

  ## Strong SSL Security   
  ## https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html & https://cipherli.st/   
  ssl on;
  ssl_certificate /etc/nginx/certs/private.atome.io/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/private.atome.io/key.pem;

  ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 5m;

  location / {
    proxy_pass http://127.0.0.1:4490/;
  }
}`

**Comment by jcormier** [comment]
> Well i try your solution, but this doesn't work.
What doesn't work? Any error messages in the log files?  Are you trying to access the correct url? https://domain:4489/

**Comment by ThomasAtome** [comment]
Well, problem solved sorry, i forget to open port on my box lol..

Thanks for your time !
