### ISSUE TITLE
warning: key :secure is duplicated and overwritten on line 76

### ISSUE THREAD

**Issue by pos-ei-don** [sameersbn/docker-redmine#297]
`/home/redmine/redmine/config/application.rb:76: warning: key :secure is duplicated and overwritten on line 76`

when invoking:  bundle exec rake generate_secret_token.

What I try to fix is that i always get the message "Invalid form authenticity token.". All usual settings in avoiding this doesn't work in my case, so i temporarily switched to "redmine:lastest" which work with my db. I hope to come back so "sameersbn/docker-redmine" soon...
maybe i should file a second issue for that, (of course i used  "REDMINE_SECRET_TOKEN")

**Comment by pos-ei-don** [comment]
The 
"Invalid form authenticity token."
- error is gone if I ignore this advice and set 
REDMINE_HTTPS to false.


```
Using HTTPS with a load balancer

Load balancers like nginx/haproxy/hipache talk to backend applications over plain http and as such the installation of ssl keys and certificates are not required and should NOT be installed in the container. The SSL configuration has to instead be done at the load balancer. Hoewever, when using a load balancer you MUST set REDMINE_HTTPS to true
```

**Comment by jcormier** [comment]
> What I try to fix is that i always get the message "Invalid form authenticity token.". All usual settings in avoiding this doesn't work in my case, so i temporarily switched to "redmine:lastest" which work with my db. I hope to come back so "sameersbn/docker-redmine" soon...
What "usual" settings to avoid this have you tried?  What version of sameersbn were you using?  Can you reproduce it on a fresh database?

**Comment by pos-ei-don** [comment]
- http://www.redmine.org/issues/5230#note-17 same as https://stackoverflow.com/questions/28719646/redmine-422-invalid-form-authenticity-token
- http://www.redmine.org/issues/14237#note-1

tried rake generate_secret_token, and so on...

> Can you reproduce it on a fresh database?

yes! I use it befind an nginx-installation on my gateway-server.  on a fresh database, i can register a new account, but as soon as i hit the ok button, i get this error.
When i directly connect to the exposed port on the docker-installation, i get the same error!
only setting REDMINE_HTTPS to false helps. (so maybe we should just change the dokumentation? what is the reason for suggesting this?)

**Comment by frank-dspeed** [comment]
@pos-ei-don i think https off is logical because the frontend nginx is the one who does requests to the backend so there https off of you use http else you can sure turn https on but thats a advanced config.

if you got no firewall https to https is a good idea with firewall
https -> nginx ->http>ngix-redmine is well

**Comment by frank-dspeed** [comment]
@pos-ei-don the reason for suggesting this was probally a old auto redirect from redmine from https to http if the HTTPS is not set so it was redirect from redmine software wich was reading url.

**Comment by pos-ei-don** [comment]
i just turned it on because of this suggestion! i agree that turnig it off is logical, but i wanted to follow the documentation ;-)

so i turned it off now and it works vor me. i even think that this redirecting-thing works as needed, so i think we should just update the documentation.... thank you anyway for this project!!

**Comment by jcormier** [comment]
> if you got no firewall https to https is a good idea with firewall
> https -> nginx ->http>ngix-redmine is well

> @pos-ei-don the reason for suggesting this was probally a old auto redirect from redmine from https to http if the HTTPS is not set so it was redirect from redmine software wich was reading url.

Just to try to make it clear as mud that it doesn't look like its as simple as an out of date documentation.

https://github.com/sameersbn/docker-redmine/blob/455be2ae0320ba434a341e3bd05926d481f37a6b/assets/runtime/functions#L751-L761
Here ^ it explicitly checks for existing SSL certificates and if not found falls back to http but with a comment about load balancing.

https://github.com/sameersbn/docker-redmine/blob/455be2ae0320ba434a341e3bd05926d481f37a6b/assets/runtime/functions#L792-L795
And here's where it gets interesting/confusing.  We enable the secure flag on the authentication cookie if HTTPS is enabled.  Looking up 'redmine secure-cookie' returns quite a few results.
http://www.redmine.org/boards/1/topics/41137
http://www.redmine.org/boards/2/topics/50318  <-- Here's your "Invalid form authenticity token"
http://www.redmine.org/issues/21697 <- Here is a request to only enable this secure flag if the session was started via https.
http://www.redmine.org/issues/6792 <- Here is perhaps suggesting that you do want the secure flag when using an nginx proxy.

So I guess there are a few questions that come from this.  When you are getting this error message are you accessing redmine via the nginx proxy or directly?  If we leave this disabled are we vulnerable to the attack mentioned here: http://www.redmine.org/issues/6792, when accessing through the https proxy?

**Comment by pos-ei-don** [comment]
> When you are getting this error message are you accessing redmine via the nginx proxy or directly? 
Both as mentioned above. https://github.com/sameersbn/docker-redmine/issues/297#issuecomment-321460839

So it's not the nginx-progy.
I even get it when i disable nginx whithin your image....
I will do some mor testing next week.....
thanks for pointing out this all...

**Comment by jcormier** [comment]
It wasn't apparent from your posts above if you ever tried accessing it from https through your proxy.  It seems clear from the posts i linked above that it won't work when accessing it over http.  However I'm not clear if that also affects the proxy which converts https -> http. Cause if thats the case then there is a bug in how we are doing it/documenting it.

I guess I'm unclear of what the correct solution is at this point.

**Comment by pos-ei-don** [comment]
As I block http-only access, they cannot steal the session by using it without https.
So i don't think that i really need this secure-flag in the cookie. Anyway, as it is the only way to get it working, i currently go without it.....
maybe i'll try https->https->redmine later, but that's not the config i'd like to use either....

**Comment by jcormier** [comment]
> As I block http-only access, they cannot steal the session by using it without https.
> So i don't think that i really need this secure-flag in the cookie.

So I'm not sure blocking http access helps with this vulnerability since the problem occurs when the browser sends your existing session in the cookie over http when either the user accidentally tries http://redmine or someone plants a http://redmine url on your forum.

http://codebutler.com/firesheep-a-day-later
> Full HTTPS for everything — Some sites support full encryption everywhere, but don’t implement it properly by failing to set the “Secure” flag on authentication cookies, negating most of the benefits and leaving users at risk. What that means is that any time you type the URL (e.g. “manage.slicehost.com”) into your web browser (without explicitly typing https:// beforehand, which people rarely do) you will inadvertently leak your cookies with that first request, prior to being redirected to the HTTPS page. Slicehost and Dropbox are good examples of this mistake.

https://www.owasp.org/index.php/SecureFlag
> The secure flag is an option that can be set by the application server when sending a new cookie to the user within an HTTP Response. The purpose of the secure flag is to prevent cookies from being observed by unauthorized parties due to the transmission of a the cookie in clear text.
> 
> To accomplish this goal, browsers which support the secure flag will only send cookies with the secure flag when the request is going to a HTTPS page. Said in another way, the browser will not send a cookie with the secure flag set over an unencrypted HTTP request.

So according to this, the secure flag should only affect the browser, and as long as the browser is connected over https it will send the cookies.  So it seems odd that setting the secure flag on the cookies causes your issue. So on the surface it does seem like we are supposed to be setting this secure flag, so I'm still wondering where the bug is.

Note that I tried testing on our redmine setup to see if I could leak any of my session cookies by accessing the http url.  Our proxy is setup to do a 301 redirect to https, instead of blocking http.  However using both chrome and firefox on my machine I was unable to capture any cookies via wireshark.  The browsers, once they sent the initial http request and got the redirect would remember the 301 and automatically switch to https for every connection after that.  I'm not sure if this would work the same way if you simple blocked http instead of redirecting.

Note that we don't have HTST enabled but we probably should.  Setting this header is supposed to tell the browser to never send traffic to your site over HTTP. This would be configured on the proxy and not in the redmine container I think.

https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet
> HTTP Strict Transport Security (HSTS) is an opt-in security enhancement that is specified by a web application through the use of a special response header. Once a supported browser receives this header that browser will prevent any communications from being sent over HTTP to the specified domain and will instead send all communications over HTTPS. It also prevents HTTPS click through prompts on browsers.

**Comment by thomas-nilsson-irfu** [comment]
Looking at my resulting redmine configuration the line 76, I see that the "secure" value is in fact set two times. Quoting lines 75-77 of the resulting "/home/redmine/redmine/config/application.rb"

```
config.session_store` :cookie_store,
        :secure => true, :secure => true, :key => '_redmine_session',
       :path => config.relative_url_root || '/'

```

I created my instance of redmine with `REDMINE_HTTPS=true` as I wish it to run with https in a secure fashion. But I did not specify, REDMINE_AUTOLOGIN_COOKIE_SECURE (which then defaults to "true".

The cookie settings appears to be set using two separate "sed" calls, once here
[assets/runtime/functions#L303:L309](https://github.com/sameersbn/docker-redmine/blob/master/assets/runtime/functions#L303:L309)
with the help of function update_template()
[assets/runtime/functions#L77:L100](https://github.com/sameersbn/docker-redmine/blob/master/assets/runtime/functions#L77:L100) to run sed once on "${REDMINE_INSTALL_DIR}/config/configuration.yml".

And a second "sed" (based on REDMINE_HTTPS) here in 
[assets/runtime/functions#792:L795](https://github.com/sameersbn/docker-redmine/blob/master/assets/runtime/functions#L792:L795)

I suspect it would suffice to set this "secure" flag only once.

**Comment by jcormier** [comment]
Both these sed calls affect different files. I'm not clear why you think they are related.

> assets/runtime/functions#L77:L100 to run sed once on "${REDMINE_INSTALL_DIR}/config/configuration.yml".
REDMINE_AUTOLOGIN_COOKIE_SECURE effects the configuration.yml file.

> And a second "sed" (based on REDMINE_HTTPS) here in
> assets/runtime/functions#792:L795

And this affects application.rb

**Comment by jcormier** [comment]
So looks like the REDMINE_AUTOLOGIN_COOKIE_SECURE isn't the problem.  

> And a second "sed" (based on REDMINE_HTTPS) here in
assets/runtime/functions#792:L795

The problem appears to be that we do this sed everytime we boot up so if you don't delete your container between runs then the `:secure` flag keeps getting appended.
```
 $ docker-compose down
Removing dockerredmine_redmine_1 ... done
Removing dockerredmine_redmine_run_2 ... done
Removing dockerredmine_redmine_run_1 ... done
Removing dockerredmine_postgresql_1 ... done
Removing network dockerredmine_default
 $ docker-compose run redmine grep 'secure' config/application.rb
Creating network "dockerredmine_default" with the default driver
Creating dockerredmine_postgresql_1
 $ docker-compose up
...
 $ docker-compose exec redmine grep 'secure' config/application.rb
      :secure => true, :key => '_redmine_session',
## Quit with ctrl-c
 $ docker-compose up
...
 $ docker-compose exec redmine grep 'secure' config/application.rb
      :secure => true, :secure => true, :key => '_redmine_session',
 $ docker-compose down
Removing dockerredmine_redmine_run_2 ... done
Removing dockerredmine_redmine_1 ... done
Removing dockerredmine_redmine_run_1 ... done
Removing dockerredmine_postgresql_1 ... done
Removing network dockerredmine_default
 $ docker-compose up
...
 $ docker-compose exec redmine grep 'secure' config/application.rb
      :secure => true, :key => '_redmine_session',
```
