### ISSUE TITLE
REDMINE_RELATIVE_URL_ROOT doesn't work from behind the proxy anymore

### ISSUE THREAD

**Issue by b-a-t** [sameersbn/docker-redmine#302]
I've made a new installation on the redmine:latest and out of the sudden configuration, which always worked to me stopped working, giving 500 error.

I have a setup where there is a frontend `nginx` docker which handles SSL and plain traffic and which is configured with:
```
        location /redmine {
                proxy_pass              http://redmine;
                include                 proxy_params;
        }
```
The `redmine` container is configured, among others, with the options:
```
REDMINE_HTTPS=true
REDMINE_RELATIVE_URL_ROOT=/redmine
NGINX_ENABLED=true
```
Such a configuration used to work well, but not anymore. I was getting 500 error on the frontend, trying to access `my.site/redmine` and cryptic error in the internal `nginx`:
```
2017/08/31 22:43:42 [error] 277#277: *3 the rewritten URI has a zero length, client: 172.17.0.6, server: , request: "GET /redmine HTTP/1.0", host: my.site
```
Not much help, until I came across [this question](https://serverfault.com/questions/527907/redirect-a-subpath-to-a-external-host-with-nginx) on SF.

Looking into the internal nignx configuration I found the line:
```
  location /redmine {
    ## Serve static files from defined root folder.
    ## @redmine is a named location for the upstream fallback, see below.
--> rewrite ^/redmine(.*)$ $1 break;
    try_files $uri index.html $uri.html @redmine;
  }
```
Which is indeed looked like the one in the SF question and by removing which I got my redmine to work again.

Now I see that the related changes were done month ago and, apparently, they were not well tested.

Please, fix it so it works again!

**Comment by frank-dspeed** [comment]
@b-a-t first of all thanks for the issue i was refactoring this to use external nginx for handling ssl also !!

and i am the one who did the changes and i need to tell you normaly this line should be not there :) try 
```
#upstream redmine
server redmine-docker:8080 fail_timeout=0;
```
 in your frontend nginx docker and expose the ports on the redmine docker this offical image will soon default to that behavier and will not serve up with own nginx any more

**Comment by frank-dspeed** [comment]
and by the way the correct RELATIV_URL PATH Setting would now be ```REDMINE_RELATIVE_URL_ROOT=/redmine/````only for docs

**Comment by frank-dspeed** [comment]
@b-a-t also applyed your suggestion with adding the / befor the $1 you can test it out if you like if that still don't works please reopen the ticket
