### ISSUE TITLE
[redmine 3.4.2.stable] no git executable

### ISSUE THREAD

**Issue by josefglatz** [sameersbn/docker-redmine#305]
# Problem

![image](https://user-images.githubusercontent.com/2861556/30521698-46de2e22-9bc4-11e7-8c28-7256b8b3cd07.png)

# What I've tried so far

- Logged in via bash and sudo'd to redmine user executing `git --version` works as expected. So git executable should be there
- Tried to add absolute path to git executable in `configuration.yml` (https://github.com/sameersbn/docker-redmine/blob/18231b656e24c8995ce3d9ebef1992d3cb1ebedf/assets/runtime/config/redmine/configuration.yml#L45) without improvements

---

# Any ideas...

how to enable git support in redmine container to enable support for reading git repos (mounted as RO volume from gitlab container)

## According the redmine wiki, only git 2.11.0 is supported 
http://www.redmine.org/projects/redmine/wiki/RedmineRepositories

Could this be the problem why the git executable isn't respected?

**Comment by josefglatz** [comment]
# found the issue in upstream

`--no-color` option when checking git version must be removed in redmine. Seems like this is already fixed in trunk of redmine 👍

**Comment by josefglatz** [comment]
> http://www.redmine.org/projects/redmine/repository/revisions/16948/diff/trunk/lib/redmine/scm/adapters/git_adapter.rb

**Comment by jcormier** [comment]
Link to the redmine issue: http://www.redmine.org/issues/26645

Fix slated for redmine 3.3.5 and i assume 3.4.3

Is it possible for us to install the older git version to get this working or should we wait for the next redmine release?

**Comment by jcormier** [comment]
Doesn't look like any of our tagged images have the newer git 2.14.0 version. But the latest image does.

```
 $ docker run -it sameersbn/redmine:latest git --version
git version 2.14.1
 $ docker run -it sameersbn/redmine:latest git --version --no-color
error: unknown option `no-color'
usage: git version [<options>]

    --build-options       also print build options
 $ docker run -it sameersbn/redmine:3.3.3 git --version --no-color
git version 2.13.0
 $ docker run -it sameersbn/redmine:3.3.2 git --version --no-color
git version 2.11.0
$ docker run -it sameersbn/redmine:3.3.1 git --version --no-color
git version 2.10.1

```

**Comment by jcormier** [comment]
Quote from @frank-dspeed 

> 
> @jcormier lets wrap git
> 
```
#!/bin/bash
REAL_GIT=path/to/git
$REAL_GIT ${@%--no-color}
```
Following this suggestion.  

```
root@d6debba8257d:/home/redmine/redmine# git --version --no-color
git version 2.14.1
root@d6debba8257d:/home/redmine/redmine# which git
/usr/local/bin/git
```

Preparing commit
