### ISSUE TITLE
Could not verify the SSL certificate for https://rubygems.org/.

### ISSUE THREAD

**Issue by hewerthomn** [sameersbn/docker-redmine#306]
Hello,

at my company we have to import self signed certificates and setup proxys to many things work, but I don't know what to setup in this case.

I used the docker-compose.yml file but this not worked.

```
redmine_1     | Installing gems required by plugins...
redmine_1     | Could not verify the SSL certificate for https://rubygems.org/.
redmine_1     | There is a chance you are experiencing a man-in-the-middle attack, but most
redmine_1     | likely your system doesn't have the CA certificates needed for verification. For
redmine_1     | information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect
redmine_1     | without using SSL, edit your Gemfile sources and change 'https' to 'http'.
redmine_redmine_1 exited with code 17
```

What I can do?

**Comment by jcormier** [comment]
Not really sure how to configure for a proxy. Its unlikely that the container doesn't have the correct certificate since it works for others.  So perhaps your proxy isn't setup correctly?

If you don't care about the ssl you could try to replace the https sources to http...

> To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.

**Comment by normansu-tw** [comment]
That's gem's version out-of-date problem.
I add one line to function.sh and the error message is disappeared.

File: assets/runtime/functions


    @@ -948,6 +948,7 @@ install_plugins() {
           rm -rf ${REDMINE_DATA_DIR}/tmp/plugin_assets/*
    
            echo "Installing gems required by plugins..."
    +       gem update --system
            exec_as_redmine bundle install -j$(nproc) --without development test --path ${REDMINE_INSTALL_DIR}/vendor/bundle --quiet
    
           echo "Migrating plugins. Please be patient, this could take a while..."

**Comment by frank-dspeed** [comment]
good finding we should add that also

**Comment by dfurusaka** [comment]
I think you can override entrypoint with your custom entrypoint.sh.

At first,import your self-signed certificate to the redmine container's CA store (`/etc/ssl/certs`).
And then, just call the original entrypoint (`/sbin/entrypoint.sh`) with `app:start` option.

```shell
#!/bin/bash
# @file some/where/entrypoint.sh

# deploy your self-signed certificate.
cat <<EOF > /usr/local/share/ca-certificates/example.crt
-----BEGIN CERTIFICATE-----
MIICqDCCAZACCQDOTHbbDI3+XjANBgkqhkiG9w0BAQsFADAWMRQwEgYDVQQDDAtl
eGFtcGxlLmNvbTAeFw0yMTA1MTkwMzM0MDVaFw0zMTA1MTcwMzM0MDVaMBYxFDAS
BgNVBAMMC2V4YW1wbGUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEAviVO5ClpPZCVBFZC30XZUAYuwRTrTCKuvnwPn3fMjr4Zcx+YDJXZZQNg/feI
YrGVithIJPhZjVaImoEmvSKopCMOYR7Ft8LbDmlJYlhGfUDXaJFzQYLKQBOcCcGX
1zyR3schV9xVclvrIUssuBahjQbNlnttBSPhlR/syhA1WjazY3kAmJR+mrg8YMeM
3mZzcRVUMZ8ckwDafqCKpJGULnZAxTlPGdTDsnYbJlf5az3zwOMlQJHvyzPOAiIX
doo95Bn5qF/m0OuzqQZ7bqws+nIhjO0vY1epYvMnir0g11JxpkZQWUSbg9TmjPiu
YsjhrGGHdqLgcOl9VKC/xx2gwwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBGTUBX
CCTfaQ/zuXDbZpVGkDwPdOKGMKY3GaYN/K2hqqrt6IWU95e/Aczwj6zx6/0D3FTw
S8fLNxKBzj1xQEqI3Vj6TAMqECTWoJFa9LVbiVC+coB3vuNEEcD01fgaAi5EDMOW
WjZwF8WmI+ebPDkgaS86S3tBFJiWMLeTHg8ceKovAvL4XAHlrDSczVzuANRagNUc
dRW6ghLZCECFXAAeCaqkXIzSddBIXAip/2bPD2vX7W+4yV0zsXVGhWEQTUitUbzy
UiGy036gzC/2jv5ys0F21ZQwnZ2S9T0chVX3Se72taebWeGJcmX3q/q5riSCg15t
ZYkOqt5OfO9N46aN
-----END CERTIFICATE-----
EOF

# import your self-signed certificates to the container.
update-ca-certificates

# execute original entrypoint.
/sbin/entrypoint.sh app:start
```

```yml
version: "3"

services:
  redmine:
    image: sameersbn/redmine:latest
    volumes:
      - some/where/entrypoint.sh:/path/to/entrypoint.sh:ro
    entrypoint: /path/to/entrypoint.sh
```
