### ISSUE TITLE
one error

### ISSUE THREAD

**Issue by lipengbin** [sameersbn/docker-redmine#308]
execute ">docker logs " show info.
and the docker container don't run!

Initializing logdir...
Initializing datadir...
Symlinking dotfiles...
Installing configuration templates...
Configuring redmine...
Configuring redmine::database
Configuring redmine::unicorn...
Configuring redmine::secret_token...
Generating a session token...
Note:
  All old sessions will become invalid.
  Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
  **SHOULD** be defined if you have a load-balancing Redmine cluster.
Configuring redmine::max_concurrent_ajax_uploads...
Configuring redmine::sudo_mode...
Configuring redmine::autologin_cookie...
Configuring redmine::backups...
Configuring nginx...
Configuring nginx::redmine...
Migrating database. Please be patient, this could take a while...
Bundler::GemNotFound: Could not find gem 'rails (= 4.2.8)' in any of the gem sources listed in your Gemfile.
  /var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/resolver.rb:396:in `block in verify_gemfile_dependencies_are_found!'
  /var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/resolver.rb:366:in `each'
  /var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/resolver.rb:366:in `verify_gemfile_dependencies_are_found!'
  /var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/resolver.rb:212:in `start'
  /var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/resolver.rb:191:in `resolve'
  /var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/definition.rb:235:in `resolve'
  /var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/definition.rb:159:in `specs'
  /var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/definition.rb:218:in `specs_for'
  /var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/definition.rb:207:in `requested_specs'
  /var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:109:in `block in definition_method'
  /var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:21:in `setup'
  /var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler.rb:101:in `setup'
  /var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/setup.rb:19:in `<top (required)>'
  /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

**Comment by jcormier** [comment]
How are you launching the image?  What version are you running?

**Comment by lipengbin** [comment]
redmine.sh
->
docker run --name=new-redmine -itd \
  --link=new-postgresql-redmine:postgresql --publish=10083:80 \
  -e "REDMINE_PORT=10083"\
  --volume=/root/redmine/newdata/redmine:/home/redmine/data \
  sameersbn/redmine:3.4.2

os:centos7

docker:Server Version: 17.06.0-ce

**Comment by lipengbin** [comment]
At the beginning，the redmine is running good。
when i removed the redmine continer。
I execute the start command again ,the contianer don't run.

**Comment by jcormier** [comment]
> At the beginning，the redmine is running good。
> when i removed the redmine continer。
> I execute the start command again ,the contianer don't run.
I'm not sure what you mean. Could you provide the steps required to reproduce the error?
