### ISSUE TITLE
Net::IMAP::BadResponseError: Unknown command

### ISSUE THREAD

**Issue by marji** [sameersbn/docker-redmine#318]
I'm running redmine:3.3.4 and recently noticed IMAP collection stopped working - from the imap inbox, it looks it was a couple of months ago.

I can see /var/log/redmine/redmine/cron_rake.log

```
rake aborted!
Net::IMAP::BadResponseError: Unknown command z25mb566414419ook
/home/redmine/redmine/lib/redmine/imap.rb:32:in `check'
/home/redmine/redmine/lib/tasks/email.rake:117:in `block (4 levels) in <top (required)>'
/home/redmine/redmine/app/models/mailer.rb:433:in `with_synched_deliveries'
/home/redmine/redmine/lib/tasks/email.rake:116:in `block (3 levels) in <top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:email:receive_imap
(See full trace by running task with --trace)
```

line 32 of _imap.rb_ says `imap.starttls`, here it is with the content:

```
imap = Net::IMAP.new(host, port, ssl)
if starttls
    imap.starttls
end
```

I start my container with `-e 'IMAP_STARTTLS=false'` so I don't understand how is that possible that the line of code gets executed (I'm a sysadmin with no knowledge of ruby, so my troubleshooting skills are limited, but am very happy to help).

After I removed the 3 lines above - the `if starttls` block - from the _imap.rb_ file, I don't get this error anymore.

Here are all the IMAP settings I'm passing to the redmine container:
```
docker run --name=redmine -d --link=mysql-redmine:mysql \
...
 -e 'IMAP_ENABLED=true' \
 -e 'IMAP_HOST=imap.gmail.com' \
 -e 'IMAP_SSL=true' \
 -e 'IMAP_INTERVAL=5' \
 -e 'IMAP_STARTTLS=false' \
 --restart=unless-stopped \
 sameersbn/redmine:3.3.4
```

Am I setting the docker variable `IMAP_STARTTLS` in a wrong way or is there a bug in the code logic somewhere?

**Comment by marji** [comment]
I found a similar, related problem reported upstream: http://www.redmine.org/issues/24503.

Based on that info, I tried to start my redmine container with
```-e IMAP_STARTTLS```

end verified this environment variable is not present inside the running container. Nevertheless, the
```
if starttls
    imap.starttls
end
```
block still gets executed and fails as per description of this issue.

I assume, the problem - like the http://www.redmine.org/issues/24503 - is this line in [imap.rb](https://github.com/redmine/redmine/blob/5938d080d1eef1128313b39d97020768f9d93a7e/lib/redmine/imap.rb#L27)
```starttls = !imap_options[:starttls].nil?```
sets the _starttls_ variable to true.

**Comment by IgorGrishkov** [comment]
I have the same problem and not found solution...

**Comment by jcormier** [comment]
So this looks like a bug with redmine itself.  However they mention in the redmine issue that it can be worked around by not providing any ssl= syntax to the  `redmine:email:receive_imap` call.

https://github.com/sameersbn/docker-redmine/blob/0dfc93d2c35cad9aa8818f6b33d030a7ff8cb470/assets/runtime/functions#L406

So I would probably change `ssl=${IMAP_SSL}` to `${SSL_OPTION}`. 

And add above the echo line:
```
# Workaround for redmine issue http://www.redmine.org/issues/24503
# If ssl= is set to any value, then it is treated as true.  So don't set ssl= unless IMAP_SSL is true.
if [[ "${IMAP_SSL}" == true ]]
then
  SSL_OPTION="ssl=${IMAP_SSL}"
fi
```

So if either of you want to try these changes and report back it would be appreciated.

**Comment by Bodge-IT** [comment]
Any update on this?  My imap has just stopped collection but I have not the skills to execute the above to test.

**Comment by neffets** [comment]
Problem occurs at the crontab entry for incoming mails.
It does not work because the scripts false recognize the starttls=false entry.

I wanted to patch it automatically, so I use the REDMINE_DATA_DIR/entrypoint.custom.sh script ability

> cat ../volumes/redmine/entrypoint.custom.sh 

```bash
#!/bin/bash

# patch function "redmine_configure_incoming_email" from /etc/docker-redmine/functions line 377
PATCHED_redmine_configure_incoming_email() {
  if [[ ${IMAP_ENABLED} == true ]]; then
    echo "Configuring redmine::incoming_email..."
    crontab -u ${REDMINE_USER} -l |grep -v 'redmine:email:receive_imap' >/tmp/cron.${REDMINE_USER}
    if ! grep -q 'redmine:email:receive_imap' /tmp/cron.${REDMINE_USER}; then
      case ${INCOMING_EMAIL_NO_PERMISSION_CHECK} in
        true)  INCOMING_EMAIL_NO_PERMISSION_CHECK=1 ;;
        false) INCOMING_EMAIL_NO_PERMISSION_CHECK=0 ;;
      esac

      case ${INCOMING_EMAIL_PRIVATE} in
        true)  INCOMING_EMAIL_PRIVATE=1 ;;
        false) INCOMING_EMAIL_PRIVATE=0 ;;
      esac

      INCOMING_EMAIL_OPTIONS="${IMAP_FOLDER:+folder=${IMAP_FOLDER}} \
        ${IMAP_MOVE_ON_SUCCESS:+move_on_success=${IMAP_MOVE_ON_SUCCESS}} \
        ${IMAP_MOVE_ON_FAILURE:+move_on_failure=${IMAP_MOVE_ON_FAILURE}} \
        ${INCOMING_EMAIL_UNKNOWN_USER:+unknown_user=${INCOMING_EMAIL_UNKNOWN_USER}} \
        ${INCOMING_EMAIL_NO_PERMISSION_CHECK:+no_permission_check=${INCOMING_EMAIL_NO_PERMISSION_CHECK}} \
        ${INCOMING_EMAIL_NO_ACCOUNT_NOTICE:+no_account_notice=${INCOMING_EMAIL_NO_ACCOUNT_NOTICE}} \
        ${INCOMING_EMAIL_DEFAULT_GROUP:+default_group=${INCOMING_EMAIL_DEFAULT_GROUP}} \
        ${INCOMING_EMAIL_PROJECT:+project=${INCOMING_EMAIL_PROJECT}} \
        ${INCOMING_EMAIL_STATUS:+status=${INCOMING_EMAIL_STATUS}} \
        ${INCOMING_EMAIL_TRACKER:+tracker=${INCOMING_EMAIL_TRACKER}} \
        ${INCOMING_EMAIL_CATEGORY:+category=${INCOMING_EMAIL_CATEGORY}} \
        ${INCOMING_EMAIL_PRIORITY:+priority=${INCOMING_EMAIL_PRIORITY}} \
        ${INCOMING_EMAIL_PRIVATE:+private=${INCOMING_EMAIL_PRIVATE}} \
        ${INCOMING_EMAIL_ALLOW_OVERRIDE:+allow_override=${INCOMING_EMAIL_ALLOW_OVERRIDE}}"
      # starttls paramete has problems
      echo "*/${IMAP_INTERVAL} * * * * cd ${REDMINE_HOME}/redmine && bundle exec rake redmine:email:receive_imap host=${IMAP_HOST} port=${IMAP_PORT} ssl=${IMAP_SSL} username=${IMAP_USER} password=${IMAP_PASS} ${INCOMING_EMAIL_OPTIONS} RAILS_ENV=${RAILS_ENV} >> ${REDMINE_LOG_DIR}/redmine/cron_rake.log 2>&1" >>/tmp/cron.${REDMINE_USER}
    fi
    crontab -u ${REDMINE_USER} /tmp/cron.${REDMINE_USER}
    rm -rf /tmp/cron.${REDMINE_USER}
  fi
}

PATCHED_redmine_configure_incoming_email
```

**Comment by neffets** [comment]
Patch works as aspected. And its a solution (without reprogramming redmine) not a workaround like mine.

**Comment by Bodge-IT** [comment]
I'll test, please provide instruction.

**Comment by jcormier** [comment]
You can build the image from source, just make sure you change your docker commands after to reference sameersbn/redmine:test.
`docker build -t sameersbn/redmine:test github.com/sameersbn/docker-redmine#imap_workaround`

**Comment by Bodge-IT** [comment]
OK, I don't have tls enabled in my config for the mail account.  I clearly have a different issue.

**Comment by jcormier** [comment]
@Bodge-IT, The problem is that these settings aren't enabled but redmine is interpreting them as enabled.

So in the following example, IMAP_STARTTLS should be disabled but redmine was enabling it.
```
 -e 'IMAP_SSL=true' \
 -e 'IMAP_STARTTLS=false' \
```

@neffets's workaround seems to suggest he was seeing the same thing with IMAP_SSL.

If you feel that you have a different problem, please create a new issue with enough details to help understand what is going wrong.

**Comment by jcormier** [comment]
Pushed this commit to master.

**Comment by marji** [comment]
I can confirm this now works on sameersbn/redmine:3.4.6
