### ISSUE TITLE
Ldap support?

### ISSUE THREAD

**Issue by thanhlq** [sameersbn/docker-redmine#321]
Hello everybody, I don't see any information regarding to the support of LDAP? so I assume that LDAP configuration is not supported yet?

**Comment by frank-dspeed** [comment]
http://www.redmine.org/projects/redmine/wiki/RedmineLDAP

**Comment by thanhlq** [comment]
Oh thanks very much, I forgot that redmine allow to configure ldap directly in dashboard.
