### ISSUE TITLE
Git fetch broken in sameersbn/redmine:latest

### ISSUE THREAD

**Issue by prodigy7** [sameersbn/docker-redmine#322]
Today I recognize, that commits are missing in redmine. After some investigation I found out, that fetching changesets in sameersbn/redmine:latest doesn't work:
```redmine@cf736b92c9fe:~/git$ cd /home/redmine/redmine
redmine@cf736b92c9fe:~/redmine$ ./bin/rails runner "Repository.fetch_changesets" -e production
fatal: '' is not a valid branch name.
fatal: '' is not a valid branch name.
fatal: '' is not a valid branch name.
fatal: '' is not a valid branch name.
fatal: '' is not a valid branch name.
fatal: '' is not a valid branch name.
fatal: '' is not a valid branch name.
fatal: '' is not a valid branch name.
fatal: '' is not a valid branch name.
fatal: '' is not a valid branch name.
fatal: '' is not a valid branch name.
fatal: '' is not a valid branch name.
```
After switching back to sameersbn/redmine:3.4.2 all does working!

**Comment by jcormier** [comment]
Likely related to #305 and #316.

Can you figure out what the git command "Repository.fetch_changesets" is issuing?

**Comment by prodigy7** [comment]
> Can you figure out what the git command "Repository.fetch_changesets" is issuing?

Not really :-/

**Comment by jcormier** [comment]
Updated redmine to 3.4.4 and removed the git workaround.  Hopefully, this fixes the git error.

**Comment by jcormier** [comment]
@prodigy7  Any change with the latest?

**Comment by jcormier** [comment]
Closing issue as there has been no response from @prodigy7

**Comment by alexandrkirilov** [comment]
I've got the same

https://www.redmine.org/issues/29416

Here the explanation

**Comment by alexandrkirilov** [comment]
$ /projects/www/redmine/bin/rails runner "Repository.fetch_changesets" -e production
fatal: '' is not a valid branch name.

**Comment by jcormier** [comment]
@alexandrkirilov  what version of the redmine docker are you running?
