### ISSUE TITLE
REDMINE_RELATIVE_URL_ROOT broken in 3.4.4

### ISSUE THREAD

**Issue by QbProg** [sameersbn/docker-redmine#324]
After upgrading to 3.4.4, if I use 
-e REDMINE_RELATIVE_URL_ROOT=/redmine

and I access the URL "http://server/redmine" I get a page with

Not Found: /

If I don't use REDMINE_RELATIVE_URL_ROOT everything works correctly. I tryed to clean the tmp dir in the data dir but still the same.

**Comment by jcormier** [comment]
Likely related to #218.

Tried setting REDMINE_RELATIVE_URL_ROOT=/redmine.  Loaded http://127.0.0.1:10083/redmine and page showed "Not Found: /".  

Tried setting REDMINE_RELATIVE_URL_ROOT=/redmine/.  Loaded http://127.0.0.1:10083/redmine and page showed 404. Loaded http://127.0.0.1:10083/redmine/ and page showed "Not Found: /".  

So bug confirmed.

**Comment by jcormier** [comment]
@QbProg  Can you confirm this fixes it?

**Comment by QbProg** [comment]
Problem is, I'm a terrible docker user, I only learned to use the docker hub images! What's the quickest way to test it from the source?

**Comment by jcormier** [comment]
You can wait for the docker images to build if you like.
https://hub.docker.com/r/sameersbn/redmine/builds/

**Comment by jcormier** [comment]
Alternatively you can try building the image yourself. See https://github.com/sameersbn/docker-redmine#installation

`docker build -t sameersbn/redmine github.com/sameersbn/docker-redmine`

**Comment by jcormier** [comment]
Woops hang on. Broke the VERSION file.

**Comment by jcormier** [comment]
Alright fixed the REDMINE_VERSION back to 3.4.4.  I don't have permission to cancel the latest build so once it fails, the new images will be built.

**Comment by QbProg** [comment]
3.4.4-2 worked really good, thank you!
