### ISSUE TITLE
3.3.6 automated build fail on Docker Hub

### ISSUE THREAD

**Issue by goodmorning9527** [sameersbn/docker-redmine#325]
3.3.6 automated build fail on Docker Hub. https://hub.docker.com/r/sameersbn/redmine/builds/
I can not pull this image. 
Thank you.

**Comment by jcormier** [comment]
Yeah I noticed this.  The build failure "Build failed: Getting Dockerfile" seems like it may have been a random failure via docker hub.  Unfortunately I can't tell it to rebuild, presumably @sameersbn  has the login details. I suppose I could push a 3.3.6-1 tag to try another build though...

**Comment by jcormier** [comment]
Alright build has finished.
