### ISSUE TITLE
Create backups task just doesn't stop creating backups

### ISSUE THREAD

**Issue by Bodge-IT** [sameersbn/docker-redmine#326]
Last attempt at a manual backup rewarded me with 15 backups!  The old adage about buses just blown out of the water.
![redmine-backup- fail](https://user-images.githubusercontent.com/1881642/35612409-9c0c2b4a-0660-11e8-94bb-55d9ac2e924b.jpg)

I have just updated to 3.4.4.  I had to force it shut.

**Comment by jcormier** [comment]
How exactly did you run the backup?  Tested it myself and only one backup was created.

```
 $ docker-compose run redmine app:backup:create
Starting dockerredmine_postgresql_1
Initializing logdir...
Initializing datadir...
Symlinking dotfiles...
Installing configuration templates...
Configuring redmine...
Configuring redmine::database...
Configuring redmine::unicorn...
Configuring redmine::secret_token...
Generating a session token...
Note:
  All old sessions will become invalid.
  Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
  **SHOULD** be defined if you have a load-balancing Redmine cluster.
Configuring redmine::max_concurrent_ajax_uploads...
Configuring redmine::sudo_mode...
Configuring redmine::autologin_cookie...
Configuring redmine::backups...
Configuring nginx...
Configuring nginx::redmine...
Dumping PostgreSQL database redmine_production...
Dumping files...
Dumping dotfiles...
Dumping plugins...
Dumping themes...
Creating backup archive: 1517509607_redmine_backup.tar...
```

```
 $ docker-compose exec redmine redmine-backup-create
Dumping PostgreSQL database redmine_production...
Dumping files...
Dumping dotfiles...
Dumping plugins...
Dumping themes...
Creating backup archive: 1517509448_redmine_backup.tar...
```

**Comment by Bodge-IT** [comment]
I added app:backup:create to the end of my run statement.
I’m not using docker-compose.
It was working before update to 3.4.4.  I seem to have several issues with this version and now find I cannot go back to 3.4.3.

**Comment by jcormier** [comment]
Docker-compose really shouldn't make a difference vs straight docker.  

Can you provide logs of what your running and the output?

Can you see if its reproducible in a new empty project?

**Comment by jcormier** [comment]
Looking at the backup_create function, I don't see any obvious way this could be looping.
https://github.com/sameersbn/docker-redmine/blob/master/assets/runtime/functions#L981

**Comment by Bodge-IT** [comment]
Hi, this is my run command.  I just appended the create backup tag to this:
docker run -d -it --name=redmine --link=mysql:mysql --restart=unless-stopped --publish=80:80 --env='DB_USER=myuser' --env='DB_PASS=mypass' --env='DB_NAME=redmine' --env='SMTP_DOMAIN=my.email.domain' --env='USERMAP_UID=500' --env='USERMAP_GID=500' --env='SMTP_HOST=email-smtp.eu-west-1.amazonaws.com' --env='SMTP_PORT=465' --env='SMTP_USER=myuserkey' --env='SMTP_PASS=myusersecret' --env='SMTP_TLS=true' --env='SMTP_STARTTLS=true' --volume=/opt/redmine/storage:/home/redmine/data sameersbn/redmine:3.4.4

Could it be the daemon option?  I'll try to test this afternoon

**Comment by jcormier** [comment]
Maybe this `--restart=unless-stopped`

**Comment by Bodge-IT** [comment]
It was either -d or  --restart=unless-stopped but one of those was causing the issue.
Just 1 backup created now.
Thanks for help @jcormier
