### ISSUE TITLE
FeaReq: Add an option to the change the day auto backups run on

### ISSUE THREAD

**Issue by Bodge-IT** [sameersbn/docker-redmine#327]
The auto backups run on a Sunday and there seems no option to change.
I know there are already a lot of options but being able to change the auto day would be extremely useful.  My system is off on a Sunday.

**Comment by jcormier** [comment]
Feel free to fork and add this feature. 

The function is located here which configures the cron job.
https://github.com/sameersbn/docker-redmine/blob/master/assets/runtime/functions#L438

Alternatively, you can use the plugins post-install.sh script and create the cron job yourself.  Essentially take whats in the redmine_configure_backups_schedule function and modify they day_of_week. The example in the https://github.com/sameersbn/docker-redmine#installing-plugins section already shows how to add a cron job there.

**Comment by Bodge-IT** [comment]
Thanks jcormier, I'll give it a go.
