### ISSUE TITLE
data or redmine for docker storage volume.

### ISSUE THREAD

**Issue by Bodge-IT** [sameersbn/docker-redmine#329]
Little bit confused with this.
Documentation says to mount a volume to /home/redmine/data but when I exec into the container, I'm in /home/redmine/redmine

Logs seem to be written to /home/redmine/data/logs
Backups are written to  /home/redmine/redmine/backups.

Plugins don't seem to "install" update when I copy through WinSCP into /home/redmine/redmine/plugins
or at least not at first...

Not sure if this is something I have done while bringing data over from an old bitnami install.
Could someone advise?

**Comment by jcormier** [comment]
Mounting the data directory should create a folder on your host similar to the following, which contains the backups and where you should place your plugins/themes.   You shouldn't be making modifications inside the container.

```
host $ ls /srv/docker/redmine/redmine/
backups  dotfiles  files  plugins  themes  tmp
```

The plugins/themes will be installed into the container when you launch the docker.

You are correct that the logs files won't be mounted per the directions.  I mount the logs directory so I can easily access them from the host machine.

The volumes section of my docker config looks like this
```
    volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
    - /srv/docker/redmine/logs:/var/log/redmine
```

**Comment by Bodge-IT** [comment]
OK, so I mount a seperate EBS volume to /opt/redmine/storage and then serve that to the container as a volume for storing redmine content, in the redmine run command.
Can you see any issues with that approach?

**Comment by jcormier** [comment]
I don't think so, though I don't know much about EBS.

> Reason I ask is that changes do not always show up immediately. it seems like they sync but only after a while or a reboot or something...

What changes? Show up where/how?

**Comment by Bodge-IT** [comment]
So I use WinSCP to connect into my container host and add/remove plugins from /opt/redmine/storage
But if I look into the plugins folder when I exec into the container with:
docker exec -t redmine /bin/bash I enter the container in /home/redmine/redmine

All the folders are there but without changes, I can traverse up to /home/redmine/data and folders are there too, this is where changes are applied.
I know I'm missing a piece of the puzzle here in my understanding

Of course this no longer works at all as my redmine currently unrecoverable from backup.

**Comment by jcormier** [comment]
The plugins and themes directories are copied/synced when the container is started.  I recently added a command to do this on a running container.

See https://github.com/sameersbn/docker-redmine/commit/8cde8483e81314d7dd6b2c57d556071b7c549776

**Comment by Bodge-IT** [comment]
OK, that now explains things.  Thanks for that, I'll add those to my armoury
