### ISSUE TITLE
Trying to install an old version

### ISSUE THREAD

**Issue by RobinScholz** [sameersbn/docker-redmine#334]
Hello there,

I'm trying to transfer an old instance of Redmine running on _2.3.2_ to another server, though on the remote it's installed natively.

My idea for this move was to use a docker container - using this image - instead.
I found that the oldest version in this repository is [version _2.3.3_](/sameersbn/docker-redmine/tree/v2.3.3) and I thought that it shouldn't be a problem to migrate data between _2.3.2_ and _2.3.3_.

The problem I'm facing though is related to depencencies and versions during the sole install process.
The source server runs on Ubuntu 14.04 and is using Ruby _2.1.5_. I used the _2.3.3_ tag of this repository and tried to install it as-is, with Ubuntu 14.04 instead ([the _2.3.3_ version image](/sameersbn/docker-redmine/tree/v2.3.3) is using 12.04), I tried increasing the Ruby version (it installs 1.9 by default) and I also tried to add specific gem versions but it just always fails to install, mostly because some packages related to rails want Ruby 2.2, but installing with Ruby 2.2 broke other stuff.

Is there someone out there that could help me setting this up? I would really appreciate it!

Thanks so far.

**Comment by RobinScholz** [comment]
Could this help?
https://github.com/bundler/bundler-features/issues/120#issuecomment-214514847

**Comment by jcormier** [comment]
Hi @RobinScholz, I, unfortunately, don't have much experience with Ruby.  When I started using this docker, I upgraded our redmine server from 2.x something to the redmine 3.2-stable (newest at the time).  It wasn't too bad though I had to go through every plugin and find a newer replacement only ended up losing a couple of them that we didn't really use anyways.

So from my experience, I can really only help you upgrade.  Maybe someone else can help though...

Heres my plugin notes from back then. Dated roughly 8/2016

Plugins from old redmine

-   (/) redmine_silencer
    Replaced by silencer 2. https://www.redmine.org/plugins/redmine_silencer
-   (/) redmine_favourite_projects
    https://www.redmine.org/plugins/redmine_favourite_projects. Supports up to 3.2.x
    https://www.redmine.org/plugins/favorite_projects This one is 3.3.x compatible.
-   (/) redmine_release_notes
    https://www.redmine.org/plugins/redmine_release_notes. Supports up to 2.4.x
    https://www.redmine.org/plugins/release_logs. Possible alternative.
-   (/) redmine_charts2
    https://www.redmine.org/plugins/redmine_charts2. Supports up to 2.3.x
-   (/) redmine_banner
    https://www.redmine.org/plugins/redmine_banner
-   (/) redmine_wiki_notes
    https://www.redmine.org/plugins/redmine_wiki_notes. Supports up to 1.2.x. May be simple enough to work.
-   SKIP redmine_plugin_views_revisions
    https://www.redmine.org/plugins/redmine_plugin_views_revisions. Supports up to 2.1.x. Doesn't seem necessary.
-   DOESN'T WORK redmine_embedded
    https://www.redmine.org/plugins/redmine-embedded. Supports up to 2.0.x. Do we even use this?
-   (/) project_alias
    Replaced by https://www.redmine.org/plugins/redmine_project_alias_2
-   (/) redmine_wiki_extensions
    https://www.redmine.org/plugins/redmine_wiki_extensions. Supports up to 3.0.x
    http://www.r-labs.org/projects/r-labs/wiki/Wiki_Extensions_en
-   (/) open_flash_chart
    Dependency of charts2
-   SKIPPED clipboard_image_paste
    https://www.redmine.org/plugins/clipboard_image_paste. Supports up to 3.0.x
    Issue reports interfering with drag/drop attachment support. https://github.com/peclik/clipboard_image_paste/issues/55#issuecomment-217409530

**Comment by jcormier** [comment]
Closing this issue
