### ISSUE TITLE
chmod: changing permissions of ‘/var/lib/postgresql’: Permission denied

### ISSUE THREAD

**Issue by SkazochnikZlodey** [sameersbn/docker-redmine#335]
Please change documentation.
from:
 docker run --name=postgresql-redmine -d \
>   --env='DB_NAME=redmine_production' \
>   --env='DB_USER=redmine' --env='DB_PASS=password' \
>   --volume=/srv/docker/redmine/postgresql:/var/lib/postgresql \
>   sameersbn/postgresql:9.6-2
to
 docker run --name=postgresql-redmine -d \
>   --env='DB_NAME=redmine_production' \
>   --env='DB_USER=redmine' --env='DB_PASS=password' \
>   --volume=/srv/docker/redmine/postgresql:/var/lib/postgresql:z \
>   sameersbn/postgresql:9.6-2

changes : /var/lib/postgresql > /var/lib/postgresql:z

**Comment by SkazochnikZlodey** [comment]
Same for :

docker run --name=redmine -d   --link=postgresql-redmine:postgresql --publish=10083:80   --env='REDMINE_PORT=10083'   --volume=/srv/docker/redmine/redmine:/home/redmine/data   sameersbn/redmine:3.4.4-2

docker run --name=redmine -d   --link=postgresql-redmine:postgresql --publish=10083:80   --env='REDMINE_PORT=10083'   --volume=/srv/docker/redmine/redmine:/home/redmine/data:z   sameersbn/redmine:3.4.4-2

changes : changes :  --volume=/srv/docker/redmine/redmine:/home/redmine/data to  --volume=/srv/docker/redmine/redmine:/home/redmine/data:z

**Comment by jcormier** [comment]
Alright, I was not familiar with this option so here is the documentation.
https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label

And the warning associated with this option:

> Use extreme caution with these options. Bind-mounting a system directory such as /home or /usr with the Z option renders your host machine inoperable and you may need to relabel the host machine files by hand.

I'm not sure we want to set this as a recommended default considering it changes permissions on the host side of the system.

Can you explain why you think this is required? 

Note, here is a long discussion on why this could be dangerous. https://github.com/moby/moby/issues/30934

Perhaps adding a section to the documentation describing how to configure if the system is using selinux would be enough?
