### ISSUE TITLE
Support for git repository hosting

### ISSUE THREAD

**Issue by gionn** [sameersbn/docker-redmine#34]
Hi,

I've taken a peek on the latest image available, and I don't see any plugin to enable git repository hosting.

Any suggestions?

**Comment by kopax** [comment]
@sameersbn 

`Technically if you use gitlab for the code hosting and repository management. Running redmine with the --volumes-from gitlab docker option would make all your gitlab repositories available in redmine.`

I have just tried, I have nothing.
I've also connected and check for the presence of /home/git/data and it is here.

Do I have anything more to setup ?

**Comment by sameersbn** [comment]
@kopax it will only make the repositories directory available on the redmine container. You still need to manually add the repository path in your projects.

**Comment by kopax** [comment]
@sameersbn actually, I have never used redmine, I use trak. I just wanted to test, could you tell me where I can add the repository path in redmine ?

**Comment by kopax** [comment]
@sameersbn ok

**Comment by agustisanchez** [comment]
I found the same problem (`entry or revision not found`) when mounting a volume containing Git repos. I `docker ssh` into the running `redmine` container and I can see the repos but get the aforementioned error when referencing the repo in Redmine UI.

**Comment by agustisanchez** [comment]
Same problem if the Git repo is created inside the redmine container in a regular directory.

**Comment by sameersbn** [comment]
@agustisanchez The redmine user (uid: 1000) needs to have the required permissions to the git repos. There are two ways to solve this

1. Use the `USERMAP_` options to map the redmine user to the UID of the user that owns the git repos. 
2. Create a entrypoint.custom.sh which adds the redmine user to a group that has access to the gire repos.

Refer #123 for some more details.

**Comment by GordonKiomon** [comment]
@sameersbn are you able to give some detail step for how to link gitlab to redmine? i had a hard time to make it works here, what else configs or settins should i do except `--volume-from=gitlab`?

**Comment by sameersbn** [comment]
@GordonKiomon it goes without saying that for `--volumes-from=gitlab` to work, gitlab should also be running in a container.

The `--volume-from=gitlab` only makes available the `/home/git/data` volume available in the redmine container at the same path. From that point on everything is a manual process. So if you want a git repository to be browsable from redmine you need to go to **project > settings > repositories** in redmine and add the path to the git repository which be be located inside `/home/git/data/repositories/`

**Comment by GordonKiomon** [comment]
@sameersbn I did start a gitlab container, but do not reallize that i need to manually do the settings, thought there might be some setting or config which could be done in redmine to make it talk with gitlab automatically. 
thank you, i will try it out.

**Comment by GordonKiomon** [comment]
@sameersbn  finally made it works, but not convenient to make the git repo work in this way. seems you guys talked about work on a new image with "redmine_git_hosting", any news on that?

**Comment by sameersbn** [comment]
No. This image will not add any third party plugins. You will need to create a new image which you can base on top of this image to add the `redmine_git_hosting` plugin.

**Comment by grahovam** [comment]
I am using both sameers gitlab and redmine image for our project code hosting and management. Since I want the gitlab repos to be visible in redmine, both images have to be on the same host. In addition, I am using jwilder/nginx-proxy so that there is different URLs for gitlab and redmine. But now i read the following article:
https://www.lvh.io/posts/dont-expose-the-docker-socket-not-even-to-a-container.html
It says that exposing the docker socket is a security risk. This makes using jwilder/nginx-proxy a security risk.

Is there another option for having different URLs for redmine and gitlab than using jwilder/nginx-proxy?

**Comment by sameersbn** [comment]
@grahovam yes. exposing your docker socket to containers poses a very serious security risk. I have never used the `jwilder/nginx-proxy` image before, but from the documentation it appears that it automatically updates the nginx vhost configs when containers are started and stopped.

If you wish to get rid of the security implications that exposing the docker socket has, you can create the vhost configs manually without relying on `jwilder/nginx-proxy` to do them for you. If the `jwilder/nginx-proxy` doesn't allow you to create vhost configs, then you can switch to some other nginx image that allows you to do so.
