### ISSUE TITLE
Sometimes extremely slow loading

### ISSUE THREAD

**Issue by simonbuehler** [sameersbn/docker-redmine#345]
Hi,

sometimes the redmine application does respond extremely slow like this:
```
Started GET "/" for 37.201.5.59 at 2018-07-17 15:06:23 +0000
Processing by WelcomeController#index as HTML
  Current user: Simon (id=7)
  Rendered welcome/index.html.erb within layouts/base (3813.1ms)
Completed 200 OK in 12777ms (Views: 9309.8ms | ActiveRecord: 724.6ms)
Started GET "/my/account" for 37.201.5.59 at 2018-07-17 15:06:40 +0000
Processing by MyController#account as HTML
  Current user: Simon (id=7)
  Rendered users/_mail_notifications.html.erb (2048.9ms)
  Rendered users/_preferences.html.erb (3193.6ms)
  Rendered my/_sidebar.html.erb (550.2ms)
  Rendered my/account.html.erb within layouts/base (9661.9ms)
Completed 200 OK in 11921ms (Views: 10491.0ms | ActiveRecord: 365.3ms)
```

then after logging in and out it gets faster (most of the time) but i can't seem to find a cause for it.
running it with this config:
```

DB_HOST | mysql
-- | --
DB_PASS | xxx
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUBY_VERSION | 2.3
REDMINE_VERSION | 3.4.4
REDMINE_USER | redmine
REDMINE_HOME | /home/redmine
REDMINE_LOG_DIR | /var/log/redmine
REDMINE_CACHE_DIR | /etc/docker-redmine
RAILS_ENV | production
REDMINE_INSTALL_DIR | /home/redmine/redmine
REDMINE_DATA_DIR | /home/redmine/data
REDMINE_BUILD_DIR | /etc/docker-redmine/build
REDMINE_RUNTIME_DIR | /etc/docker-redmine/runtime
SMTP_HOST | xxx.de
SMTP_USER | xxx
SMTP_PASS | xxx
SMTP_PORT | 465
SMTP_TLS | true
IMAP_HOST | xxx.de
SMTP_METHOD | async_smtp
IMAP_ENABLED | true
IMAP_INTERVAL | 10
REDMINE_BACKUP_SCHEDULE | daily
```

how can i debug the slowdowns any further, the docker host is powerfull and always has has less then ~10% cpu load, others containers do run fine

**Comment by jcormier** [comment]
I'm not sure though I'm pretty curious myself.

**Comment by simonbuehler** [comment]
is there any hint on how to fix this?

**Comment by jcormier** [comment]
I am not an expert in Ruby on Rails or redmine.  There may be some options to diagnose slowdowns that I'm not aware of.

**Comment by simonbuehler** [comment]
this must have something to to with some timeout of the unicorn server, after 30 minutes of idle time the slowdowns do occur, what setting does release a pool or connection after that time?

**Comment by frank-dspeed** [comment]
@simonbuehler you should study that and also how to benchmark that i think this is out of the scope for this image as it is not responsible for the environment it runs in.

**Comment by simonbuehler** [comment]
i fixed it with a dirty curl getting the homepage every 15 minutes, but the slowdown is caused  by the redmine/unicorn config inside image not the outside environment

**Comment by jcormier** [comment]
> this must have something to to with some timeout of the unicorn server, after 30 minutes of idle time the slowdowns do occur, what setting does release a pool or connection after that time?

I checked and there is no such setting that I could find.  
https://bogomips.org/unicorn/TUNING.html
https://bogomips.org/unicorn/Unicorn/Configurator.html

Could your server be putting your disks to sleep or something similar? I don't think there's much we can do to diagnose this.
