### ISSUE TITLE
docker-compose up

### ISSUE THREAD

**Issue by TonyYule** [sameersbn/docker-redmine#353]
The quickest way to get started is using docker-compose.

wget https://raw.githubusercontent.com/sameersbn/docker-redmine/master/docker-compose.yml
docker-compose up

Creating redmine_postgresql_1 ... done
Creating redmine_postgresql_1 ...
Creating redmine_redmine_1    ... done
Attaching to redmine_postgresql_1, redmine_redmine_1
postgresql_1  | Initializing datadir...
postgresql_1  | Initializing certdir...
postgresql_1  | Initializing logdir...
postgresql_1  | Initializing rundir...
postgresql_1  | Setting resolv.conf ACLs...
postgresql_1  | Initializing database...
redmine_1     | Initializing logdir...
redmine_1     | Initializing datadir...
redmine_1     | Generating OpenSSH client keys...
redmine_1     | Symlinking dotfiles...
redmine_1     | Installing configuration templates...
redmine_1     | Configuring redmine...
postgresql_1  | Configuring hot standby...
postgresql_1  | ‣ Setting postgresql.conf parameter: wal_level = 'hot_standby'
postgresql_1  | ‣ Setting postgresql.conf parameter: max_wal_senders = '16'
postgresql_1  | ‣ Setting postgresql.conf parameter: checkpoint_segments = '8'
postgresql_1  | ‣ Setting postgresql.conf parameter: wal_keep_segments = '32'
postgresql_1  | ‣ Setting postgresql.conf parameter: hot_standby = 'on'
postgresql_1  | ‣ Setting postgresql.conf parameter: data_directory = '/var/lib/postgresql/9.6/main'
postgresql_1  | ‣ Setting postgresql.conf parameter: log_directory = '/var/log/postgresql'
postgresql_1  | ‣ Setting postgresql.conf parameter: log_filename = 'postgresql-9.6-main.log'
postgresql_1  | ‣ Setting postgresql.conf parameter: ssl = 'off'
postgresql_1  | Creating database user: redmine
postgresql_1  | psql: could not connect to server: No such file or directory
postgresql_1  | 	Is the server running locally and accepting
postgresql_1  | 	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
postgresql_1  | psql: could not connect to server: No such file or directory
postgresql_1  | 	Is the server running locally and accepting
postgresql_1  | 	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
redmine_postgresql_1 exited with code 2
redmine_1     | Configuring redmine::database...........................................................
redmine_1     | Could not connect to database server. Aborting...
redmine_redmine_1 exited with code 1

why

**Comment by jcormier** [comment]
Strange. Sounds like you got it working.  Closing issue.
