### ISSUE TITLE
Modify workflow setting field permission but it is not workable

### ISSUE THREAD

**Issue by tailsice** [sameersbn/docker-redmine#355]
I've been using Sameer's docker version of Redmine now. It's great to me.
But I want to modify field permission for role. When I modify Administrator -> Setting -> Workflow -> Fields permission -> Role and Track Edit. But when I finished modify it, but it still not workable. I want add some field be required field. But I cannot do it.
Do you have easier way to get things working.

Thanks
Tails

**Comment by tailsice** [comment]
Hi, 

Thanks for your help.
I need add category and due date become requirement field.
So I change field permission for it as below step

Administration -> Workflow -> Fields Permission -> Role:Developer Tracker:all -> Category:Required, Due date: Required

But it is not workable

**Comment by jcormier** [comment]
Are you testing this with a user that has the Developer role for that project?  I tried this with the Admin account and it didn't prompt me for the required fields but when I created an account and set them as developer in test project.  It wouldn't let me create a new issue without entering the due date.

**Comment by tailsice** [comment]
Hi, 

Thanks for your help.
I try use Developer role to modify issue will see the field be required. Sorry, it’s bothering
But admin role will not see requirement field is right user experience ?

**Comment by jcormier** [comment]
I'm not a redmine developer but yes that seems to be what they intended.  Admin's get to break the rules I assume.
