### ISSUE TITLE
a plugin of redmine_image_clipboard_paste

### ISSUE THREAD

**Issue by HalfWater** [sameersbn/docker-redmine#357]
I found a plugin, it's redmine_image_clipboard_paste.
I think it's so good ,wonderful and useful, i exec docker cp it into plugin dir, then  exec command and restart container, it worked success.
Count you add it in docker-redmine as a default function?
The url is https://github.com/thorin/redmine_image_clipboard_paste
And there is another plugin https://github.com/peclik/clipboard_image_paste, but i config it failed, you can try it.

**Comment by jcormier** [comment]
We don't include any plugins in the container.  If you want to use the plugin follow: https://github.com/sameersbn/docker-redmine#installing-plugins
