### ISSUE TITLE
docker-compse up -d  出现如下 problem 

### ISSUE THREAD

**Issue by jishandong** [sameersbn/docker-redmine#358]
[root@roerpcs11 redmine]# docker-compose up --build

redmine_1     | rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/bin': Directory not empty
redmine_1     | rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/cache': Directory not empty

**Comment by jcormier** [comment]
You've not given me many details here.  But I'd recommend running `docker-compose down` and deleting the tmp directory at `/srv/docker/redmine/redmine`.  I generally see this if I've changed redmine versions.

**Comment by jishandong** [comment]
when I delete all files  at /srv/docker/redmine/ ，then i execute “docker-compse up -d” 

it looks likes as  fellow:

[root@rofckub12 jisd]# docker logs b9aa724da1f9
Initializing logdir...
Initializing datadir...
Generating OpenSSH client keys...
Symlinking dotfiles...
Installing configuration templates...
Configuring redmine...
Configuring redmine::database....
Configuring redmine::unicorn...
Configuring redmine::secret_token...
Generating a session token...
Note:
  All old sessions will become invalid.
  Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
  **SHOULD** be defined if you have a load-balancing Redmine cluster.
Configuring redmine::max_concurrent_ajax_uploads...
Configuring redmine::sudo_mode...
Configuring redmine::autologin_cookie...
Configuring redmine::backups...
Configuring nginx...
Configuring nginx::redmine...
**Migrating database. Please be patient, this could take a while...
redmine_production already exists**
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/bin': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/cache': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/kgio-2.11.2': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/mysql2-0.4.10/mysql2': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.8.3/nokogiri': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/pg-0.18.4': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/raindrops-0.19.0': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/redcarpet-3.4.0': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/rmagick-2.16.0': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/unicorn-5.4.0': Directory not empty
rm: cannot remove '/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/actionmailer-4.2.8/lib/action_mailer': Directory not empty

**Comment by jcormier** [comment]
Did you run `docker-compose down`?

**Comment by jcormier** [comment]
Closed due to no user input
