### ISSUE TITLE
Official Synology "Docker Redmine" package

### ISSUE THREAD

**Issue by mcondarelli** [sameersbn/docker-redmine#359]
Hi,
My problem was to transport a defunct (files mostly intact, but system not booting) Redmine installation to a new home.
This new home is a beefed-up (8G RAM) Synology DS415+ NAS.
Synology provides a large number of installable "packages" one of which is "Docker Redmine"; this package seems to rely heavily on this project as, after installation, I get the following info from dockerd:

![dockerd info](https://user-images.githubusercontent.com/870849/46000852-0a9f8580-c0aa-11e8-9a9f-2c40484a69ed.png)

Problem is Synology scripts hide the low-level docker handling behind a nice GUI and so I have problems following manual operations detailed here.

NOTE: I managed to do almost all I needed to do; this "Issue" is mostly for reference and to aid other people who might have my same problems. Any comment from more knowledgeable people would be, of course, very welcome.

Here is what I did:

1. extract "redmine" database from defunct MariaDB by overwriting database directory (/var/packages/MariaDB10/target/mysql) with my salvaged files and then using the usual `mysqldump` command (with "drop tables").
2. Restore the "original" (empty) database files and recreate the tables from backup (mysqldump <backup.sql).
3. Copy old "files" subdirectory contents to the docker mount (/volume1/docker/redmine/files).
4. copy the needed plugins (redmine_dmsf & plantuml, in my case) to the right place (/volume1/docker/redmine/plugins).
4. Open a terminal in the running container (docker exec -it synology_redmine bash).
5. Perform gem updates (bundle update).
6. Perform database update (bundle exec rake db:migrate RAILS_ENV=production).
7. Perform plugins update (bundle exec rake redmine:plugins:migrate RAILS_ENV=production.
8. Enjoy.

I had some troubles integrating the GIT repos as Synology GIT server package wants repos in a well defined place (/volume1/git), which is not visible by redmine. Placing symlinks won't work (of course!) and doing a "bind mount" would break at next DSM upgrade, so I resorted (ugly solution!) at putting the "real" repositories in redmine data path (/volume1/docker/redmine/git) and symlinking from the "git directory" (/volume1/git).  I am looking for a better solution.

Another thing where I am looking for a better solution is the web server reverse proxy system.
Sameersbn/docker-redmine comes with it's own reverse proxy (nginx) while Synology has a "Web Station" package capable of handling multiple (vitual) sites using either NginX or Apache 2.2/2.4 as backend.
The only way I could have those two thing coexist is to discriminate at the port-number level, but this is far from being "nice".
Ideally all connections should go through central Synology server (including TLS certificates) to be dispatched (locally, that shouldn't require encryption) as required, but I'm unsure just how to plug this in sameersbn/docker-redmine.

**Comment by jcormier** [comment]
I'm curious if you really needed to do these steps.  The container is supposed to auto run these at launch if it detects the plugins have changed.

- Open a terminal in the running container (docker exec -it synology_redmine bash).
- Perform gem updates (bundle update).
- Perform database update (bundle exec rake db:migrate RAILS_ENV=production).
- Perform plugins update (bundle exec rake redmine:plugins:migrate RAILS_ENV=production.

Note: For future reference, editing your post and adding more questions doesn't send a new email so I didn't notice at first the email and your post was different.

> Another thing where I am looking for a better solution is the web server reverse proxy system.
> Sameersbn/docker-redmine comes with it's own reverse proxy (nginx) while Synology has a "Web Station" package capable of handling multiple (vitual) sites using either NginX or Apache 2.2/2.4 as backend.

We had some work towards moving the included nginx install into a separate container but it hasn't gotten anywhere yet. 

What I did on my server was to map docker-redmine's port to a localhost only port and then use apache to proxy traffic to it.  While its true that ideally, apache could take over what nginx is doing, I didn't want to redo all the setup/configuration that is already setup for nginx.  And I wanted all my redmine specific setup handled in moveable containers and not relying on the HOSTs OS.

**Comment by mcondarelli** [comment]
I *think* I needed those steps because my previous Redmine installation was older (3.0.0) and thus my ported database was not "current".
It might be I could have skipped the last  step, but trying to run without the first two "bundle ..." commands resulted in "error 500".
Anyway they didn't hurt ;)

I will try the "double proxy" option, but the Synology server is not really powerful (Intel Atom C2538, Quad Core, DDR3 2GB beefed up to 8GB) and I fear a performance hit.

About the GIT integration problem:
Can I add a new volume to the container (e.g.: "--volume /volume1/git:/opt/git") and expect it to be picked up, or should I use some ENV vatiable to notify a new volume is to be used?
