### ISSUE TITLE
Routing a sub domain to redmine ip

### ISSUE THREAD

**Issue by JintoAntony** [sameersbn/docker-redmine#363]
I want to route a sub domain to this redmine account. How to do that ..?

**Comment by jcormier** [comment]
Could you be more specific? 

This doesn't seem like a problem with the docker-redmine specific container.

**Comment by frank-dspeed** [comment]
@jcormier we should not handle that as he is asking none related questions this container works with any subdomain he has problems to configure his webserver or service its out of scope
