### ISSUE TITLE
SSL not starting even in container

### ISSUE THREAD

**Issue by hhoria** [sameersbn/docker-redmine#372]
Works on 80, doesn't start on 443 inside container, let alone outside container from the mapped port.
Inside the container there is neither 43324 or 443

Started the docker image with

docker run --name=redmine -d --publish=43323:80 --publish 43324:443 --env='REDMINE_PORT=43324' --env='REDMINE_HTTPS=true' --volume=/server/redmine/:/home/redmine/data sameersbn/redmine:2.5.1

[LogsRedmineDockerSSL1.txt](https://github.com/sameersbn/docker-redmine/files/2736759/LogsRedmineDockerSSL1.txt)

**Comment by StefanCristian** [comment]
docker run --name=redmine -d --publish=8080:80 --publish 443:443 --env='REDMINE_PORT=443' --env='REDMINE_HTTPS=true' --volume=/server/redmine/:/home/redmine/data sameersbn/redmine:2.5.1

Reproduced on my side as well. Is it the version?

**Comment by jcormier** [comment]
That version of the container doesn't support HTTPS.
https://github.com/sameersbn/docker-redmine/tree/e3da0066bac8cea5f5d04c2d1e82dd6832960f42

According to the commit diff between the 2.5.1 release and the 2.5-stable branch.  HTTP was added in Aug 2014 and requires atleast tag 2.5.2-1
