### ISSUE TITLE
SMTP_PASS parameter causing parse error for configuration.yml file for unicorn

### ISSUE THREAD

**Issue by Paladiamors** [sameersbn/docker-redmine#373]
When trying to parse the password in the configuration.yml file for redmine I get the following error:

```
/usr/lib/ruby/2.3.0/psych.rb:379:in `parse': (<unknown>): found unknown escape character while parsing a quoted scalar at line 25 column 17 (Psych::SyntaxError)
        from /usr/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
        from /usr/lib/ruby/2.3.0/psych.rb:327:in `parse'
        from /usr/lib/ruby/2.3.0/psych.rb:254:in `load'
        from /home/redmine/redmine/lib/redmine/configuration.rb:86:in `load_from_yaml'
        from /home/redmine/redmine/lib/redmine/configuration.rb:42:in `load'
        from /home/redmine/redmine/lib/redmine/configuration.rb:67:in `[]'
```

Inside the docker-compose.yml
`SMTP_PASS=Ag1JPqxxxxxEt\/luwfpY0ZkYayu`

inside the configuration.yml
`password: "Ag1JPqxxxxxEt\/luwfpY0ZkYayu"`

I modify the configuration.yml file to replace the double quotes to single quotes:
`password: 'Ag1JPqxxxxxEt\/luwfpY0ZkYayu'`

And the unicorn process is able to start. Looks like the problem was solved by switching to single quotes?

**Comment by jcormier** [comment]
Could you verify that the pushed commit fixes it?

**Comment by Paladiamors** [comment]
Hello, yup this change does stop the errors from happening and the error message stops being cyclic
