### ISSUE TITLE
Prepare redmine docker container for use with redmine_bots

### ISSUE THREAD

**Issue by prodigy7** [sameersbn/docker-redmine#385]
Is there any chance, prepare docker-redmine for using with https://github.com/centosadmin/redmine_bots ? So far the plugin needs TDLib for running.

Or is there any way, integrate that package by myself without complete fork this repository?

**Comment by jcormier** [comment]
What your looking for is the pre-install.sh and post-install.sh scripts mentioned https://github.com/sameersbn/docker-redmine#installing-plugins
