### ISSUE TITLE
Error in NetworkExplorer on Orange3

### ISSUE THREAD

**Issue by marromcb** [sameersbn/docker-redmine#386]
I'm running Orange3 from Anaconda.
I'm trying to use Network Explorer but it appear that error
Does anyone know what it means?
Thank you in advance,
M.
![errorr-orange](https://user-images.githubusercontent.com/26971441/53051191-75d26580-3458-11e9-96a7-b2f8d01ca92d.jpg)

**Comment by jcormier** [comment]
What does this have to do with Redmine?

**Comment by marromcb** [comment]
sorry, wrong repository, 
 you can delete that issue

**Comment by frank-dspeed** [comment]
hahaha nice
