### ISSUE TITLE
Application Could not connect to database server

### ISSUE THREAD

**Issue by 50l1d7r33** [sameersbn/docker-redmine#387]
I have a Redmine environment with Docker Compose. With the following versions:

` postgresql:
    image: sameersbn/postgresql:9.6-4
`
` redmine:
    image: sameersbn/redmine:3.4.6
`

At the moment I am no longer able to start the application. The database seems to run clean. I can create a dump directly in the container. But the container aborts after the following steps: 

```postgresql_1  | Initializing datadir...
redmine_1     | Initializing logdir...
redmine_1     | Initializing datadir...
redmine_1     | Symlinking dotfiles...
redmine_1     | Installing configuration templates...
redmine_1     | Configuring redmine...
postgresql_1  | Initializing certdir...
postgresql_1  | Initializing logdir...
postgresql_1  | Initializing rundir...
postgresql_1  | Setting resolv.conf ACLs...
postgresql_1  | Creating database user: redmine
postgresql_1  | Creating database: redmine_production...
postgresql_1  | ‣ Granting access to redmine user...
postgresql_1  | Starting PostgreSQL 9.6...
postgresql_1  | LOG:  database system was shut down at 2019-02-20 06:54:29 UTC
postgresql_1  | LOG:  MultiXact member wraparound protections are now enabled
postgresql_1  | LOG:  database system is ready to accept connections
postgresql_1  | LOG:  autovacuum launcher started
redmine_1     | Configuring redmine::database...........................................................
redmine_1     | Could not connect to database server. Aborting...
```

The removal of the images and the and re-pulling from the index did not succeed. 
Also the debug mode did not bring any deeper knowledge. 

At the moment I simply have no explanation for this phenomenon and even the search in the issues has not brought any success. 

Does anyone still have an idea of what it might be?

thx

**Comment by jcormier** [comment]
What does your docker-compose look like?

**Comment by iamwesel** [comment]
You mean the comose.yml? There are no big diffrence between the these an the provided one.

`version: '2'

services:
  postgresql:
    image: sameersbn/postgresql:9.6-4
    environment:
    - DB_USER=redmine
    - DB_PASS=redmineDBpw
    - DB_NAME=redmine_production
    volumes:
    - /srv/docker/redmine/postgresql:/var/lib/postgresql
    restart: always

  redmine:
    image: sameersbn/redmine:3.4.6
    depends_on:
    - postgresql
    environment:
    - TZ=Asia/Kolkata
    - http_proxy=http://10.101.1.127:8080/
    - https_proxy=https://10.101.1.127:8080/
    - no_proxy=localhost,10.4.33.160,127.0.0.0/8,::1

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=redmine
    - DB_PASS=redmineDBpw
    - DB_NAME=redmine_production

    - REDMINE_PORT=10083
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=true
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=domain.it
    - SMTP_HOST=10.10.10.10
    - SMTP_PORT=25
    #- SMTP_USER=projekt
    #- SMTP_PASS=exchangepw
    - SMTP_STARTTLS=false
    #- SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=true
    - IMAP_HOST=10.10.10.10
    - IMAP_PORT=993
    - IMAP_USER=projekt
    - IMAP_PASS=exchangepw
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    ports:
    - "80:80"
    volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
    - /srv/docker/redmine/logs_redmine:/var/log/redmine
    restart: always
    depends_on:
      - postgresql
`

**Comment by jcormier** [comment]
Using the compose file from the 3.4.6 tag works fine for me so your problem is something beyond the default configuration.
https://github.com/sameersbn/docker-redmine/blob/3.4.6/docker-compose.yml 

From the redmine container you should be able to ping the postgresql container:
```
$ docker-compose exec redmine ping postgresql
PING postgresql (172.22.0.2) 56(84) bytes of data.
64 bytes from dockerredmine_postgresql_1.dockerredmine_default (172.22.0.2): icmp_seq=1 ttl=64 time=0.037 ms
64 bytes from dockerredmine_postgresql_1.dockerredmine_default (172.22.0.2): icmp_seq=2 ttl=64 time=0.076 ms
```

Try downloading the above compose file and starting up a empty redmine instance.  Change the volumes to somewhere else.  And see if it starts correctly, if not then theres something wrong with your docker installation.
