### ISSUE TITLE
Add  Icon to Redmine

### ISSUE THREAD

**Issue by koren85** [sameersbn/docker-redmine#388]
Hello!

How can I add custom icons in Redmine if they are located docker-image-name: / home / redmine / redmine / public / images /?
Is this correct and can this directory be rendered as a separate volume?
Copying every time after launching an image is a bit tedious, even if it is a script.

**Comment by jcormier** [comment]
Is that not covered by making a theme?

Regardless you can volume mount images if you want.  For example to specify a custom favicon.ico.

```
    volumes:
    - ./config/favicon-internal.ico:/home/redmine/redmine/public/favicon.ico
```

**Comment by koren85** [comment]
This causes a nginx error.
--volume = / srv / docker / redmine / icons: / home / redmine / redmine / public /: ro \

nginx not starting

**Comment by jcormier** [comment]
You'll need to post the nginx logs from /var/log/redmine inside the container.
