### ISSUE TITLE
unicorn version mismatch

### ISSUE THREAD

**Issue by 16dyui** [sameersbn/docker-redmine#392]
Since the unicorn version is not specified, 5.5.0 is automatically selected.
So I think remine does not go up I need to specify an older version of unicorn.

**Comment by jcormier** [comment]
Looks like there was a bug introduced in 5.5.0
https://bogomips.org/unicorn-public/20190307022859.mxz7m3mbspujo4c2@dcvr/

I tested his patched version and it works.
```
Set unicorn version in Gemfile
gem "unicorn", "~> 5.5.0.1.g6836"
And ran @bundle update unicorn
```
