### ISSUE TITLE
 Service 'redmine' failed to build

### ISSUE THREAD

**Issue by vilyansky** [sameersbn/docker-redmine#393]
I am trying to build docker-compose-mysql.yml
Ubuntu 18.04
Docker version 18.09.3, build 774a1f4

Step 11/20 : COPY assets/build/ ${REDMINE_BUILD_ASSETS_DIR}/
ERROR: Service 'redmine' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder857051654/assets/build: no such file or directory

**Comment by jcormier** [comment]
Sounds like you either found a docker bug or something is misconfigured on your system.  You may have to ask the docker folks for help, as I'm not an expert in the internals of docker.

I'm running ubuntu 18.04 and  Docker version 18.09.2, build 6247962.  And do have any issues.
