### ISSUE TITLE
An error occurred while sending mail

### ISSUE THREAD

**Issue by vilyansky** [sameersbn/docker-redmine#395]
Gmail SMTP setting is not working:

  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: 'smtp.gmail.com'
      port: 587
      domain: 'smtp.gmail.com'
      authentication: :plain
      user_name: 'superuser@gmail.com'
      password: 'superpassword'
      tls: true

An error occurred while sending mail (SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol)

It is no way to unset 'tls' parameter, like in this example configuration - http://www.redmine.org/projects/redmine/wiki/EmailConfiguration#GMail-Google-Apps

**Comment by jcormier** [comment]
What environment settings are you giving to the docker?  My settings below work for gmail.

```
    - SMTP_ENABLED=true
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=criticallink.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=<user@criticallink.com>
    - SMTP_PASS=<pass>
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login
    
    - IMAP_ENABLED=true
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=<user@criticallink.com>
    - IMAP_PASS=<pass>
    - IMAP_SSL=true
    # Poll every 1 minute range: (1 - 60)
    - IMAP_INTERVAL=1
```

**Comment by jcormier** [comment]
Reopen if you still need help
