### ISSUE TITLE
Error 404: The page you were trying to access doesn't exist or has been removed.

### ISSUE THREAD

**Issue by Joshuapaul** [sameersbn/docker-redmine#398]
I have upgraded from 3.4.7-1 to 4.0.3-1 and everything works well except users page. when i try to edit user getting 404 error with below error message. could you please help me to solve this.

"The page you were trying to access doesn't exist or has been removed."

**Comment by Joshuapaul** [comment]
Missing template, responding with 404: Missing partial users/_user_color_form with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}. Searched in:
  * "/home/redmine/redmine/plugins/redmineup_tags/app/views"
  * "/home/redmine/redmine/plugins/redmine_work_time/app/views"
  * "/home/redmine/redmine/plugins/redmine_percent_done/app/views"
  * "/home/redmine/redmine/plugins/redmine_mentions/app/views"
  * "/home/redmine/redmine/plugins/redmine_hearts/app/views"
  * "/home/redmine/redmine/plugins/redmine_checklists/app/views"
  * "/home/redmine/redmine/plugins/redmine_agile/app/views"
  * "/home/redmine/redmine/plugins/easy_wbs/app/views"
  * "/home/redmine/redmine/plugins/easy_mindmup/app/views"
  * "/home/redmine/redmine/app/views"
  * "/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.3.00/app/views"

  Rendering common/error.html.erb within layouts/base
  Rendered common/error.html.erb within layouts/base (0.5ms)
  Rendered plugins/redmineup_tags/app/views/tags/_additional_assets.html.erb (0.5ms)
  Rendered plugins/redmineup_tags/app/views/tags/_select2_transformation_rules.html.erb (0.1ms)
Completed 404 Not Found in 205ms (Views: 13.4ms | ActiveRecord: 17.9ms)

**Comment by jcormier** [comment]
This is likely a redmine plugin issue with the newer version of redmine.  When upgrading redmine versions, make sure the new version is supported by all your plugins.

https://www.redmineup.com/questions/216-agile-plugin-not-working

**Comment by Joshuapaul** [comment]
yes, you are right. it was caused by agile plugin. everything normal after agile plugin removed. thank you.
