### ISSUE TITLE
How apply patch to Redmine

### ISSUE THREAD

**Issue by koren85** [sameersbn/docker-redmine#405]
Hello!
I,m interested in the possibility of using * .patch files to expand the capabilities of Redmine. How can i do this? Can you give an example of applying patch?

**Comment by jcormier** [comment]
I can give a brief explanation of how you might do this but I don't have anything to provide as an example.

- You can add a custom entrypoint.custom.sh in your hosts redmine data directory. Which will get run on the docker startup.
https://github.com/sameersbn/docker-redmine/blob/888b5c7f94a83c39f45ff42b7a71166d6f3cf24c/entrypoint.sh#L23
- The script will need to apply the patch using the patch command tool. 
https://www.thegeekstuff.com/2014/12/patch-command-examples/
