### ISSUE TITLE
Working Plugin recommendations for the latest Docker version?

### ISSUE THREAD

**Issue by gerroon** [sameersbn/docker-redmine#407]
HI

I have been trying to install pluins from the Redmine plugins site but man I am having so much hard time with this, because whatever I try ends up borking the container with gem fails etc. So I am guessing that I am constantly hitting plugins that are not meant to be for v4.

I am wondering if we can make a good listing of working plugins for v4 under this topic.  So that we save time not waste time with trying to install unintallable plugins.

thanks

**Comment by Bodge-IT** [comment]
Plugin list and lack of internal install/update mechanism for plugins is always a big let down in Redmine, for me.  
To help you with your list: I can vouch for the [RedmineUP plugins](https://www.redmineup.com/pages/plugins).  They're useful, always ready for new versions and have great support.

**Comment by jcormier** [comment]
>  To help you with your list: I can vouch for the [RedmineUP plugins](https://www.redmineup.com/pages/plugins). They're useful, always ready for new versions and have great support.

I'll second the RedmineUP plugins.  I'm still running Redmine 3.3 at work due to a lack of time to upgrade.  So my redmine plugin list is not up to date so not sure if sharing it would help.  But I will definitely have to generate a list when we do.

**Comment by gerroon** [comment]
@jcormier  that would be great.

I will take a look at the RedmineUp site.

thanks

**Comment by jcormier** [comment]
[DOWNLOAD_LOG.txt](https://github.com/sameersbn/docker-redmine/files/3773081/DOWNLOAD_LOG.txt)

Here is my list for redmine 3.3 in case it helps.
