### ISSUE TITLE
Error start up on Openshift 4.1

### ISSUE THREAD

**Issue by jerryhan77** [sameersbn/docker-redmine#408]
Hi,

I used to run sameersbn/redmine on Openshift 3.X without any issue.

But when i deploy on a new Openshift 4.1 cluster. The pod could not startup and got following log:
```
Initializing logdir...
Initializing datadir...
Generating OpenSSH client keys...
sudo: unable to send audit message: Operation not permitted
/etc/docker-redmine/runtime/functions: line 48:    46 Segmentation fault      sudo -HEu ${REDMINE_USER} "$@"
```
The deploy config are same. I also try different version of redmine images with no lucky.

Thanks

**Comment by jcormier** [comment]
I'm not familiar with Openshift.  And I'm not sure how the host system can cause sudo to fail within the container :(

Seems like this might be an openshift bug.

**Comment by frank-dspeed** [comment]
its not a bug its expected behavior of openshift openshift does not support root containers! At Last by default.

```
OpenShift is Red Hat's container platform, built on Kubernetes, Red Hat Enterprise Linux, and OCI containers, and it has a great security feature: By default, no containers are allowed to run as root. An admin can override this, otherwise all user containers run without ever being root
```

**Comment by h4wkmoon** [comment]
Hi, 
I know the issue is long closed.

Root containers can be allowed.

The error message is still there : 
> sudo: unable to send audit message: Operation not permitted

**Comment by jcormier** [comment]
You could set DEBUG=true in the environment variables to see what command is causing the failure.  Then you could try opening a shell in the container and poke around to see why the command fails.
