### ISSUE TITLE
Bad Gateway 502 error - nginx

### ISSUE THREAD

**Issue by graygray** [sameersbn/docker-redmine#418]
Hi, good work here, but here are the issue I encounter;

Using mysql yml file (master/docker-compose-mysql.yml) to run will cause this issue :
step:
1. docker-compose up;
2. browse to http://localhost:10083/

but same operations & step is all fine by using postgres yml file (master/docker-compose.yml)

**Comment by jcormier** [comment]
@graygray Thanks for reporting this.  However please attach the full output of docker-compose up.  Without that, I've no way of knowing whats happening.

**Comment by graygray** [comment]
@jcormier, please have a look:

this log result Bad Gateway 502 error use mysql
=========================================================
$ docker-compose -f docker-compose-mysql.yml up
Creating network "docker_default" with the default driver
Creating docker_mysql_1 ... done
Creating docker_redmine_1 ... done
Attaching to docker_mysql_1, docker_redmine_1
mysql_1    | Creating database "redmine_production"...
mysql_1    | Granting access to database "redmine_production" for user "redmine"...
redmine_1  | Initializing logdir...
redmine_1  | Initializing datadir...
redmine_1  | Symlinking dotfiles...
redmine_1  | Installing configuration templates...
redmine_1  | Configuring redmine...
mysql_1    | 2020-03-26T16:38:21.765695Z mysqld_safe Logging to syslog.
mysql_1    | 2020-03-26T16:38:21.784499Z mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
redmine_1  | Configuring redmine::database....
redmine_1  | Configuring redmine::unicorn...
redmine_1  | Configuring redmine::secret_token...
redmine_1  | Generating a session token...
redmine_1  | Note:
redmine_1  |   All old sessions will become invalid.
redmine_1  |   Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
redmine_1  |   **SHOULD** be defined if you have a load-balancing Redmine cluster.
redmine_1  | Configuring redmine::max_concurrent_ajax_uploads...
redmine_1  | Configuring redmine::sudo_mode...
redmine_1  | Configuring redmine::autologin_cookie...
redmine_1  | Configuring redmine::backups...
redmine_1  | Configuring nginx...
redmine_1  | Configuring nginx::redmine...
redmine_1  | Installing plugins...
redmine_1  | Installing themes...
redmine_1  | 2020-03-26 22:08:23,028 CRIT Supervisor running as root (no user in config file)
redmine_1  | 2020-03-26 22:08:23,029 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
redmine_1  | 2020-03-26 22:08:23,029 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
redmine_1  | 2020-03-26 22:08:23,029 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
redmine_1  | 2020-03-26 22:08:23,038 INFO RPC interface 'supervisor' initialized
redmine_1  | 2020-03-26 22:08:23,038 INFO supervisord started with pid 1
redmine_1  | 2020-03-26 22:08:24,043 INFO spawned: 'unicorn' with pid 226
redmine_1  | 2020-03-26 22:08:24,047 INFO spawned: 'cron' with pid 227
redmine_1  | 2020-03-26 22:08:24,051 INFO spawned: 'nginx' with pid 228
redmine_1  | 2020-03-26 22:08:25,664 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2020-03-26 22:08:25,664 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2020-03-26 22:08:25,665 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2020-03-26 22:08:27,695 INFO exited: unicorn (exit status 1; not expected)
redmine_1  | 2020-03-26 22:08:28,699 INFO spawned: 'unicorn' with pid 233
redmine_1  | 2020-03-26 22:08:30,210 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2020-03-26 22:08:32,058 INFO exited: unicorn (exit status 1; not expected)
redmine_1  | 2020-03-26 22:08:33,061 INFO spawned: 'unicorn' with pid 237
redmine_1  | 2020-03-26 22:08:34,577 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2020-03-26 22:08:37,210 INFO exited: unicorn (exit status 1; not expected)
redmine_1  | 2020-03-26 22:08:38,213 INFO spawned: 'unicorn' with pid 241
redmine_1  | 2020-03-26 22:08:39,743 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2020-03-26 22:08:42,575 INFO exited: unicorn (exit status 1; not expected)
redmine_1  | 2020-03-26 22:08:43,580 INFO spawned: 'unicorn' with pid 245
redmine_1  | 2020-03-26 22:08:45,110 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2020-03-26 22:08:47,106 INFO exited: unicorn (exit status 1; not expected)
redmine_1  | 2020-03-26 22:08:48,111 INFO spawned: 'unicorn' with pid 249
redmine_1  | 2020-03-26 22:08:49,700 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2020-03-26 22:08:51,657 INFO exited: unicorn (exit status 1; not expected)
redmine_1  | 2020-03-26 22:08:52,659 INFO spawned: 'unicorn' with pid 253
^CGracefully stopping... (press Ctrl+C again to force)
Stopping docker_redmine_1 ... done
Stopping docker_mysql_1   ... done


this log is work fine use postgres
=========================================================
$ docker-compose -f docker-compose-postgres.yml up
WARNING: Found orphan containers (docker_mysql_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Pulling postgresql (sameersbn/postgresql:9.6-4)...
9.6-4: Pulling from sameersbn/postgresql
6b98dfc16071: Already exists
4001a1209541: Already exists
6319fc68c576: Already exists
b24603670dc3: Already exists
97f170c87c6f: Already exists
02befcbfa4bc: Pull complete
703f657e352c: Pull complete
d5bfe11f5126: Pull complete
cfbe776bd60f: Pull complete
cc092b9fffcf: Pull complete
f5d746359f3e: Pull complete
Digest: sha256:518664a770e57fb023fb5cc5c3b3e492802f898d32f226481a1bf2c3d6ad4a20
Status: Downloaded newer image for sameersbn/postgresql:9.6-4
Creating docker_postgresql_1 ... done
Recreating docker_redmine_1  ... done
Attaching to docker_postgresql_1, docker_redmine_1
postgresql_1  | Initializing datadir...
postgresql_1  | Initializing certdir...
postgresql_1  | Initializing logdir...
postgresql_1  | Initializing rundir...
postgresql_1  | Setting resolv.conf ACLs...
redmine_1     | Initializing logdir...
redmine_1     | Initializing datadir...
redmine_1     | Symlinking dotfiles...
redmine_1     | Installing configuration templates...
redmine_1     | Configuring redmine...
postgresql_1  | Creating database user: redmine
postgresql_1  | Creating database: redmine_production...
postgresql_1  | ‣ Granting access to redmine user...
postgresql_1  | Starting PostgreSQL 9.6...
postgresql_1  | LOG:  database system was shut down at 2020-03-26 16:43:32 UTC
postgresql_1  | LOG:  MultiXact member wraparound protections are now enabled
postgresql_1  | LOG:  database system is ready to accept connections
postgresql_1  | LOG:  autovacuum launcher started
redmine_1     | Configuring redmine::database...
redmine_1     | Configuring redmine::unicorn...
redmine_1     | Configuring redmine::secret_token...
redmine_1     | Generating a session token...
redmine_1     | Note:
redmine_1     |   All old sessions will become invalid.
redmine_1     |   Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
redmine_1     |   **SHOULD** be defined if you have a load-balancing Redmine cluster.
redmine_1     | Configuring redmine::max_concurrent_ajax_uploads...
redmine_1     | Configuring redmine::sudo_mode...
redmine_1     | Configuring redmine::autologin_cookie...
redmine_1     | Configuring redmine::backups...
redmine_1     | Configuring nginx...
redmine_1     | Configuring nginx::redmine...
redmine_1     | Installing plugins...
redmine_1     | Installing themes...
redmine_1     | 2020-03-26 22:13:35,591 CRIT Supervisor running as root (no user in config file)
redmine_1     | 2020-03-26 22:13:35,591 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
redmine_1     | 2020-03-26 22:13:35,592 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
redmine_1     | 2020-03-26 22:13:35,592 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
redmine_1     | 2020-03-26 22:13:35,600 INFO RPC interface 'supervisor' initialized
redmine_1     | 2020-03-26 22:13:35,601 INFO supervisord started with pid 1
redmine_1     | 2020-03-26 22:13:36,606 INFO spawned: 'unicorn' with pid 228
redmine_1     | 2020-03-26 22:13:36,611 INFO spawned: 'cron' with pid 229
redmine_1     | 2020-03-26 22:13:36,619 INFO spawned: 'nginx' with pid 230
redmine_1     | 2020-03-26 22:13:38,187 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1     | 2020-03-26 22:13:38,187 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1     | 2020-03-26 22:13:38,188 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
^CGracefully stopping... (press Ctrl+C again to force)
Stopping docker_redmine_1    ... done
Stopping docker_postgresql_1 ... done

**Comment by jcormier** [comment]
> redmine_1 | 2020-03-26 22:08:32,058 INFO exited: unicorn (exit status 1; not expected)
redmine_1 | 2020-03-26 22:08:33,061 INFO spawned: 'unicorn' with pid 237

Okay so unicorn is failing to load.  

Assuming you are just testing things.  IE: Don't delete your real data.  I would run `docker-compose  -f docker-compose-mysql.yml down` and delete /srv/docker/redmine/redmine folder and try again.

**Comment by graygray** [comment]
@jcormier , u are expert!
following steps resolve this issue.
but what's the root cause? ( postgres is fine but not mysql ...)

$ pwd
/srv/docker/redmine
$ sudo rm -r redmine/
$ ls
mysql  postgresql

$ docker-compose -f docker-compose-mysql.yml up
Creating network "docker_default" with the default driver
Pulling mysql (sameersbn/mysql:5.7.22-1)...
5.7.22-1: Pulling from sameersbn/mysql
6b98dfc16071: Already exists
4001a1209541: Already exists
6319fc68c576: Already exists
b24603670dc3: Already exists
97f170c87c6f: Already exists
5afb5bb61043: Pull complete
580763305454: Pull complete
Digest: sha256:8d30a2a778c6ac8df2881ccdd635bba5969b42f806fae150e23043687536755f
Status: Downloaded newer image for sameersbn/mysql:5.7.22-1
Creating docker_mysql_1 ... done
Creating docker_redmine_1 ... done
Attaching to docker_mysql_1, docker_redmine_1
redmine_1  | Initializing logdir...
redmine_1  | Initializing datadir...
redmine_1  | Generating OpenSSH client keys...
redmine_1  | Symlinking dotfiles...
redmine_1  | Installing configuration templates...
redmine_1  | Configuring redmine...
mysql_1    | Creating database "redmine_production"...
mysql_1    | Granting access to database "redmine_production" for user "redmine"...
mysql_1    | 2020-03-27T02:29:07.104533Z mysqld_safe Logging to syslog.
mysql_1    | 2020-03-27T02:29:07.138958Z mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
redmine_1  | Configuring redmine::database.....
redmine_1  | Configuring redmine::unicorn...
redmine_1  | Configuring redmine::secret_token...
redmine_1  | Generating a session token...
redmine_1  | Note:
redmine_1  |   All old sessions will become invalid.
redmine_1  |   Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
redmine_1  |   **SHOULD** be defined if you have a load-balancing Redmine cluster.
redmine_1  | Configuring redmine::max_concurrent_ajax_uploads...
redmine_1  | Configuring redmine::sudo_mode...
redmine_1  | Configuring redmine::autologin_cookie...
redmine_1  | Configuring redmine::backups...
redmine_1  | Configuring nginx...
redmine_1  | Configuring nginx::redmine...
redmine_1  | New redmine version. Clearing cache
redmine_1  | Migrating database. Please be patient, this could take a while...
redmine_1  | Database 'redmine_production' already exists
redmine_1  | Installing plugins...
redmine_1  | Installing gems required by plugins...
redmine_1  | [DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path '/home/redmine/redmine/vendor/bundle'`, and stop using this flag
redmine_1  | [DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set without 'development test'`, and stop using this flag
redmine_1  | Migrating plugins. Please be patient, this could take a while...
redmine_1  | Installing themes...
redmine_1  | 2020-03-27 07:59:25,278 CRIT Supervisor running as root (no user in config file)
redmine_1  | 2020-03-27 07:59:25,279 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
redmine_1  | 2020-03-27 07:59:25,279 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
redmine_1  | 2020-03-27 07:59:25,279 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
redmine_1  | 2020-03-27 07:59:25,295 INFO RPC interface 'supervisor' initialized
redmine_1  | 2020-03-27 07:59:25,297 INFO supervisord started with pid 1
redmine_1  | 2020-03-27 07:59:26,302 INFO spawned: 'unicorn' with pid 291
redmine_1  | 2020-03-27 07:59:26,311 INFO spawned: 'cron' with pid 292
redmine_1  | 2020-03-27 07:59:26,325 INFO spawned: 'nginx' with pid 293
redmine_1  | 2020-03-27 07:59:27,779 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2020-03-27 07:59:27,780 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2020-03-27 07:59:27,780 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by jcormier** [comment]
What I expect happened is you brought up the postgres version first so the database was properly set up.  When you tried to bring up the mysql version, the start up code saw that it already setup a database (since we are using the same /srv/docker/redmine path for both) and skipped setting up the database.
