### ISSUE TITLE
Creating a volume for plugins crashes the redmine container

### ISSUE THREAD

**Issue by sgaseretto** [sameersbn/docker-redmine#419]
I want to add a volume for my containers, something like this 
```
   volumes:
    - redmine_data:/home/redmine/data
    - ./redmine-plugins:/home/redmine/redmine/plugins
```
So I can add all my plugins to that folder, then when restarting the container, all my containers could appear installed. But each time I try that, the redmine container crashes. Any idea of how to fix it? Also, I'm working on MacOS

**Comment by jcormier** [comment]
Sorry didn't see this come through email. 

Could you add the log from the docker and clarify container crashes?  Also set DEBUG=true in the environment.

**Comment by jcormier** [comment]
Please reopen if this is still an issue
