### ISSUE TITLE
Installation of easy_wbs plugin

### ISSUE THREAD

**Issue by matzol** [sameersbn/docker-redmine#429]
Hi, 

I'm using the sameersbn/docker-redmine (4.1.1-3) with postgres and I had an issue when installing the plugin with command : 

`docker exec -it redmine redmine-install-plugins
`

`Migrating plugins. Please be patient, this could take a while...
rake aborted!
NoMethodError: undefined method `assets' for #
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/railtie/configuration.rb:97:in `method_missing'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:20:in `'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:9:in `'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:8:in `'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `require_relative'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `'
/var/lib/gems/2.4.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require'
/var/lib/gems/2.4.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
/var/lib/gems/2.4.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
/var/lib/gems/2.4.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
/var/lib/gems/2.4.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
/var/lib/gems/2.4.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
/var/lib/gems/2.4.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
/home/redmine/redmine/config/application.rb:18:in `'
/home/redmine/redmine/Rakefile:5:in `require'
/home/redmine/redmine/Rakefile:5:in `'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `'
(See full trace by running task with --trace)

Desired behavior:
no error ! ;)`

The support of easyredmine helped me, please check their response : 

> I've investigated the issue. I've installed this specific dockerized redmine (with postgres) and tried to install plugins there (before that I've rechecked that on regular redmine there is no such problem).
> 
> I was able to reproduce the problem, found out it's source and fix it (but you will need to reapply the fix every time you rerun the container).
>  
> 
> So, I've found out that
> 
> 1) there were some needed gems removed from Gemfile. I've added them to plugin's gemfile (it was easier).
> 
> I've edited file easy_midmup/Gemfile and added the next lines there:
> 
> # Use SCSS for stylesheets
> gem 'sass-rails', '~> 5.0'
> 
> # Use Uglifier as compressor for JavaScript assets
> gem 'uglifier', '>= 2.7.2'
> 
> # Use jquery as the JavaScript library
> gem 'jquery-rails'
> 
> 2) After that I've found out that there was very important line commented in one redmine file. I've found and uncommented it:
> 
> sudo docker exec -it redmine bash
> 
> vi config/application.rb
> 
> uncomment the line
> 
> # require 'sprockets/railtie'
> 
> 3) After that I've found our that one important package was not installed in the system. To be able to install it I had to run the next command
> 
> apt update & apt upgrade
> 
> apt-get install nodejs
> 
> 4) After that I've reinstalled plugins without restarting the container with the command 
> 
>  sudo docker exec -it redmine redmine-install-plugins
> 
> And plugins were installed successfully.
> 
> So there is nothing in our plugins that prevents the installation (gems that I've added to plugin's gemfile should be initially presented in redmine's gemfile). The problem is in dockerized redmine itself. For some reasons the author of the docker decided to remove this parts from the container. You may contact him and suggest him to add these changes to his docker file.

**Comment by jcormier** [comment]
Thanks I'm a bit busy this week but I'll see if I can find time to look into this.

**Comment by jcormier** [comment]
The problem appears to be caused by updates in redmine 4.1.1 and not this docker image. The plugin author needs to update their plugin to support redmine 4.1.1

```
 $ cd /tmp
 $ wget "http://www.redmine.org/releases/redmine-4.1.1.tar.gz" -O /tmp/redmine-4.1.1.tar.gz
 $ tar xzf redmine-4.1.1.tar.gz
 $ grep -R sprock redmine-4.1.1
redmine-4.1.1/doc/CHANGELOG:* Defect #32839: Redmine 4.1 installation fails due to an attempt to install sprockets 4.0.0 if bundler prior to 1.15.2 is used on Ruby prior to 2.5
redmine-4.1.1/doc/CHANGELOG:* Defect #32223: Disable sprockets to avoid Sprockets::Railtie::ManifestNeededError raised by sprockets 4.0.0
redmine-4.1.1/doc/CHANGELOG:* Defect #32300: Don't use sprockets 4.0.0 in order to avoid Sprockets::Railtie::ManifestNeededError
redmine-4.1.1/Gemfile:gem 'sprockets', '~> 3.7.2' if RUBY_VERSION < '2.5'
redmine-4.1.1/config/application.rb:# require 'sprockets/railtie'
 $ grep -R sass-rails redmine-4.1.1
 $ grep -R uglifier redmine-4.1.1
 $ grep -R jquery-rails redmine-4.1.1
redmine-4.1.1/doc/CHANGELOG:* Patch #31205: Replace jquery-rails with vanilla javascript ujs
```

**Comment by matzol** [comment]
Thanks for your response, I will transfer the message !
