### ISSUE TITLE
Installation of stuff to do plugin - exited: unicorn (exit status 1; not expected)

### ISSUE THREAD

**Issue by Sir-Will** [sameersbn/docker-redmine#430]
When I'm trying to install the stuff to do plugin, redmine fails to start up completely and logs
`exited: unicorn (exit status 1; not expected)`.

Is this an issue with the plugin or this docker image?

https://github.com/neffets/redmine-stuff-to-do-plugin

**Comment by jcormier** [comment]
You'll need to look at the server logs to get some more info.  I just added some documentation for how to get access to them.

https://github.com/sameersbn/docker-redmine/commit/758b166d2dd4d54765d4cf562a2f675fa45f6d7f

**Comment by Sir-Will** [comment]
Thank you. The log shows this error.
```
/home/redmine/redmine/plugins/stuff_to_do_plugin/app/models/stuff_to_do_mailer.rb:5:in `<class:StuffToDoMailer>': undefined method `split' for nil:NilClass (NoMethodError)
        from /home/redmine/redmine/plugins/stuff_to_do_plugin/app/models/stuff_to_do_mailer.rb:2:in `<top (required)>'
```

**Comment by jcormier** [comment]
looks like the plugin is failing for calling split on a Nil class object presumably.  I don't know much ruby unfortunately.  Maybe check the plugin source or report this to them?

/home/redmine/redmine/plugins/stuff_to_do_plugin/app/models/stuff_to_do_mailer.rb:2

**Comment by jcormier** [comment]
Closing this for now but reopen if you need to

**Comment by Sir-Will** [comment]
Yea, seems like it can't find the setting. I will ask on the plugins github.
