### ISSUE TITLE
Possibility to develop a redmine theme within the container

### ISSUE THREAD

**Issue by josefglatz** [sameersbn/docker-redmine#440]
Hi,

if you working on a new redmine theme it would be cool to have a rake task for updating a theme.

Is this somehow easy possible? Even without a feature? What is the best practice for that?

https://github.com/sameersbn/docker-redmine/blob/26c03868397fe96d1cc8149a60220f6263003c0d/assets/runtime/functions#L1041

**Comment by jcormier** [comment]
I would try volume mounting an empty directory to the ${REDMINE_INSTALL_DIR}/public/themes/ location.  When the docker starts it should copy the theme to that location and you could update it live from the host machine.

Alternatively, if that causes too many issues you could try to copy your modified files into the docker container. https://docs.docker.com/engine/reference/commandline/cp/

**Comment by jcormier** [comment]
Closing, feel free to reopen if you need more help
