### ISSUE TITLE
Ruby/Rails newer version - security issue

### ISSUE THREAD

**Issue by rzuw273** [sameersbn/docker-redmine#444]
currently running
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.4.10-p364 (2020-03-31) [x86_64-linux-gnu]
  Rails version                  5.2.4.2
need to run newer version of Ruby/Rails - cause of security issues
https://weblog.rubyonrails.org/2020/5/18/Rails-5-2-4-3-and-6-0-3-1-have-been-released/
is it possible to implement soon? Or maybe how to fix it by myself.
Thx.

**Comment by jcormier** [comment]
Redmine is specifically requesting rails 5.2.4.2.  So I would prefer to wait for a redmine update to avoid breaking things.

```
 $ grep rails redmine-4.1.1/Gemfile
gem 'rails', '5.2.4.2'
```
