### ISSUE TITLE
Tried to upgrade to 4.1.1-8 and fails with errors

### ISSUE THREAD

**Issue by Bodge-IT** [sameersbn/docker-redmine#446]
Trying to run the container I get an error about not being able to find Yard gem and fails.

If I try to go back to 4.1.1-1, I get:
```
Installing mysql2 0.5.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.4.0/gems/mysql2-0.5.3/ext/mysql2
/usr/bin/ruby2.4 -r ./siteconf20201027-995-f0tinz.rb extconf.rb
checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for rb_wait_for_single_fd()... yes
checking for -lmysqlclient... no
-----
mysql client is missing. You may need to 'sudo apt-get install libmariadb-dev', 'sudo apt-get install
libmysqlclient-dev' or 'sudo yum install mysql-devel', and try again.
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```
I'm running Coreos 2303.4.0 so can't easily install from apt, nor should I have to, the 4.1.1-1 image worked before.
Also not sure why bundle can't find yard?
No plugins installed at this point.
Not using sameersbn mysql.

Any help would be appreciated. Currently the container is up and docker logs show running but site is 502.

**Comment by Bodge-IT** [comment]
hah just noticed #349 this is my exact problem.  But 4.1.1-1 is was working

**Comment by jcormier** [comment]
I would try to bring down the container and manually delete the temp folder in the data volume mount location.  To see if that allows bundle to find things?

**Comment by Bodge-IT** [comment]
I see this in the log:
```
cp: cannot overwrite non-directory '/home/redmine/data/tmp/bundle' with directory '/home/redmine/redmine/vendor/bund
le'
```

**Comment by Bodge-IT** [comment]
Same.  There was initially an issue where sym links stop new bundle dir and lock file but after I delete those, bundle and lock appear.
myslq2 is there with proper sub dirs and content but get same extconf.rb fail error and bundler stops.

**Comment by Bodge-IT** [comment]
I see this:
```
"gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.4.0 -I/usr/include/ruby-2.4.0/ruby/backward -I/usr/include/ruby-2.4.0 -I. -I/usr/local/include -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC conftest.c  -L. -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib -L/usr/local/lib/mysql -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -L/build/ruby2.4-IB2yVO/ruby2.4-2.4.10/debian/lib -fstack-protector -rdynamic -Wl,-export-dynamic     -lruby-2.4 -ltrue  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
/usr/bin/ld: cannot find -ltrue
collect2: error: ld returned 1 exit status
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10:
11:   return 0;
12: }
13:
14: int t(void) { ; return 0; }
/* end */

--------------------
```
/var/lib/gems/2.4.0/extensions/x86_64-linux/2.4.0/mysql2-0.5.3/mkmf.log file

**Comment by Bodge-IT** [comment]
Sry, forgot about this post and can't remember how I got it working.  I think @jcormier 's suggestion around the tmp folder was a big part of it though.
