### ISSUE TITLE
postgresql_1 failed

### ISSUE THREAD

**Issue by BharathS11** [sameersbn/docker-redmine#449]
I'm trying to run redmine on raspberry pi4, running ubuntu 20.04 server. I was able to successfully build an image using your Dockerfile, made some modifications on the way had to use ruby 2.3 for xenial. Couldn't build for bionic or focal. 
But that aside, when I try to run the built image it fails with this error
```

Starting docker-redmine_postgresql_1 ... done
Starting docker-redmine_redmine_1    ... done
Attaching to docker-redmine_postgresql_1, docker-redmine_redmine_1
postgresql_1  | standard_init_linux.go:211: exec user process caused "exec format error"
docker-redmine_postgresql_1 exited with code 1
redmine_1     | Initializing logdir...
redmine_1     | Initializing datadir...
redmine_1     | Symlinking dotfiles...
redmine_1     | Installing configuration templates...
redmine_1     | Configuring redmine...
redmine_1     | Configuring redmine::database...........................................................
redmine_1     | Could not connect to database server. Aborting...
docker-redmine_redmine_1 exited with code 1
```

Any pointers on what is causing this or a fix is appreciated. Thanks

**Comment by jcormier** [comment]
I'm not sure I understand.  Are you modifying the docker image?  Did you modify the Postgres image as well?

Does the published, prebuilt images work?
