### ISSUE TITLE
Local Git repository shows "404 The entry or revision was not found in the repository" error.

### ISSUE THREAD

**Issue by Aleksei-Badyaev** [sameersbn/docker-redmine#453]
The repository to the server is working fine, but when I connect it as a project repository, I see a message (see the title). Redmine support recommends changing the "scm_git_command" in "configuration.yml" file, but this cannot be done by the container settings. I took the redmine settings folder out of the container and mounted it in the container. However, after restarting the container, all my configuration changes made in the file disappear. What should I do to use the Git repository as a repository for the project?

**Comment by jcormier** [comment]
Aleksei, does scm_git_command just need to be set to something reasonable or would it need to be customized per person?

Do you have a recommendation for what you'd like it set to?

**Comment by Aleksei-Badyaev** [comment]
Hi! Thank you for your quick response! I need to write the value "/usr/bin/git "to the parameter "scm_git_command".

**Comment by jcormier** [comment]
Huh, it seems odd that the default doesn't just work. 

Both the root user and redmine user git commands look at /usr/bin/git
```
root@75e7de661573:/home/redmine/redmine# which git
/usr/bin/git
root@75e7de661573:/home/redmine/redmine# su - redmine
redmine@75e7de661573:~$ which git
/usr/bin/git
```

I suspect the problem lies somewhere else.  Especially considering the git version is correctly reported in the admin info page.

```
SCM:
  Subversion                     1.9.3
  Mercurial                      3.7.3
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.29.0
```

**Comment by jcormier** [comment]
I ran through the git repo setup instructions and was able to make it work. https://www.redmine.org/projects/redmine/wiki/RedmineRepositories#Git-repository

Setup test repo
```
mkdir /srv/docker/redmine/git
cd /srv/docker/redmine/git
git clone --mirror https://github.com/sameersbn/docker-redmine.git
# Make sure permissions are accessible by redmine user, which is user 1000 on my machine
chown 1000:1000 -R .
```

Mount directory in docker as volume to /git
```
 $ tail docker-compose.yml
    ports:
    - "10083:80"
    volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
    - /srv/docker/redmine/redmine-logs:/var/log/redmine
    - /srv/docker/redmine/git:/git
```

Setup new repo
![image](https://user-images.githubusercontent.com/5613721/105877849-68bc3a80-5fce-11eb-95d4-0da814fdbb93.png)
Repo loaded
![image](https://user-images.githubusercontent.com/5613721/105878044-9acd9c80-5fce-11eb-89af-48c9ab6880ac.png)

**Comment by jcormier** [comment]
Note according to this post, https://www.redmine.org/boards/2/topics/41094?r=44138

A 404 error could happen if the git repo is empty as well.

**Comment by Aleksei-Badyaev** [comment]
Thank you for reply!
