### ISSUE TITLE
Cannot Login After install

### ISSUE THREAD

**Issue by grichardomi** [sameersbn/docker-redmine#454]
Tried to login after docker-compose up, using admin / admin. What I'm missing?

**Comment by jcormier** [comment]
admin / admin works for me.

The first login forces you to change passwords, is it possible you changed to password to something else in a previous run.  If you don't remember you can delete the redmine data, only recommended for test servers of course.

```
docker-compose down
sudo rm -rf /srv/docker/redmine/
```
