### ISSUE TITLE
422 Invalid form authenticity token

### ISSUE THREAD

**Issue by fabiopires77** [sameersbn/docker-redmine#455]
My Redmine is giving 422 Invalid form authenticity token error everytime. I'm using Docker. I've disabled HTTPS using REDMINE_HTTPS=false and I've manually setted a token with REDMINE_SECRET_TOKEN and it keeps displaying error 422 everytime I submit a form.

**Comment by jcormier** [comment]
Is this a fresh install?  If not do you get this error when using the example docker-compose?
What version of redmine are you using?
Are you using any plugins?

Are you using REDMINE_RELATIVE_URL_ROOT? #368

**Comment by fabiopires77** [comment]
It's not a fresh install. 

I'm using Redmine 3.3.10 on Docker using a Synology NAS. 

I'm not using REDMINE_RELATIVE_URL_ROOT.

**Comment by jcormier** [comment]
Did this issue crop up suddenly then?  Has anything changed recently?

**Comment by fabiopires77** [comment]
The only thing that changed recently was the HTTPS configuration on the NAS itself, but not on the Redmine / Docker side.

**Comment by fabiopires77** [comment]
I ended up reinstalling it and it's working now.
