### ISSUE TITLE
When accessing any file in DMS it shows 404 the file is not accessible

### ISSUE THREAD

**Issue by ar-sumesh** [sameersbn/docker-redmine#456]
i encounter this problem when i moved dmsf files and postgresql data folder from official redmine docker conatainer to new sameersbn redmine docker container , as i wanted that redmine should start up without the requirement of internet connection for downloading the plugins dependencies every time we start and stop the redmine container that why i done this switch.

**Comment by jcormier** [comment]
I'm not aware of dmsf files.  I'm also not that familiar with how the official redmine docker container is setup.

But in general when you are trying to move database files to a different database of unknown version.  You should back up the database to a .SQL file and then restore it on the new database.

Please provide details on what steps you took to move to this image.  Also a log of the startup messages/errors.

**Comment by ar-sumesh** [comment]
Steps i took :-

- i went through the sameersbn redmine docker-compose file , i found  where should the redmine files , plugins has to be kept like `/home/redmine/data` in container side.
- Also found where to put postgres files like `/var/lib/postgresql/data/` in container side.
- After directing my old redmine files and postgres to these directories in docker-compose file.
- i started the docker containers.
-  i can able to see the files under DMS tab in project section of redmine but not able to download them.
- I am attaching the logs from the part when i clicked on that file to get download:-

> Started GET "/dmsf/files/3/view" for 192.168.208.1 at 2021-02-22 18:11:02 +0530
Processing by DmsfFilesController#view as HTML
  Parameters: {"id"=>"3"}
  Current user: admin (id=1)
Sent file /home/redmine/redmine/files/dmsf/2020/06/file.pptx (0.6ms)
Cannot read file /home/redmine/redmine/files/dmsf/2020/06/file.pptx
  Rendering common/error.html.erb within layouts/base
  Rendered common/error.html.erb within layouts/base (0.7ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (3.5ms)
  Rendered plugins/redmine_wktime/app/views/wkbase/_base_header.html.erb (0.5ms)
  Rendered plugins/redmineup_tags/app/views/tags/_additional_assets.html.erb (0.2ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_sidebar.html.erb (0.0ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_recent_projects.html.erb (1.9ms)
  Rendered plugins/redmine_wktime/app/views/wktime/_attendance_widget.html.erb (0.9ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (1.9ms)
  Rendered plugins/redmineup_tags/app/views/tags/_select2_transformation_rules.html.erb (0.3ms)
  Rendered plugins/redmine_people/app/views/common/_people_select2_data.html.erb (0.2ms)
  Rendered plugins/redmine_people/app/views/common/_layout_bottom.html.erb (0.3ms)
Completed 404 Not Found in 203ms (Views: 103.3ms | ActiveRecord: 60.5ms)
Started GET "/issue_badge" for 192.168.208.1 at 2021-02-22 18:11:02 +0530
Processing by IssueBadgeController#index as /
  Current user: admin (id=1)
Completed 200 OK in 40ms (Views: 0.4ms | ActiveRecord: 13.5ms)


![](https://user-images.githubusercontent.com/59471926/108834025-a2935780-75f3-11eb-9700-7f6ac90abe47.png)

**Comment by jcormier** [comment]
> * i went through the sameersbn redmine docker-compose file , i found  where should the redmine files , plugins has to be kept like `/home/redmine/data` in container side.
> * Also found where to put postgres files like `/var/lib/postgresql/data/` in container side.
> * After directing my old redmine files and postgres to these directories in docker-compose file.

I assume you mean you updated the volume mounts to the location of the old redmine files and postgres.  I sounds like redmine started up and was able to use your postgres database correctly so that's good.  That was not obvious from your first post.

I am not familiar with the dkms plugin, is it this one? https://github.com/danmunn/redmine_dmsf#setup--upgrade

It looks like its trying to open a file here /home/redmine/redmine/files/dmsf/2020/06, does this path exist and what are the permissions?  My guess would be your file permissions don't match the user inside the docker.

```
Sent file /home/redmine/redmine/files/dmsf/2020/06/file.pptx (0.6ms)
Cannot read file /home/redmine/redmine/files/dmsf/2020/06/file.pptx
```

You can change the user id and group id of the user running inside the docker to match the owner of the files on your host system. See https://github.com/sameersbn/docker-redmine#mapping-host-user-and-group

**Comment by ar-sumesh** [comment]
Yes, that dmsf plugin only.

i tried changing the UID and GID to 500 using that environment variable in my docker compose file and i can see that all the directories mounted to docker container has `500:500` permission  on **Host** side but still getting that same error

**Comment by jcormier** [comment]
So looks like the dmsf plugin is looking in the wrong directory.  The attachments file dir is located at /home/redmine/data/files inside the container and not /home/redmine/redmine/files.


```
 $ ag REDMINE_ATTACHMENTS_DIR assets/
assets/runtime/env-defaults
7:REDMINE_ATTACHMENTS_DIR=${REDMINE_ATTACHMENTS_DIR:-$REDMINE_DATA_DIR/files}

assets/runtime/config/redmine/configuration.yml
89:  attachments_storage_path: {{REDMINE_ATTACHMENTS_DIR}}
```

```
 $ docker-compose exec redmine ls -la /home/redmine/data/
total 736
drwxr-xr-x  9 redmine redmine   4096 Sep 30 21:55 .
drwxr-xr-x  6 redmine redmine   4096 Feb 24 17:05 ..
drwxr-xr-x  2 redmine redmine   4096 Feb 25 09:05 backups
drwxr-xr-x  2 redmine redmine   4096 Aug 15  2019 certs
drwxr-xr-x  4 redmine redmine   4096 Aug 16  2016 dotfiles
drwxr-xr-x  8 redmine redmine 716800 Jan  4 11:43 files
-rwxr-xr-x  1 redmine redmine    554 Aug 19  2016 letsencrypt.log
drwxr-xr-x 22 redmine redmine   4096 Sep 30 21:51 plugins
drwxr-xr-x  5 redmine redmine   4096 Jan 12  2013 themes
drwxr-xr-x  5 redmine redmine   4096 Sep 30 21:56 tmp
 13:47:43  jcormier  ⇔  export  docker  …  redmine-docker-cl-internal     master                                                                                                                     1d 1h 43m
 $ docker-compose exec redmine ls -la /home/redmine/redmine/files
total 12
drwxr-xr-x  2 redmine redmine 4096 Oct 10  2016 .
drwxr-xr-x 22 redmine redmine 4096 Feb 24 17:05 ..
-rw-r--r--  1 redmine redmine   36 Oct 10  2016 delete.me
```


Looking at the plugin source, it looks like they may have a dmsf_storage_directory setting which you should check for, as it appears like it may be set incorrectly.

https://github.com/danmunn/redmine_dmsf/blob/635410d62c9d8c868be14a11b4c69cc5ed864f20/app/models/dmsf_file.rb#L76

**Comment by ar-sumesh** [comment]
Thanks , that issue is now solved , i given the `/home/redmine/data/files/dmsf` path in dmsf plugin settings page.

now i am able to download files
