### ISSUE TITLE
Missing 4.1.2 tag in dockerhub

### ISSUE THREAD

**Issue by tecnoprogram-thomas** [sameersbn/docker-redmine#460]
Dear sameersbn,
first of all thanks for the great job!

I noticed that in dockerhub the 4.1.2 tag is missing, while there is the "latest" tag. Was this intended, or just missing? In previous versions each release had a specific tag, so it *may* be a forgetfulness.

Thomas

**Comment by jcormier** [comment]
Hmm your right, the tags got pushed to github but dockerhub isn't picking them up...

**Comment by jcormier** [comment]
@sameersbn can you see why the tag auto build didn't trigger?

**Comment by jcormier** [comment]
The 4.1.2 image hash is https://hub.docker.com/layers/sameersbn/redmine/latest/images/sha256-fa96460978f04e1fb9c6cbb5b7f44df9dde9b1bcc3083240185707ec54b31548?context=explore

**Comment by jcormier** [comment]
A 4.0.8 image was never built.

**Comment by jcormier** [comment]
Hmm I just pushed the 4.2.0 tag and that got built.  So maybe I need to delete and repush the two tags that are missing

**Comment by jcormier** [comment]
Repushed tags and they triggered a build.
