### ISSUE TITLE
Plugin Install Error: Could not find gem 'redmine_crm' in rubygems repository

### ISSUE THREAD

**Issue by Didldu-Florian** [sameersbn/docker-redmine#466]
Hi, first thanks for you great redmine docker.
I like it mor than the default redmine because of the outsourced enironement config.
Unfortunately no Redmine plugins can be installed, because of error:

```
/var/lib/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/resolver.rb:338:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'redmine_crm' in rubygems repository https://rubygems.org/ or installed locally. (Bundler::GemNotFound)
The source does not contain any versions of 'redmine_crm'
```

System Info: Docker Container on QNAP NAS.

Problem effects, when you add unzip a new plugin folder via /home/redmine/redmine/plugins and restart the container to auto install. Same problem also via bundle install.
Anyidea. Did not testet it on windows docker, but via redmine QNAP it seems like to be a bug.
Tested with two different compatible plugins.
Both running via default offical redmine docker image.

Hope for help, many thanks

**Comment by jcormier** [comment]
Hi @Didldu-Florian, plugin installation does work for me and most users.  So the question becomes what is special about how you've set things up or how QNAP is configured.

Can you detail the steps you took to install this?  What plugins did you test?

I don't have a QNAP nas so I'm going to need your help to diagnose this.

**Comment by Didldu-Florian** [comment]
Hi @jcormier, finally it did worked now. It was just a filepermission problem inside docker container.
For other users, just run chmod and change owner to redime plugin directory.
Permissions could be defekt, because of i mapped the folder and paste the plugin via qnap.
May be wget in the folder is here more to prefer.
Finally the plugin installed auto after restart container
