### ISSUE TITLE
Service 'redmine' failed to build : Build failed has appered.

### ISSUE THREAD

**Issue by asyahana** [sameersbn/docker-redmine#469]
Thank you for your help.
I tried to run docker-compose according to the Quick Start guidance, but I got an error like the one in the image.
I tried to create a directory because there are no such files or directory, but the error like the image is still displayed.
Can you tell me if there is any workaround? 

![image](https://user-images.githubusercontent.com/64050777/123390923-6a6a4880-d5d6-11eb-884d-4c071ea20a8e.png)

**Comment by jcormier** [comment]
Note: docker-compose uses the name of the folder where the .yml file is located to name the container. 

Remove "build: ./" from docker-compose.yml

**Comment by asyahana** [comment]
Thanks a lot!!
With your valuable advice, it was solved successfully!
