### ISSUE TITLE
Cannot restore cause of NOT find file or directory.

### ISSUE THREAD

**Issue by asyahana** [sameersbn/docker-redmine#472]
I am verifying the operation of Redmine backup acquisition and restore, but both acquisition and restore fail.
Sorry to trouble you, but I would appreciate your advice on the solution.

[terminal log]
[root@redmine-test ~]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)`
[root@redmine-test docker]# docker-compose up -d --build
Creating memcached         ... done
Creating docker_database_1 ... done
Creating docker_redmine_1  ... done
[root@redmine-test docker]# docker stop docker_redmine_1 && docker rm docker_redmine_1
docker_redmine_1
docker_redmine_1
[root@redmine-test docker]# docker run --name docker_redmine_1 -it --rm sameersbn/redmine:4.2.1-1 app:backup:create
Initializing logdir...
Initializing datadir...
chmod: cannot access '/home/redmine/data': No such file or directory
[root@redmine-test docker]# 

[docker-compose-sample.yml.txt](https://github.com/sameersbn/docker-redmine/files/6838322/docker-compose-sample.yml.txt)

**Comment by jcormier** [comment]
If your using docker-compose, you should stick to `docker-compose` commands so it has access to all the same paths and settings

```
docker-compose up -d --build
docker-compose down
docker-compose run redmine app:backup:create
```

**Comment by asyahana** [comment]
Thanks a lot!!
