### ISSUE TITLE
How to manually fetch emails

### ISSUE THREAD

**Issue by HRIT-Florian** [sameersbn/docker-redmine#476]
Hi, we havet to fetch emails manually, normally in redmine theres a command like:

`rake redmine:email:receive_imap RAILS_ENV="production" host=imap.foo.bar username=redmine@somenet.foo password=xxx move_on_success=read move_on_failure=failed`

but when we run rake inside docker container, in /home/redmine/redmine it says, rake is not installed?

These ist, because we have problems with your build in fetcher, it featch email only once by start container and than not more!
Not sure why. 

Alternate we have tested to use Rufus-Scheduler
https://www.redmine.org/projects/redmine/wiki/redminereceivingemails#Schedule-email-receiving-with-Rufus-Scheduler
But we can not install "gem install rufus-scheduler" in a docker container.
Is there a way, you cann add refus scheduler? Or can you let me know, how to fetch emails manually?
Hope for help, many thanks!

**Comment by jcormier** [comment]
Here is an example of sending a test email.  I think it shows how you would adapt it to manually fetch emails.

`docker-compose exec redmine bundle exec rake redmine:email:test[admin] RAILS_ENV=production`

Note the use of `bundle exec`, you can find info about it here: https://bundler.io/man/bundle-exec.1.html
Note: The bundle exec command needs to be run as the redmine user, which should already be true for the above example.

I haven't had any issue with the CRON scheduled email retrieval but using rufus does seem like a nice alternative.  If you would like to make modifications (like installing gems) on container start, you can create either pre-install.sh/post-install.sh script, located inside the plugins directory.
