### ISSUE TITLE
Cannot remove theme completely

### ISSUE THREAD

**Issue by civita** [sameersbn/docker-redmine#478]
Hi,

I followed the [guide](https://github.com/sameersbn/docker-redmine#installing-themes) to install theme by moving the donwloaded folder into `/srv/docker/redmine/redmine/themes`. It worked and the added theme can be selected in the dropdown menu. However, when I was trying to remove one of the added themes, it still presented in the menu even after I removed the folder in `/srv/docker/redmine/redmine/themes` and restarted the docker. I found that in the container under the path `/home/redmine/redmine/public/themes`, there is a copy of the installed theme, and I have to remove it to uninstall completely. Is this the correct way to remove the theme, or am I missing some steps?

Thanks.

Version: 4.2.2

**Comment by jcormier** [comment]
Make sure when you stop the docker container that you destroy it.

For docker-compose, running `docker-compose down` is enough.  If your running straight docker, you can add `--rm` to the run command so it cleans up when its stopped.  Or run `docker stop redmine && docker rm redmine`

**Comment by civita** [comment]
@jcormier Thanks for the reply! Now I understand how it works.
