### ISSUE TITLE
MySQL SSL connection error: unsupported protocol

### ISSUE THREAD

**Issue by northway** [sameersbn/docker-redmine#479]
Hi!

I wanted to upgrade from version `4.1.1-8` to `4.2.2`.

During the upgrade I got this error message:

```
Migrating database. Please be patient, this could take a while...
SSL connection error: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
Couldn't create 'einfra_redmine' database. Please check your configuration.
rake aborted!
Mysql2::Error::ConnectionError: SSL connection error: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `connect'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `initialize'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_handling.rb:90:in `connection'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/tasks/mysql_database_tasks.rb:6:in `connection'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/tasks/mysql_database_tasks.rb:14:in `create'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/tasks/database_tasks.rb:119:in `create'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/tasks/database_tasks.rb:313:in `each'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```

The database is a MariaDB Galera cluster, with TLS support altough it's not enforced.

All database related settings are in place:

```
DB_ADAPTER: "mysql2"
DB_ENCODING: "utf8"
DB_HOST: "REMOTE HOST"
DB_NAME: "redmine"
DB_USER: "redmine"
DB_PASS: "SECRET"
```

Is there a way to explicitly disable the MySQL adapter's SSL connection?

**Comment by jcormier** [comment]
Is it possible to enable TLSv1.2 in MariaDB?
`ssl_cipher = TLSv1.2`

It seems like the problem stems from debian and thus ubuntu increasing the minimal TLS version for SSL.

The docker could be updated to go back to supporting TLSv1 but there is apparently some big security issues with that.

https://github.com/microsoft/msphpsql/issues/1023#issuecomment-642340422

/etc/ssl/openssl.cnf section [system_default_sect] to
```
[system_default_sect]
MinProtocol = TLSv1.0
CipherString = DEFAULT@SECLEVEL=1
```

Its also made worse by MySQL client v5.7, changed its default to prefer using SSL.  And we are using v5.7.

```
root@fe4934890271:/home/redmine/redmine# mysql -V
mysql  Ver 14.14 Distrib 5.7.35, for Linux (x86_64) using  EditLine wrapper
```

This post implies it might be possible to explicitly disable ssl for MySQL. https://stackoverflow.com/a/60554755/780194

So options in order of best case:
* Update server to support TLSv1.2
* Drop min TLS to V1.0
* Set ssl_mode to disabled

What would you like to try?

**Comment by northway** [comment]
I think I would go the `Set ssl_mode to disabled` option for now.

How can I permanently add the `ssl_mode: disabled` option to `database.yml`, so that would be persistent across the versions?

**Comment by jcormier** [comment]
Would you be willing to add DB_SSL_MODE as an option to the docker image and create a pull request?

This could be done by searching for anywhere DB_NAME is used and seeing if its appropriate to add DB_SSL_MODE

**Comment by jcormier** [comment]
Alternatively a `plugins/post-install.sh` script could be created which changes the database.yml config file on each run, though would require a little bit of `sed` magic.

**Comment by northway** [comment]
> Would you be willing to add DB_SSL_MODE as an option to the docker image and create a pull request?
> 
> This could be done by searching for anywhere DB_NAME is used and seeing if its appropriate to add DB_SSL_MODE

That was my first idea. I'll take look at this.

**Comment by jcormier** [comment]
Sounds good, the default should be preferred as I believe that's what its set to if its not supplied.

The options are as follows. `sslmode: (disable|allow|prefer|require)` though I have not been able to find an official documentation for rails which specifies this...

**Comment by northway** [comment]
I was able create a working version based on what you have linked: https://stackoverflow.com/a/60554755/780194

The correct syntax were: `ssl_mode: (disabled|allow|prefer|require)`

Can you take a look at my commit? https://github.com/northway/docker-redmine/commit/fc8f05c766ac17b95eb0f4f02bb9a1cb43d95e13

If it's okay, I'll create a pull request.

**Comment by jcormier** [comment]
Testing mysql and mariadb failed:

```
docker-compose -f docker-compose-mysql.yml up
...
redmine_1  | Migrating database. Please be patient, this could take a while...
redmine_1  | Unknown MySQL ssl_mode flag: prefer
redmine_1  | no implicit conversion from nil to integer
redmine_1  | Couldn't create 'redmine_production' database. Please check your configuration.
redmine_1  | rake aborted!
redmine_1  | TypeError: no implicit conversion from nil to integer
```

Testing postgres and sqlite3 started up fine though

 $ docker-compose -f docker-compose-sqlite3.yml up
 $ docker-compose -f docker-compose.yml up

**Comment by jcormier** [comment]
Looks like mysql wants preferred instead of prefer...

I tried preferred with postgres and it didn't fail.  But I also tried setting a bad value and it didn't fail either so I'm not sure postgres pays any attention to the ssl-mode...

**Comment by northway** [comment]
> Looks like mysql wants preferred instead of prefer...

So should I change the default value to `preferred`?

**Comment by northway** [comment]
I've changed to the default value to `preferred`, it looks good to me.

https://github.com/northway/docker-redmine/commit/37a1dd1414d7b2e01013c8efc983d53a96f5d7db

**Comment by northway** [comment]
When can we except a new release, which contains this PR?

**Comment by frank-dspeed** [comment]
@northway you can always expect it to land with the next regular redmine version as our release system is at present broken. we are manualy releasing and we got only one member with release access.

**Comment by northway** [comment]
I see, thanks for the update.

**Comment by Bodge-IT** [comment]
Hi was this patch rolled into 4.1.5?
I'm getting the very same issue.

**Comment by jcormier** [comment]
> was this pr rolled into 4.1.5?
It does not look like it.  It was included in 4.2.2-1

I just cherry-picked the changes to 4.1.5-1

**Comment by Bodge-IT** [comment]
Was there anything else I needed to do oother than the new ssl mode setting?
I couldn't get 4.2.2 to work either.

**Comment by jcormier** [comment]
Did you try 4.2.2-1?

**Comment by Bodge-IT** [comment]
> Did you try 4.2.2-1?

No, just 4.2.2
