### ISSUE TITLE
manpages inside the container

### ISSUE THREAD

**Issue by b-a-t** [sameersbn/docker-redmine#48]
With the docker-entry I find it's easy and handy to access container to peek log files and check/tweak some configuration parameters. Sometimes I need to check options or other help information for the installed packages within container. Hence I try to access manpages for that packages within container, but 'man' command isn't available :(

I can imagine, that it's not installed to keep image smaller, but then - the whole bunch of manpages in /usr/share/man/* are actually there, together with /usr/share/doc/*. So, if the priority is saving space, taken by the image its worth deleting content of those directories(together with /etc/alternatives/).

Otherwise, if they are there already it's handy to be able to access those manpages and add 'man-db'  package to the image.

Actually, it's possibly better to add this to the parent image, sameersbn/ubuntu and/or sameersbn/debian, as those alreasy have some manpages.

**Comment by mc0e** [comment]
I don't think you should install user tools.  It's trivial for people to base an image on yours and add stuff if they want it, or to look at the man pages in another environment.
