### ISSUE TITLE
Erroneous standard SSL_..._PATH in the read me

### ISSUE THREAD

**Issue by maneuss** [sameersbn/docker-redmine#485]
Hi,

at first my congrats for your work. i installed the image a few months ago (my first docker instance) and after some adjustments it worked. 
now i wanted to enable ssl support and followed the instructions in the readme file.

the mentioned default data path for redmine.crt, redmine.key, dhparam.pem is NOT /home/redmine/data/certs as written in the readme but /app/setup/certs/ ... as written in the variables description at the end of the readme.

also the code "openssl x509 .... redmine.crt" in step 3 does not wrap when displayed so - on my ipad - the line was cut at "redmine".  as a newcomer i had to find out that the file extension was missing.

now ssl and https works like a charm.

with best regards 

martin

**Comment by jcormier** [comment]
> the mentioned default data path for redmine.crt, redmine.key, dhparam.pem is NOT /home/redmine/data/certs as written in the readme but /app/setup/certs/ ... as written in the variables description at the end of the readme.
I don't follow, there is no /app folder in this container.

There are env variables to change where we look for the SSL certs but the defaults are indeed `/home/redmine/data/certs`
https://github.com/sameersbn/docker-redmine/blob/17c25efb68371aa199b3bd6a93a8a8ce44ed0a61/assets/runtime/env-defaults#L83


> also the code "openssl x509 .... redmine.crt" in step 3 does not wrap when displayed so - on my ipad - the line was cut at "redmine". as a newcomer i had to find out that the file extension was missing.

Your right it doesn't seem to wrap, unfortunately, that is controlled by Github's rendering of .MD files.  Not sure if there's anything I can do about it.

**Comment by maneuss** [comment]
Hi,

primarely i installed the files at the „default“ location „/home/redmine/data/certs“ - didn ´t work. then i explicitedly set all three  SSL_…_PATH variables to „/home/redmine/data/certs“ and it did work. so i tend to disagree: the default values seem not to be the mentioned standards. and when reading the actual readme.md file the default values seem to other values.

<img width="1112" alt="PNG-Bild" src="https://user-images.githubusercontent.com/10476501/140520719-d72bf2a8-15af-4c80-a4e1-ea4c7cbe49c6.png">

**Comment by jcormier** [comment]
The documentation was definitely wrong. Fixed that.

Just to verify, was able to fire up the ssl docker-compose and load redmine just fine.
```
$ sudo mkdir /srv/docker/redmine/redmine/certs
$ sudo cp -v redmine.* dhparam.pem /srv/docker/redmine/redmine/certs/
'redmine.crt' -> '/srv/docker/redmine/redmine/certs/redmine.crt'
'redmine.csr' -> '/srv/docker/redmine/redmine/certs/redmine.csr'
'redmine.key' -> '/srv/docker/redmine/redmine/certs/redmine.key'
'dhparam.pem' -> '/srv/docker/redmine/redmine/certs/dhparam.pem'
$ docker-compose -f docker-compose-ssl.yml up
...
redmine_1     | Configuring nginx::redmine::ssl...
redmine_1     | Configuring nginx::redmine::hsts...
...
```

And loaded fine at https://localhost:10445/
