### ISSUE TITLE
"bundle install" broken for all three databases

### ISSUE THREAD

**Issue by wunditta** [sameersbn/docker-redmine#490]
I am using latest (4.3.2) together with sameersbn/mysql:5.7.26-0 on a Synology. In principle this works. However, in order to install plugins I need to run "bundle install". And this does not work.

I am not an expert, so whatever I tried was probably meaningless from the beginning, but I tried a lot (I even tried to use the Gemfiles from the official Redmine docker image, as with that image no errors occur (but I could not get that container to run with HTTPS, which I need as I this is the only means to get rid of the "Invalid form authenticity token." error, which occurred after reinstalling this container several times... well it's a long story to be told another time ;-) )).

So, after failing for several days I kindly ask for help on this. I would really, really... really appreciate help on this...

After resetting the container (and deleting tmp folder), without any plugin installed, when I run "bundle install" I get the attached output.

[bundleinstallout.txt](https://github.com/sameersbn/docker-redmine/files/8082052/bundleinstallout.txt)

**Comment by jcormier** [comment]
Did you follow the instructions here: https://github.com/sameersbn/docker-redmine#installing-plugins

There should be no need to manually run bundle install, this image runs it automatically on startup.  I've had no issues with this with any plugins I've tried except for the Easy Redmine plugins. 

> Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.

You've executed bundler incorrectly, it has to be run as the redmine user.  But again this shouldn't be required.
Example of running bundle as correct user: https://github.com/sameersbn/docker-redmine#rake-tasks

If automatic plugin installation doesn't work, please provide the full startup log and the plugins that are failing.

**Comment by jcormier** [comment]
Example of a post-install.sh script which calls db:migrate to work around peculiarities with easy_gantt.

```
#/bin/bash

# Required for easy_gantt plugin
cd /home/redmine/redmine && sudo -HEu redmine bundle exec rake db:migrate       RAILS_ENV=production
```

**Comment by wunditta** [comment]
Well, the errors occur even without installing a plugin. But of course the (first and only) plugin I tried to install was EasyGantt from Easy Redmine... I did not know that their plugins have issues.

However, yes I followed the instructions. So, on the Synology I created a dir "plugins" within the data folder, copied the correct plugin version (for Redmine 4.x) there (unzipped). Well, I left out everything I could not understand (like pre/post-install.sh whatever), but I do not think that was relevant. I also followed EasyRedmine's instruction as given here: [https://www.easyredmine.com/redmine-gantt-plugin#install](url). But "bundle install" fails for me.
I admit I always did this as "root", because I did not know how to change this. When creating a bash session from Synology this is automatically as root.

Ouch... I just tried to run
`docker exec -it redmine sudo -u redmine -H bundle install`
in an SSH session on the Synology... and it seemed to work without errors... can I believe this?

Can I then just follow the given instructions for this plugin, or do I have to create this post-install.sh script also?

**Comment by wunditta** [comment]
OK, I got it. I tried the post-install.sh script, but this did not work and crashed the server. But manually issuing those three lines did it:
```
docker exec -it redmine sudo -u redmine -H bundle install
docker exec -it redmine sudo -u redmine -H bundle exec rake db:migrate RAILS_ENV=production
docker exec -it redmine sudo -u redmine -H bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```
Thanks a lot! :-)

Although I am outraged. I applied for the free version for private matters and I was granted a download link... And ALL this for nothing! You can use this plugin only with demo data!!! They do not tell this anywhere upfront! They really let you go through all this hassle for nothing? Well, should I ever use this professionally I will NEVER EVER buy one of their plugins. Sorry, for the rant, but maybe this helps some others avoiding a lot of trouble for nothing.

**Comment by jcormier** [comment]
The post install script runs every time you start the container. It should
be placed in the data/plugin directory.

I dont recommend running it manually as youd have to do that every boot...

**Comment by jcormier** [comment]
I don't see an obvious issue with that script.  Maybe it needs to be make executable?  
```chmod +x post-install.sh```

**Comment by wunditta** [comment]
I didn't mean that there are issues with it. I just was not sure how the script should look like.

However, I do not need it anyways. I restarted the container without the script several times and everything seems to work. So, maybe this is a newer version of EasyGantt which fixed some issues.

Again, many, many thanks for the fast response. You really saved my day... well, more weeks than day... ;-)
