### ISSUE TITLE
Tags in dockerhub?

### ISSUE THREAD

**Issue by tecnoprogram-thomas** [sameersbn/docker-redmine#495]
I noticed that latest tags are not available in dockerhub, maybe there is some syncronization issue?

Thanks!

**Comment by frank-dspeed** [comment]
@tecnoprogram-thomas we are partial aware of some issues and currently working on that i keep this open

**Comment by jcormier** [comment]
Tags 4.2, 4.2.4, and 4.1.6-r2 have been pushed
