### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by koren85** [sameersbn/docker-redmine#502]
Hi!
How can I set many values in 
REDMINE_BACKUP_TIME

**Comment by jcormier** [comment]
Can you provide more details of what you are trying to do?

Per the documentation, it can only take a single time.

- **REDMINE_BACKUP_TIME**: Set a time for the automatic backups in `HH:MM` format. Defaults to `04:00`.

If you need a custom cron setup for your backups you may need to setup your own cron entries using the post-install.sh script mentioned in the README.md

**Comment by koren85** [comment]
Hey,
I was interested in the ability to specify two values, for example 6:00 and 19:00

**Comment by frank-dspeed** [comment]
@koren85 consider to solve that on the container hosts cron  and use docker exec rake task
