### ISSUE TITLE
send email fail

### ISSUE THREAD

**Issue by kt1024** [sameersbn/docker-redmine#503]
have tried multiple combo settings. (corp mailserver, 3rd party mailserver, postfix, tls 587/465, no tls/25 , etc)
the log only showing deliveryjob performed.  (no error log related)

question is , how can I enable debug log ? and advice is appreciated. 

<pre>
[ActiveJob] Enqueued ActionMailer::DeliveryJob (Job ID: 1b9effed-9d87-4895-a8e5-a860df961329) to Async(mailers) with arguments: "Mailer", "issue_edit", "deliver_now", #<GlobalID:0x000055bbfbac5a28 @uri=#<URI::GID gid://redmine-app/User/6>>, #<GlobalID:0x000055bbfbac50c8 @uri=#<URI::GID gid://redmine-app/Journal/365>>
[ActiveJob] [ActionMailer::DeliveryJob] [1b9effed-9d87-4895-a8e5-a860df961329] Performing ActionMailer::DeliveryJob (Job ID: 1b9effed-9d87-4895-a8e5-a860df961329) from Async(mailers) with arguments: "Mailer", "issue_edit", "deliver_now", #<GlobalID:0x000055bbfba09710 @uri=#<URI::GID gid://redmine-app/User/6>>, #<GlobalID:0x000055bbfba08fe0 @uri=#<URI::GID gid://redmine-app/Journal/365>>
[ActiveJob] [ActionMailer::DeliveryJob] [1b9effed-9d87-4895-a8e5-a860df961329]   Rendering mailer/issue_edit.text.erb within layouts/mailer
[ActiveJob] [ActionMailer::DeliveryJob] [1b9effed-9d87-4895-a8e5-a860df961329]   Rendered mailer/_issue.text.erb (4.1ms)
[ActiveJob] [ActionMailer::DeliveryJob] [1b9effed-9d87-4895-a8e5-a860df961329]   Rendered mailer/issue_edit.text.erb within layouts/mailer (5.5ms)
[ActiveJob] [ActionMailer::DeliveryJob] [1b9effed-9d87-4895-a8e5-a860df961329]   Rendering mailer/issue_edit.html.erb within layouts/mailer
[ActiveJob] [ActionMailer::DeliveryJob] [1b9effed-9d87-4895-a8e5-a860df961329]   Rendered mailer/_issue.html.erb (0.5ms)
[ActiveJob] [ActionMailer::DeliveryJob] [1b9effed-9d87-4895-a8e5-a860df961329]   Rendered mailer/issue_edit.html.erb within layouts/mailer (1.9ms)
[ActiveJob] [ActionMailer::DeliveryJob] [1b9effed-9d87-4895-a8e5-a860df961329] Performed ActionMailer::DeliveryJob (Job ID: 1b9effed-9d87-4895-a8e5-a860df961329) from Async(mailers) in 22.34ms
</pre>

**Comment by jcormier** [comment]
I'm not sure, you might need to ask on the redmine forum.

You could try running the email test and seeing if it reports the errors directly.

`docker exec -it redmine sudo -u redmine -H bundle exec rake redmine:email:test[admin] RAILS_ENV=production`

**Comment by kt1024** [comment]
> I'm not sure, you might need to ask on the redmine forum.
> 
> You could try running the email test and seeing if it reports the errors directly.
> 
> `docker exec -it redmine sudo -u redmine -H bundle exec rake redmine:email:test[admin] RAILS_ENV=production`

I can receive test email with this command, but can not get system notice email. only get logs like 1st post.
checked with email server, it does not connect to email server smtp pot. (has connection while using test command)

**Comment by jcormier** [comment]
I'm not sure how to debug the email system in ruby.  You should ask on the redmine.org forum to see if there is a way to enable logs for ActionMailler::DeliveryJob.  If you need help doing a step they ask, then maybe I can point you in the right direction.

Sending emails works for me for both the test command and through ActionMailer.

**Comment by kt1024** [comment]
found the option with google, but no error found in  `production.log` after set log level to `:debug` in `application.rb`
my version is `4.2.5`, found some similar post on redmine forum but did not found solution yet.

logs with debut enabled:
<pre>
[ActiveJob] Enqueued ActionMailer::DeliveryJob (Job ID: 5b5184ca-6463-4ac9-94a6-d2274bdd4dbd) to Async(mailers) with arguments: "Mailer", "issue_edit", "deliver_now", #<GlobalID:0x00005643af0baa88 @uri=#<URI::GID gid://redmine-app/User/6>>, #<GlobalID:0x00005643af0ba2e0 @uri=#<URI::GID gid://redmine-app/Journal/380>>
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd] Performing ActionMailer::DeliveryJob (Job ID: 5b5184ca-6463-4ac9-94a6-d2274bdd4dbd) from Async(mailers) with arguments: "Mailer", "issue_edit", "deliver_now", #<GlobalID:0x00005643af093ca8 @uri=#<URI::GID gid://redmine-app/User/6>>, #<GlobalID:0x00005643af093348 @uri=#<URI::GID gid://redmine-app/Journal/380>>
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   AnonymousUser Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('AnonymousUser') AND `users`.`lastname` = 'Anonymous' LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Issue Load (3.5ms)  SELECT  `issues`.* FROM `issues` WHERE `issues`.`id` = 110 LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Project Load (1.1ms)  SELECT  `projects`.* FROM `projects` WHERE `projects`.`id` = 2 LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Tracker Load (0.3ms)  SELECT  `trackers`.* FROM `trackers` WHERE `trackers`.`id` = 4 LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`id` = 6 LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Principal Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 6 LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   CACHE User Load (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`id` = 6 LIMIT 1  [["id", 6], ["LIMIT", 1]]
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   JournalDetail Load (0.4ms)  SELECT `journal_details`.* FROM `journal_details` WHERE `journal_details`.`journal_id` = 380
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'protocol' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'host_name' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'mail_from' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'user_format' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'app_title' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]    (0.3ms)  SELECT `email_addresses`.`address` FROM `email_addresses` WHERE `email_addresses`.`user_id` = 6 AND (is_default = TRUE OR notify = TRUE)
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   UserPreference Load (0.3ms)  SELECT  `user_preferences`.* FROM `user_preferences` WHERE `user_preferences`.`user_id` = 6 LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]    (0.3ms)  SELECT `email_addresses`.`address` FROM `email_addresses` WHERE `email_addresses`.`user_id` = 6
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'bcc_recipients' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Rendering mailer/issue_edit.text.erb within layouts/mailer
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]    (0.4ms)  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 2
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   IssueStatus Load (0.3ms)  SELECT  `issue_statuses`.* FROM `issue_statuses` WHERE `issue_statuses`.`id` = 2 LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   IssuePriority Load (0.3ms)  SELECT  `enumerations`.* FROM `enumerations` WHERE `enumerations`.`type` IN ('IssuePriority') AND `enumerations`.`id` = 2 ORDER BY `enumerations`.`position` ASC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   IssueCustomField Load (0.4ms)  SELECT `custom_fields`.* FROM `custom_fields` WHERE `custom_fields`.`type` IN ('IssueCustomField') AND (is_for_all = TRUE OR id IN (SELECT DISTINCT cfp.custom_field_id FROM custom_fields_projects cfp WHERE cfp.project_id = 2)) ORDER BY `custom_fields`.`position` ASC
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   IssueCustomField Load (0.4ms)  SELECT `custom_fields`.* FROM `custom_fields` INNER JOIN `custom_fields_trackers` ON `custom_fields`.`id` = `custom_fields_trackers`.`custom_field_id` WHERE `custom_fields`.`type` IN ('IssueCustomField') AND `custom_fields_trackers`.`tracker_id` = 4
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Attachment Exists (0.3ms)  SELECT  1 AS one FROM `attachments` WHERE `attachments`.`container_id` = 110 AND `attachments`.`container_type` = 'Issue' LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Rendered mailer/_issue.text.erb (7.6ms)
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Rendered mailer/issue_edit.text.erb within layouts/mailer (10.9ms)
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'emails_header' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'emails_footer' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'plain_text_mail' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Rendering mailer/issue_edit.html.erb within layouts/mailer
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'text_formatting' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'cache_formatted_text' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Attachment Load (0.3ms)  SELECT `attachments`.* FROM `attachments` WHERE `attachments`.`container_id` = 110 AND `attachments`.`container_type` = 'Issue' ORDER BY attachments.created_on ASC, attachments.id ASC
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Rendered mailer/_issue.html.erb (1.0ms)
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd]   Rendered mailer/issue_edit.html.erb within layouts/mailer (5.3ms)
[ActiveJob] [ActionMailer::DeliveryJob] [5b5184ca-6463-4ac9-94a6-d2274bdd4dbd] Performed ActionMailer::DeliveryJob (Job ID: 5b5184ca-6463-4ac9-94a6-d2274bdd4dbd) from Async(mailers) in 54.67ms
</pre>

**Comment by kt1024** [comment]
@jcormier if you are with redmine v4 or 5, would you mind share you config? thank you

**Comment by kt1024** [comment]
with `config.action_mailer.perform_deliveries` set to `true`, no related error 

logs of manual send test mail
<pre>
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
   (0.3ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
  User Load (0.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`login` = 'admin'
  AnonymousUser Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('AnonymousUser') AND `users`.`lastname` = 'Anonymous' LIMIT 1
  Setting Load (0.6ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'force_default_language_for_loggedin' ORDER BY `settings`.`id` DESC LIMIT 1
  Setting Load (0.5ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'default_language' ORDER BY `settings`.`id` DESC LIMIT 1
  Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'protocol' ORDER BY `settings`.`id` DESC LIMIT 1
  Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'host_name' ORDER BY `settings`.`id` DESC LIMIT 1
  Setting Load (0.6ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'mail_from' ORDER BY `settings`.`id` DESC LIMIT 1
  Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'app_title' ORDER BY `settings`.`id` DESC LIMIT 1
   (0.3ms)  SELECT `email_addresses`.`address` FROM `email_addresses` WHERE `email_addresses`.`user_id` = 1 AND (is_default = TRUE OR notify = TRUE)
  Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'bcc_recipients' ORDER BY `settings`.`id` DESC LIMIT 1
  Rendering mailer/test_email.text.erb within layouts/mailer
  Rendered mailer/test_email.text.erb within layouts/mailer (0.6ms)
  Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'emails_header' ORDER BY `settings`.`id` DESC LIMIT 1
  Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'emails_footer' ORDER BY `settings`.`id` DESC LIMIT 1
  Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'plain_text_mail' ORDER BY `settings`.`id` DESC LIMIT 1
  Rendering mailer/test_email.html.erb within layouts/mailer
  Rendered mailer/test_email.html.erb within layouts/mailer (0.2ms)
  Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'text_formatting' ORDER BY `settings`.`id` DESC LIMIT 1
  Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'cache_formatted_text' ORDER BY `settings`.`id` DESC LIMIT 1
 </pre>
 
 logs of notice email (failed)
<pre>
  Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'default_users_hide_mail' ORDER BY `settings`.`id` DESC LIMIT 1
  EmailAddress Load (0.3ms)  SELECT  `email_addresses`.* FROM `email_addresses` WHERE `email_addresses`.`user_id` = 6 AND `email_addresses`.`is_default` = TRUE LIMIT 1
[ActiveJob] Enqueued ActionMailer::DeliveryJob (Job ID: ef60c06f-d169-4f9d-add0-ea8d149a016a) to Async(mailers) with arguments: "Mailer", "issue_edit", "deliver_now", #<GlobalID:0x000055d9cf113470 @uri=#<URI::GID gid://redmine-app/User/6>>, #<GlobalID:0x000055d9cf112b38 @uri=#<URI::GID gid://redmine-app/Journal/385>>
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a] Performing ActionMailer::DeliveryJob (Job ID: ef60c06f-d169-4f9d-add0-ea8d149a016a) from Async(mailers) with arguments: "Mailer", "issue_edit", "deliver_now", #<GlobalID:0x000055d9cf0f4188 @uri=#<URI::GID gid://redmine-app/User/6>>, #<GlobalID:0x000055d9cf04f9d0 @uri=#<URI::GID gid://redmine-app/Journal/385>>
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a]   Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'mail_from' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a]    (0.3ms)  SELECT `email_addresses`.`address` FROM `email_addresses` WHERE `email_addresses`.`user_id` = 6 AND (is_default = TRUE OR notify = TRUE)
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a]    (0.3ms)  SELECT `email_addresses`.`address` FROM `email_addresses` WHERE `email_addresses`.`user_id` = 6
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a]   Rendering mailer/issue_edit.text.erb within layouts/mailer
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a]   Rendered mailer/_issue.text.erb (5.4ms)
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a]   Rendered mailer/issue_edit.text.erb within layouts/mailer (7.7ms)
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a]   Setting Load (0.2ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'emails_header' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a]   Setting Load (0.2ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'emails_footer' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a]   Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'plain_text_mail' ORDER BY `settings`.`id` DESC LIMIT 1
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a]   Rendering mailer/issue_edit.html.erb within layouts/mailer
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a]   Rendered mailer/_issue.html.erb (1.7ms)
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a]   Rendered mailer/issue_edit.html.erb within layouts/mailer (5.4ms)
[ActiveJob] [ActionMailer::DeliveryJob] [ef60c06f-d169-4f9d-add0-ea8d149a016a] Performed ActionMailer::DeliveryJob (Job ID: ef60c06f-d169-4f9d-add0-ea8d149a016a) from Async(mailers) in 41.58ms
  EmailAddress Load (0.3ms)  SELECT `email_addresses`.* FROM `email_addresses` WHERE `email_addresses`.`is_default` = TRUE AND `email_addresses`.`user_id` = 6
</pre>

manual excute <pre>SELECT `email_addresses`.* FROM `email_addresses` WHERE `email_addresses`.`is_default` = TRUE AND `email_addresses`.`user_id` = 6"</pre>in mysql can get correct email address.

**Comment by kt1024** [comment]
solved. is my stupid mistake, I test with my own account, but by default notice won't be sent to the user who made chagens.
thank you. @jcormier 
![image](https://user-images.githubusercontent.com/12657496/165696675-e3d4fde5-474a-4414-9da6-f178cdaa0a07.png)
