### ISSUE TITLE
app:backup:create and app:backup:restore commands doesn't work

### ISSUE THREAD

**Issue by nord64** [sameersbn/docker-redmine#508]
I run redmine with postgresql based on [docker-compose-ssl.yml](https://github.com/sameersbn/docker-redmine/blob/master/docker-compose-ssl.yml) - sameersbn/redmine:4.2.9.
It works great, makes automatic backups. But I have a problem with manual backup and restore, described in https://github.com/sameersbn/docker-redmine#creating-backups
1. `docker stop redmine-docker-redmine-1 && docker rm redmine-docker-redmine-1` - OK

When I try to restore backup with the following command:

2. `docker run --name redmine-docker-redmine-1 -it --rm sameersbn/redmine:4.2.9 app:backup:restore`

I get the following message:

`Initializing logdir...
Initializing datadir...
chmod: cannot access '/home/redmine/data': No such file or directory
`

How to solve this issue?

**Comment by jcormier** [comment]
You need to link to your sql container and well as volume mount the data directory.

Ex:
```
docker run --name redmine-docker-redmine-1 -it --rm --volume=/srv/docker/redmine/redmine:/home/redmine/data --link=postgresql-redmine:postgresql sameersbn/redmine:4.2.9 app:backup:create
```

**Comment by nord64** [comment]
Found another way, when using docker compose.
These commands should be executed from the folder with your docker-compose.yml.

Create backup:
```
docker compose stop redmine && docker compose rm redmine
docker compose run -it --rm redmine app:backup:create
docker compose up -d
```


Restore backup:
```
docker compose stop redmine && docker compose rm redmine
docker compose run -it --rm redmine app:backup:restore
docker compose up -d
```

**Comment by jcormier** [comment]
Yeah I definitely recommend using docker compose.  I've been wanting to redo all the documentation using docker compose syntax but it's a lot to change.
