### ISSUE TITLE
Upgrade from 4.2.3 to 5.0.5: no login possible

### ISSUE THREAD

**Issue by auc-mma** [sameersbn/docker-redmine#511]
I tried to upgrade my redmine from 4.2.3 to 5.0.5.

after the start of my new Redmine 5.0.5 docker container ...it seemed all ok...db was migraded, all plugins start...
but now I can't login anymore

here are the tasks I made:

- copy of the hole mariadb Database
- create a new container with right setting for db
- container starts successfull, all plugins start well

this procedure worked well til 4.2.3...

did I make something wrong?

**Comment by jcormier** [comment]
Try launching without any plugins to rule out an incompatible plugin.

I personally haven't tried migrating to 5.x yet. Still running 4.2.x, i can
give it a try if that helps.

**Comment by auc-mma** [comment]
works now...
It seems to be..that i made a mistake while copying the database...
