### ISSUE TITLE
How themes are handled

### ISSUE THREAD

**Issue by redbast** [sameersbn/docker-redmine#514]
Hi!
I am using sameersbn redmine for quite a while but still can not fully figure out how themes are handled. Inside the container they are located where supposed to in pubic/themes but is the content of this directory gets always recreated especially when some plugins (for example Redmine-X's) create their own theme? I do not seem to be able to find 'themes' with any content in the local filesystem...

**Comment by jcormier** [comment]
Installing themes is described here: https://github.com/sameersbn/docker-redmine#installing-themes

**Comment by jcormier** [comment]
Closing, reopen if you have further questions
