### ISSUE TITLE
Issues while installing plugin

### ISSUE THREAD

**Issue by CreatorSimon** [sameersbn/docker-redmine#522]
Hello,
I wanted to install this plugin: https://github.com/planio-gmbh/omniauth-redmine-oauth2. I followed the steps in your documentation, but i got this weird issue:

redmine_1     | Database 'redmine_production' already exists
redmine_1     | Installing plugins...
redmine_1     | Installing gems required by plugins...
redmine_1     | You are replacing the current local value of without, which is currently "development:test"
redmine_1     | Migrating plugins. Please be patient, this could take a while...
redmine_1     | rake aborted!
redmine_1     | Zeitwerk::NameError: wrong constant name Omniauth-redmine-oauth2 inferred by RedmineInflector from file
redmine_1     |
redmine_1     |   /home/redmine/redmine/plugins/omniauth-redmine-oauth2/lib/omniauth-redmine-oauth2.rb
redmine_1     |
redmine_1     | Possible ways to address this:
redmine_1     |
redmine_1     |   * Tell Zeitwerk to ignore this particular file.
redmine_1     |   * Tell Zeitwerk to ignore one of its parent directories.
redmine_1     |   * Rename the file to comply with the naming conventions.
redmine_1     |   * Modify the inflector to handle this case.
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:171:in `rescue in cname_for'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:166:in `cname_for'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:414:in `block in define_autoloads_for_dir'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:25:in `each'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:25:in `ls'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:411:in `define_autoloads_for_dir'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:124:in `block (2 levels) in setup'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:123:in `each'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:123:in `block in setup'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:120:in `synchronize'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:120:in `setup'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies/zeitwerk_integration.rb:95:in `setup_autoloaders'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies/zeitwerk_integration.rb:72:in `take_over'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/application/finisher.rb:81:in `block in <module:Finisher>'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `instance_exec'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `run'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:61:in `block in run_initializers'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:60:in `run_initializers'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/application.rb:391:in `initialize!'
redmine_1     | /home/redmine/redmine/config/environment.rb:16:in `<top (required)>'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:332:in `block in require'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:299:in `load_dependency'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:332:in `require'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/application.rb:367:in `require_environment!'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/application.rb:533:in `block in run_tasks_blocks'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
redmine_1     |
redmine_1     | Caused by:
redmine_1     | NameError: wrong constant name Omniauth-redmine-oauth2
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:167:in `const_defined?'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:167:in `cname_for'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:414:in `block in define_autoloads_for_dir'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:25:in `each'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:25:in `ls'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:411:in `define_autoloads_for_dir'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:124:in `block (2 levels) in setup'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:123:in `each'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:123:in `block in setup'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:120:in `synchronize'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:120:in `setup'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies/zeitwerk_integration.rb:95:in `setup_autoloaders'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies/zeitwerk_integration.rb:72:in `take_over'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/application/finisher.rb:81:in `block in <module:Finisher>'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `instance_exec'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `run'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:61:in `block in run_initializers'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:60:in `run_initializers'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/application.rb:391:in `initialize!'
redmine_1     | /home/redmine/redmine/config/environment.rb:16:in `<top (required)>'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:332:in `block in require'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:299:in `load_dependency'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:332:in `require'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/application.rb:367:in `require_environment!'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7.2/lib/rails/application.rb:533:in `block in run_tasks_blocks'
redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
redmine_1     | Tasks: TOP => redmine:plugins:migrate => environment
redmine_1     | (See full trace by running task with --trace)
docker-redmine_redmine_1 exited with code 1

I searched for an solution and tried the given ones, but without any success. Does anyone noticed this issue using an different plugin?

Thanks for the help!

Kind regards

**Comment by CSCSxx** [comment]
At first glance I would say that the plugin is not compatible with Redmine 5.0...

**Comment by jcormier** [comment]
Agreed, the linked plugin hasn't been updated in 3 years and doesn't even mention what redmine versions its compatible with.
