### ISSUE TITLE
 Ruby 3.2 support 

### ISSUE THREAD

**Issue by outductor** [sameersbn/docker-redmine#529]
Sicne 5.1.0, Rubt 3.2 is supported and we can use `YJIT` properly.

**Comment by outductor** [comment]
@CSCSxx You should make your own issue... that's not what we discuss in this issue

**Comment by jcormier** [comment]
According to your title, your both requesting a newer version of Ruby. Unfortunately, 2.7 is the newest version of ruby in the brightbox/ruby-ng repo.  Which means bumping the OS version, which cascades into a lot of other changes.

I will try to bump it again, but it might turn into a project.

**Comment by jcormier** [comment]
Alright, this took way too long but I pushed a new branch, ruby3.2 that moves the 5.1.1 redmine to ruby 3.2.  This ended up involving swapping to a Debian-based distro.  So it would be good if people would try it out and see if it works before I merge it into master.

I don't know anything about YJIT, does redmine support it?  How do you even enable it?

**Comment by outductor** [comment]
https://shopify.engineering/ruby-yjit-is-production-ready
https://railsatscale.com/2023-09-18-ruby-3-3-s-yjit-runs-shopify-s-production-code-15-faster/

**Comment by kannrem** [comment]
> Alright, this took way too long but I pushed a new branch, ruby3.2 that moves the 5.1.1 redmine to ruby 3.2. This ended up involving swapping to a Debian-based distro. So it would be good if people would try it out and see if it works before I merge it into master.
> 
> I don't know anything about YJIT, does redmine support it? How do you even enable it?

We tested the ruby3.2 branch and its working as expected. thanks. Could you please merge to master or create a new image out of it? Also we would like to point out the problem with attachments which will get saved in /redmine/files. this directory is not in sync with mounted volume /data/files. hence the data there are not persisted and  attachments are getting lost once the new container brought up.

**Comment by jcormier** [comment]
> Also we would like to point out the problem with attachments which will get saved in /redmine/files. this directory is not in sync with mounted volume /data/files. hence the data there are not persisted and attachments are getting lost once the new container brought up.

So not sure what you mean, I just tested in the master branch and files were correctly persisted.
```
root@5d231c2e4892:/home/redmine/redmine# ls /home/redmine/data/files/2024/01/2401152042*
/home/redmine/data/files/2024/01/240115204204_6252_23026330_bootlog.txt
/home/redmine/data/files/2024/01/240115204216_am62a7_evm_edgeai_09_00_01_08.log
$ ls -l /srv/docker/redmine/redmine/files/2024/01/2401152042*
-rw-r--r-- 1 jcormier-local jcormier-local  42449 Jan 15 10:12 /srv/docker/redmine/redmine/files/2024/01/240115204204_6252_23026330_bootlog.txt
-rw-r--r-- 1 jcormier-local jcormier-local 363980 Jan 15 10:12 /srv/docker/redmine/redmine/files/2024/01/240115204216_am62a7_evm_edgeai_09_00_01_08.log
```
I also tested it on the ruby3.2 branch and had no issue with files persisting.

**Comment by kannrem** [comment]
@jcormier Thankyou for ruby support as most of the plugins we tried requires ruby 3.x. Could you please merge this branch to master or would you be able to push a seperate image with ruby tag. Thankyou

**Comment by jcormier** [comment]
Thanks for the bump, this has been dragging for quite a while.  I'm still fairly swamped at work currently.

I merged the ruby changes into master, and tagged 5.1.1-4. Docker images are building now.
