### ISSUE TITLE
Help:Unknown system variable "transaction_isolation"

### ISSUE THREAD

**Issue by CSCSxx** [sameersbn/docker-redmine#531]
I tried to run the version 5.1.1 on my Synology with the bundled MariaDB 10.11.2
As Failure i get a error: Unknown system variable "transaction_isolation"
I found out that MariaDB <11 and MySQL <8  needs the name "tx_isolation" 
How can i change this as variable?

**Comment by jcormier** [comment]
Thats a good question. For now you can run the 5.1.0 tag which doesn't set this variable.

I'm swamped at work right now so not sure when I can look into this.  I think we might need to detect which mysql server/mariadb server version we are connecting to and change the setting accordingly.

**Comment by jcormier** [comment]
Note the commit in question is here: https://github.com/sameersbn/docker-redmine/commit/8270cbddd52790bc947f78313b85bf5a519190e7

**Comment by Gong-Bao-Chicken** [comment]
I have the same problem.

**Comment by jcormier** [comment]
> I have the same problem.

Are you using MariaDB as well?  Does the 5.1.0 tag work?

**Comment by Gong-Bao-Chicken** [comment]
Yes. 5.1.0 Tag is still working.
I am using Maria db 10.5 image.

**Comment by jcormier** [comment]
Instead of trying to set the transaction level, the image now just checks what its set to and prints a warning.

    docker-redmine-redmine-1  | Configuring redmine::database...
    docker-redmine-redmine-1  | Checking transaction isolation level... REPEATABLE-READ
    docker-redmine-redmine-1  | WARNING: transaction isolation level is not READ-COMMITTED
    docker-redmine-redmine-1  | WARNING: Read more about this issue at:
    docker-redmine-redmine-1  | https://www.redmine.org/projects/redmine/wiki/MySQL_configuration

Updated the docker compose files for mysql and mariadb to set the transaction level to READ-COMMITTED
