### ISSUE TITLE
postgresql container fails to start and report error: popen failure: unable to allocate memory initdb: error: The program "postgres" is needed by initdb but was not found in the same directory as "/usr/lib/postgresql/14/bin/initdb". 

### ISSUE THREAD

**Issue by wangyu8460958** [sameersbn/docker-redmine#534]
When I use the file https://github.com/sameersbn/docker-redmine/blob/master/docker-compose-memcached.yml to start, the postgresql container fails to start and reports an error straight away:
`Initializing database...
popen failure: unable to allocate memory
initdb: error: The program "postgres" is needed by initdb but was not found in the
same directory as "/usr/lib/postgresql/14/bin/initdb". 
Check your installation.`

How can I solve this problem?

**Comment by jcormier** [comment]
Could you happen to have docker version 5:20?  A quick google points in that direction.

https://stackoverflow.com/a/76571292

**Comment by wangyu8460958** [comment]
@jcormier ， thank you, this method solve my question.
