### ISSUE TITLE
Run sameersbn/redmine with an External Azure MySQL database

### ISSUE THREAD

**Issue by luciantr24** [sameersbn/docker-redmine#542]
Hi. On our team we are trying run the docker image for sameersbn/redmine (v3.4.6) using an external already created Azure MySQL database. The user and database are already configured. (according to this documentation [External MySQL](https://github.com/sameersbn/docker-redmine?tab=readme-ov-file#external-mysql-server))

Docker command: 
`docker run --name=redmine-prod -it --rm --env='DB_ADAPTER=mysql2' --env='DB_HOST=azure_host_ip' --env='DB_NAME=db_name' --env='DB_USER=db_user' --env='DB_PASS=db_pass'  --env='DB_PORT=3306' --volume=/srv/docker/redmine/redmine:/home/redmine/data --volume=/srv/docker/redmine/redmine-logs:/var/log/redmine/ sameersbn/redmine:3.4.6`

Output:
```
Initializing logdir...
Initializing datadir...
Generating OpenSSH client keys...
Symlinking dotfiles...
Installing configuration templates...
Configuring redmine...
Configuring redmine::database
```

After few minutes the process stops as the database connection cannot be established. 

I tried different things found on the internet but didn't help ( I ran in network mode: host, I created a custom network based on my network configuration, I modified the MySQL configuration).All of this gave me the same error. Also I tried to connect to my host database instead of the Azure MySQL and this also didn't work. 

Can you please let me know what is needed to be configured or what might be the issue in order to be able to access the database? I am mentioning that we can access it using our company VPN but from the docker container we don't have access. 

Thank you very much!

**Comment by jcormier** [comment]
First thing, I'm not familiar with Azure app services.  So there may be some network setup needed..

Add --env='DEBUG=true' to see the command being run. I suspect its the "wait for database to start" step.

This should look something like: `mysqladmin -h ${DB_HOST} -P ${DB_PORT} -u ${DB_USER} ${DB_PASS:+-p$DB_PASS} status`
This should keep trying for about 60 seconds before giving up.  If this is were the container is getting stuck, you need to figure out why your container cannot reach the external mysql server.

Things to try from within the container (`docker run -it ... bash`)
* Ping the mysql ip address from within the container. Some servers block ping so not always reliable...
* Try running the mysqladmin command yourself, maybe it is printing an error thats getting hidden

**Comment by luciantr24** [comment]
Thank you @jcormier . Unfortunately I was not able to replicate what is causing the issue with sameersbn/redmine:3.4.6, but in the end we used **redmine:3.4.6** and we were able to successfully run the application in the Linux Azure App Service using an external Azure MySql Database (using a VNET integration).
