### ISSUE TITLE
MOving back from 5.1.1 to 5.0.7

### ISSUE THREAD

**Issue by vomus** [sameersbn/docker-redmine#544]
Hi!
I just played a bit with 5.1.1 and wants to go back to 5.0.7. Knowing that going back is not possible with an already upgraded DB, I just wiped it out and restored my 5.0.7 DB from a backup. However, when I started an old container I still got an error:

<pre>
redmine-1  | ERROR: 
redmine-1  |   Cannot downgrade from Redmine version 5.1.1 to 5.0.7.
redmine-1  |   Only upgrades are allowed. Please use sameersbn/redmine:5.1.1 or higher.
redmine-1  |   Cannot continue. Aborting!
</pre>

Is there anything I haven't done?

**Comment by jcormier** [comment]
Delete the tmp directory in the data volume, it will get regenerated.
