### ISSUE TITLE
Failed: Upgrade from 5.0.7 -> 5.1.2 on Synology Docker

### ISSUE THREAD

**Issue by CSCSxx** [sameersbn/docker-redmine#549]
When I try to update my current 5.0.7 to 5.1.2, an error occurs during the migration of the database - plugins are not yet integrated in this step:

Migrating database. Please be patient, this could take a while...
rake aborted!
(Checking transaction isolation level... REPEATABLE-READ)
...
Bundler::GemRequireError: There was an error while trying to load the gem 'with_advisory_lock'. (Bundler::GemRequireError)
Gem Load Error is: failed to get urandom

The DB version used: 10.3.29-MariaDB (cannot be updated)

Is the cause in the database or somewhere else?
Thanks for the support, Carsten

**Comment by jcormier** [comment]
[testing_5.0.7_upgrade_to_5.1.2_mariadb.log](https://github.com/sameersbn/docker-redmine/files/14652785/testing_5.0.7_upgrade_to_5.1.2_mariadb.log)

Tested upgrading a blank new server from 5.0.7 to 5.1.2. This was successful though the first boot into 5.1.2 the database upgrade took longer than redmine was willing to wait.  Note making sure to bring down the docker compose between upgrades is important I think.

Could you post your before and after docker-compose?  Also posting the full log is a lot more helpful than just a snippet.  Make sure your making backups before doing these upgrades.

**Comment by jcormier** [comment]
> Bundler::GemRequireError: There was an error while trying to load the gem 'with_advisory_lock'. (Bundler::GemRequireError)
> Gem Load Error is: failed to get urandom

Note there is a chance this is a old kernel issue, especially if this is run on a synology: https://github.com/sameersbn/docker-gitlab/issues/2872

**Comment by jcormier** [comment]
> Bundler::GemRequireError: There was an error while trying to load the gem 'with_advisory_lock'. (

It looks like with_advisory_lock is a new dependency between 5.0.7 and 5.1.2, which is using the urandom  call so the previous link is looking more likely
```
./Gemfile:        gem "with_advisory_lock"
```

**Comment by CSCSxx** [comment]
I can well imagine that it is due to the Docker version of this Synology Station (DSM 6.2).
I haven't had any problems updating on a newer station.
Our IT department now wants to create a new, virtual environment for it, since the old NAS will be retired in the medium term anyway...
Thanks for your tips.
