### ISSUE TITLE
PLZ Add: sendmail support via env

### ISSUE THREAD

**Issue by frank-dspeed** [sameersbn/docker-redmine#72]
I need to run internal sendmail because i hate gmail they always block and discuss with me my ips and all that i simply need working mail and would love that without setting up postfix

**Comment by sameersbn** [comment]
@frank-dspeed how can we do that? any suggestions?

**Comment by b-a-t** [comment]
And I'd live exim, Or not, wait, CommuniGatePro, its nicer! Adding more software into the docker defeats the whole idea of separation of the applications and their tasks. 

docker-redmine already provides nice outgoing SMTP interface, so why not to use it?! Setup sendmail/postfix/whatever in your local network or even on docker hosting server and point redmine to talk to it over SMTP. I guess, you can use docker-sendmail as well, only expose port 25 for external IP.

**Comment by sameersbn** [comment]
@b-a-t @frank-dspeed my idea was to create a postfix image with simple configuration options which you would be able to link to other images or communicate over the network to send emails. However I have not found the time to work on it.

**Comment by frank-dspeed** [comment]
ah its only a little option but don't got time to do this will send pull when its ready and postfix img is to big i only whant to send some mails not 1000 per hour so its fine with the sendmail execute able simply need a ENV setting for this like SMTP_METHOD sendmail, smtp, false, thats it :dancer:

**Comment by b-a-t** [comment]
Do I understand correctly that you want to bloat redmine image with yet another package? That is against the whole ideology of docker. Redmine is already heavier than an average dock app and each additional package should be evaluated for it's necessity. I don't see the reason why you can't communicate with the local to the hosting machine sendmail over SMTP.

**Comment by frank-dspeed** [comment]
thats not right sendmail isn't a daemon

**Comment by fbertux** [comment]
Hi!
I had a problem with create and and update an issue when internet isn't working, Redmine didn't witout internet, I can't create or modify any issue. The solution was change delivery_method in assets/config/redmine/smtp_settings.rb from stmp to async_smtp. Is it possible to create a environment variable SMTP_METHOD to set delivery_method to smtp, sendmail, async_smtp, async_sendmail? I think it's a useful thing...

**Comment by frank-dspeed** [comment]
good idea thats what i will work on was offline because location change i attach this issu to me :dart:

**Comment by frank-dspeed** [comment]
i also vote for default async_smtp !

**Comment by fbertux** [comment]
With async_smtp create or modify an issue is faster, I vote to be default too.

**Comment by sameersbn** [comment]
@fbertux I have sent a review to your PR. Need a couple of changes and we should be ready to merge. Thanks

**Comment by sameersbn** [comment]
@fbertux @frank-dspeed setting the async delivery method to default might not be a great idea simply because if there is an issue in your smtp configuration or say for some reason your smtp server is gone bust, you will not notice it and redmine will always tell you that the email was sent.

**Comment by fbertux** [comment]
@sameersbn  You're right! It's better set smtp to default, if email delivery is working the user can change to async_smtp.

**Comment by frank-dspeed** [comment]
#80

**Comment by sameersbn** [comment]
@fbertux the PR has been merged. Thanks for the contribution.
