### ISSUE TITLE
Plugin Installation Failed

### ISSUE THREAD

**Issue by kndrio** [sameersbn/docker-redmine#74]
After clone some plugin to /plugins dir and restart container the logs show this message:
Could not find gem 'rails (= 3.2.21) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.

I already tried and retried rm tmp and these three plugins and the error are the same, 
https://github.com/scrum2b/scrum2b
https://github.com/nsi-iff/kanban-plugin
https://github.com/nutso/redmine-plugin-recurring-tasks.git

Thanks for helping!

**Comment by sameersbn** [comment]
@kndrio from what I can tell scrum2b does not indicate that it is compatible with redmine 2.6 series. The kanban-plugin has not been updated in the last 4 years, so I am pretty sure it will not work with latest redmine. The recurring-task-plugin is known to work and is also documented in https://github.com/sameersbn/docker-redmine#installing-plugins, you can also refer to https://gist.github.com/sameersbn/dd24dfdd13bc472d11a5#file-redmine-plugins-install-sh-L93-L112 for the complete set of instructions

**Comment by kndrio** [comment]
Thanks for answer I will try another versions.
