### ISSUE TITLE
Use Wiki for plugins and themes scripts

### ISSUE THREAD

**Issue by petiepooo** [sameersbn/docker-redmine#76]
The Wiki allows anyone to update the plugins and themes install scripts.  Rather than using a gist, which only you can update, I suggest you allow the community to update scripts as new versions of the packages are released.

To help you, I've copied the original gists into your Wiki with a page linking to both of them.  See https://github.com/sameersbn/docker-redmine/wiki

BTW, did you know anybody can create wiki pages in your project repositories if you have the Wiki enabled for it?  :)

**Comment by sameersbn** [comment]
@petiepooo understood. thanks for the info.
