### ISSUE TITLE
smtp not working with ssl/tls

### ISSUE THREAD

**Issue by ict4ngo** [sameersbn/docker-redmine#77]
I'm using this information to connect

SMTP_USER="email@domain.net"
SMTP_PASS="password"
SMTP_DOMAIN="domain.net"
SMTP_HOST="smtpout.secureserver.net"
SMTP_PORT="465"
SMTP_STARTTLS="false"

however I have a (end of file reached) when testing or sending an email

Completed 500 Internal Server Error in 30989.5ms

EOFError (end of file reached):
  app/models/mailer.rb:431:in `deliver_mail'
  app/controllers/users_controller.rb:145:in `update'

the official settings that works for are 

ssl/tls on port 465 

normally setting smtp_starttls to false should work. I'm not sure what other option I have

**Comment by kt1024** [comment]
I've met same problem and fixed. check Internal Error #107 for details.

also you should check if you have typo or not. (in password/address). and check if your mail server block your connection or not.
works fine now.

**Comment by sameersbn** [comment]
@ict4ngo I have added `SMTP_TLS` option to enable `SSL/TLS` in the `latest` version.

**Comment by sameersbn** [comment]
Link #117 and close
