### ISSUE TITLE
3.0.0 won't start

### ISSUE THREAD

**Issue by codercotton** [sameersbn/docker-redmine#79]
A simple pull/run is throwing this error:

Using transifex-ruby-fork-jg 0.1.0
Using unicorn 4.8.3
Using vcard 0.2.12
Bundle complete! 46 Gemfile dependencies, 98 gems now installed.
Gems in the groups development and tests were not installed.
Bundled gems are installed into ./vendor/bundle.
Migrating plugins. Please be patient, this could take a while...
rake aborted!
ArgumentError: The scope body needs to be callable.
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/scoping/named.rb:143:in `scope'
/home/redmine/redmine/plugins/redmine_agile/lib/redmine_agile/patches/issue_patch.rb:33:in `block in included'
/home/redmine/redmine/plugins/redmine_agile/lib/redmine_agile/patches/issue_patch.rb:29:in `class_eval'
/home/redmine/redmine/plugins/redmine_agile/lib/redmine_agile/patches/issue_patch.rb:29:in `included'
/home/redmine/redmine/plugins/redmine_agile/lib/redmine_agile/patches/issue_patch.rb:50:in `include'
/home/redmine/redmine/plugins/redmine_agile/lib/redmine_agile/patches/issue_patch.rb:50:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine/plugins/redmine_agile/lib/redmine_agile.rb:26:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine/plugins/redmine_agile/init.rb:55:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine/lib/redmine/plugin.rb:155:in `block in load'
/home/redmine/redmine/lib/redmine/plugin.rb:146:in `each'
/home/redmine/redmine/lib/redmine/plugin.rb:146:in `load'
/home/redmine/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:651:in `load_config_initializer'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine/plugins/recurring_tasks/lib/tasks/recurring_tasks.rake:7:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/redmine/redmine/lib/tasks/redmine.rake:179:in `block in <top (required)>'
/home/redmine/redmine/lib/tasks/redmine.rake:179:in `each'
/home/redmine/redmine/lib/tasks/redmine.rake:179:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:658:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:658:in `run_tasks_blocks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:438:in `run_tasks_blocks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:453:in `load_tasks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
/home/redmine/redmine/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by sameersbn** [comment]
@codercotton as indicated [here](https://github.com/sameersbn/docker-redmine#version) and [here](https://github.com/sameersbn/docker-redmine/issues/12#issuecomment-76695281), if your installation depends on various third party plugins, please stick with 2.6.xx series to avoid breakage.

**Comment by codercotton** [comment]
Thanks for the reply!

**Comment by codercotton** [comment]
Any chance you can add this patch to your 2.6-stable branch?  Fixes a downgrade migration issue I'm running into after trying and failing the 3.0.0 upgrade.

http://www.redmine.org/projects/redmine/repository/revisions/13920

**Comment by sameersbn** [comment]
@codercotton that commit is already present in the redmine `3.0.0` release
