### ISSUE TITLE
2.6-latest branch is redmine 3.0.0

### ISSUE THREAD

**Issue by Neopallium** [sameersbn/docker-redmine#81]
It seems the 2.6-latest branch has been upgraded to 3.0.0.

**Comment by sameersbn** [comment]
@Neopallium Could be an issue with docker build service. The `2.6-latest` tag is configured to be build from the `2.6-stable` branch.

**Comment by sameersbn** [comment]
@Neopallium the redmine version upgrade commit were merged into the `2.6-stable` branch when I merged a PR into this branch. I have (force) fixed the branch and push the changes out. A new build should be available in a couple of minutes.

Thanks for notifying about this issue.
