### ISSUE TITLE
permission denied on data/tmp contents

### ISSUE THREAD

**Issue by chaseadam** [sameersbn/docker-redmine#83]
I just switched to externalizing the entire redmine/data directory and noticed permission errors when I started the redmine container the second time. I can workaround by clearing out data/tmp, but this is necessary before every startup.

Running with the following command on a fedora atomic host:
sudo docker run --name=redmine -it --rm -p 80:80 -p 443:443 -v /home/fedora/redmine/data:/home/redmine/data -e 'REDMINE_HTTPS=true' --link postgresql2:postgresql sameersbn/redmine:latest

I have followed the documentation on setting security on the data directory:
sudo chcon -Rt svirt_sandbox_file_t /home/fedora/redmine/data

Example of errors:
chown: changing ownership of '/home/redmine/data/tmp/bundle/ruby/2.1.0/build_info/activerecord-4.2.0.info': Permission denied
chown: changing ownership of '/home/redmine/data/tmp/bundle/ruby/2.1.0/build_info/sprockets-rails-2.2.4.info': Permission denied
chown: changing ownership of '/home/redmine/data/tmp/Gemfile.lock': Permission denied

**Comment by sameersbn** [comment]
@chaseadam I have no idea whats going on here. selinux works in mysterious ways :smile: 
I will try your command as soon as I have the chance to setup fedora and atomic. Until then I have no suggestion other than suggesting you disable selinux :facepunch:

**Comment by chaseadam** [comment]
Looks like SELinux is the culprit, but not sure how to proceed. Will have to brush up on my black magic of SELinutx
```
type=AVC msg=audit(1426910746.902:5432): avc:  denied  { setattr } for  pid=1263 comm="chown" name="Gemfile.lock" dev="dm-0" ino=6452906 scontext=system_u:system_r:svirt_lxc_net_t:s0:c703,c808 tcontext=system_u:object_r:svirt_sandbox_file_t:s0:c22,c577 tclass=file permissive=0
```

**Comment by chaseadam** [comment]
Thought it might be because I had the data in /home/fedora/redmine/data, so moved it to /opt/redmine/data, but that wasn't it. Found that it is attempting to do a setattr which appears to be allowed per SELinux policies:

````
[fedora@atomic redmine]$ sesearch --allow --source svirt_lxc_net_t --target svirt_sandbox_file_t --class file --perm write
Found 1 semantic av rules:
   allow svirt_sandbox_domain svirt_sandbox_file_t : file { ioctl read write create getattr setattr lock relabelfrom relabelto append unlink link rename execute execute_no_trans open } ;
````

audit2allow produces a Type Enforcement rule which indicates setattr is not permitted:
````
#	Possible cause is the source level (s0:c6,c679) and target level (s0:c484,c529) are different.
allow svirt_lxc_net_t svirt_sandbox_file_t:file setattr;
````

created module to allow this explicitly:
````
[fedora@atomic tmp]$ sesearch --allow --source svirt_lxc_net_t --target svirt_sandbox_file_t --class file --perm setattr
Found 2 semantic av rules:
   allow svirt_lxc_net_t svirt_sandbox_file_t : file setattr ; 
   allow svirt_sandbox_domain svirt_sandbox_file_t : file { ioctl read write create getattr setattr lock relabelfrom relabelto append unlink link rename execute execute_no_trans open } ; 
````
and I still get permission denied...

**Comment by sameersbn** [comment]
@chaseadam I myself have no selinux expertise. Luckily I came across the ` sudo chcon -Rt svirt_sandbox_file_t <path>` configuration while watching a youtube video about docker+selinux (https://www.youtube.com/watch?v=zWGFqMuEHdw).

I guess things might have changed now. I cannot be of much help here. Hopefully somebody who has faced this issue and managed to get is resolved might respond.

**Comment by sameersbn** [comment]
@chaseadam were you able to resolve this issue. If yes, then for the benefit of others please mention it here. Thanks

**Comment by abn** [comment]
Had a similar issue. The culprit seems to be [MCS](http://www.projectatomic.io/docs/docker-and-selinux/).

The symptom I had encountered was that files created on host by a container when re-used by another container or another instance of the same container, a `Permission Denied` error was encountered.

The solution, for me at least, was to run the container with `--security-opt` option. See [docker run security configuration](https://docs.docker.com/reference/run/#security-configuration) for more information.

```sh
docker run --security-opt label:level:s0:c100,c200 -i -t fedora bash
```

You could also use `--security-opt label:level:s0`; but this will effectively disable MCS but has the advantage other containers can use the data too event when the level is not set explicitly as above.

Hope this helps resolve your issue.

**Comment by sameersbn** [comment]
@abn thanks for sharing the selinux info.

**Comment by sameersbn** [comment]
closing issue.
