### ISSUE TITLE
Can you build version 2.3.3 to docker hub please ?

### ISSUE THREAD

**Issue by cedvan** [sameersbn/docker-redmine#84]
Hi,

Need use **2.3.3** version (Don't have choice...).
I can't build in enterprise network with firewall. 
So I need pull image ready from docker hub.

Can you build image 2.3.3 on docker hub please ?

**Comment by sameersbn** [comment]
@cedvan I will give it a try.

**Comment by cedvan** [comment]
Ok thank you :)

**Comment by cedvan** [comment]
Did you have time to try ?

**Comment by sameersbn** [comment]
@cedvan preparing the gitlab releases. Will work on this once i am done.

**Comment by cedvan** [comment]
ok, no stress, if you need help, I can maybe help you ?

**Comment by sameersbn** [comment]
maybe you can send a PR and I will create a new branch for the 2.3.3 version where I will merge the PR. https://github.com/sameersbn/docker-redmine#contributing

**Comment by sameersbn** [comment]
@cedvan didn't realize that version 2.3.3 is already tagged in the repo. Just need to build. Lets hope the build goes through.

**Comment by sameersbn** [comment]
@cedvan `2.3.3 ` tag is now available on docker hub.
Note that a lot has changed since `2.3.3` release, so please make sure you refer to the correct [README](https://github.com/sameersbn/docker-redmine/blob/063d00112d77b371cc24ffc585b4ca658e1a2ca4/README.md)

**Comment by cedvan** [comment]
Oh great ! Thank you :)
