### ISSUE TITLE
Failed to upload files in wiki or files modules

### ISSUE THREAD

**Issue by stevenfounder** [sameersbn/docker-redmine#87]
Can't use the file upload function in the wiki page or "files" module.
I tried several version of the docker image: redmine v2.6.2, v3.0.0, v3.0.1.

After select a file, it always say "error" in the read-only text field behind the file name and can't see the uploaded file in the wiki page or file list of the "files" module.

But in fact, I can see the file in the files directory inside docker instance:
/home/redmine/redmine/files/2015/03/150324095538_marketing.png

And I can also see the related messages in the redmine/log/production.log: 
Started POST "/uploads.js?attachment_id=2&filename=marketing.png&content_type=image%2Fpng" for 127.0.0.1 at 2015-03-24 09:55:38 +0000
Processing by AttachmentsController#upload as JS
  Parameters: {"attachment_id"=>"2", "filename"=>"marketing.png", "content_type"=>"image/png"}
  Current user: guochaoyang (id=3)
Saving attachment '/home/redmine/redmine/files/2015/03/150324095538_marketing.png' (3010575 bytes)
  Rendered attachments/upload.js.erb (0.4ms)
Completed 200 OK in 67ms (Views: 1.2ms | ActiveRecord: 36.0ms)

The environment info:
OS: Ubuntu 14.10 x86_64, Ubuntu 3.16.0-31-generic
Docker: Docker version 1.5.0, build a8a31ef
Fig: docker-compose 1.1.0

Any suggestion will be welcome! Thanks!

**Comment by stevenfounder** [comment]
The environment info:
OS: Ubuntu 3.16.0-31-generic, x86_64
Docker: Docker version 1.5.0, build a8a31ef
Fig: docker-compose 1.1.0

**Comment by mzoeller** [comment]
I just stumbled upon that error myself. I realized that for some files (size?, mime?), file upload works fine. I'm not sure but it might have something to do with the fact that NGIX is serving the uploads.js statically for larger files different filenames? See http://www.redmine.org/issues/13564, specifically http://www.redmine.org/issues/13564#note-8

**Comment by sameersbn** [comment]
@stevenfounder @mzoeller I began testing this issue and this is what I found.
The tests were performed using the sample fig.yml, so basically `fig up` to start the container.

In my tests I found that when I upload files in the Files module, the result is random. Either the file uploads or it does not. Its just random. Retrying multiple times seems to upload the file. Various errors are emitted by nginx and unicorn when the upload fails. Nginx (internal) says "failed (13: Permission denied) while reading upstream". 

Currently nginx is configured to communicate with unicorn over the unix socket. I decided to try using the TCP socket and found that the uploads seems to work fine. So basically the issue might be resolved if we switch to using the TCP socket in the nginx configuration.

Before I can make this change. I need your confirmation.

**How to test**

1. Acquire a shell to the running container using docker exec, i.e. `docker exec -it redmine bash`
2. Edit `/etc/nginx/sites-enabled/redmine` configuration and change the line 5 from: `server unix:{{INSTALL_DIR}}/tmp/sockets/redmine.socket fail_timeout=0;` to: `server 127.0.0.1:8080 fail_timeout=0;`
3. Restart the nginx server `supervisorctl restart nginx`
4. Test the issue.

Let me know the results for you. If this resolves the issue, then I will make the changes. Else, we need to keep digging.

**Comment by mzoeller** [comment]
I can confirm that this fixes the issue. Interesting..
Also, thanks for your very speedy reply and fix!

**Comment by stevenfounder** [comment]
@sameersbn I tested your solution and it works fine! Really appreciate for your quick response!

**Comment by sameersbn** [comment]
@stevenfounder the fix has been applied and should be present in the `latest` tag.
