### ISSUE TITLE
some SMTP server require that  "FROM address"  must be equal to the user. 

### ISSUE THREAD

**Issue by epiphyllum** [sameersbn/docker-redmine#90]
does redmine has such property to config such as docker-gitlab's      GITLAB_EMAIL ??

the following is the error message result from my  SMTP config

Completed 500 Internal Server Error in 4382.9ms

Net::SMTPFatalError (553 Mail from must equal authorized user
):
  app/models/mailer.rb:431:in `deliver_mail'
  app/controllers/users_controller.rb:96:in `create'

**Comment by epiphyllum** [comment]
372   def mail(headers={}, &block)
    373     headers.reverse_merge! 'X-Mailer' => 'Redmine',
    374             'X-Redmine-Host' => Setting.host_name,
    375             'X-Redmine-Site' => Setting.app_title,
    376             'X-Auto-Response-Suppress' => 'OOF',
    377             'Auto-Submitted' => 'auto-generated',
    378             # 'From' => Setting.mail_from,
    379             'From' => "18874881230@163.com",
    380             'List-Id' => "<#{Setting.mail_from.to_s.gsub('@', '.')}>"

I modified the source code, and manually set the From to my email address. it works.  But I think this should be confgurable. 

another problem is,  when I check my email.  I found the content of email is misleading(http://localhost:3000/login),   should it also be configurable?   just like gitlab's GITLAB_HOST


您的帐号信息:

登录名: kkk
密码: SFkVpyCtUs
登录: http://localhost:3000/login

You have received this notification because you have either subscribed to it, or are involved in it.
To change your notification preferences, please click here: http://hostname/my/account

**Comment by epiphyllum** [comment]
the tested version is   2.6.3

**Comment by epiphyllum** [comment]
I think, you should  add more  -e parameter for replacement in settings.yml. 
I have test it, it is ok to manually modify  settings.yml and restart

**Comment by sameersbn** [comment]
@epiphyllum In **Administration -> Settings -> Email notifications (tab)** you will find a setting named *Emission email address*. I believe it will set the `from` field in email notifications. Does that not work for you?

**Comment by epiphyllum** [comment]
yes , Thanks, I found it!
