### ISSUE TITLE
 INFO exited: unicorn (exit status 1; not expected)

### ISSUE THREAD

**Issue by linksonice** [sameersbn/docker-redmine#94]
Hi sameersbn. I've seen this before I think in your gitlab container, but get it now in redmine with postgresql. Basically I do everything by the book - pull  sameersbn/redmine:3.0.1, pull  sameersbn/postgresql:9.4, start everything up with the correct docker -run commands, but then get into this endless loop of failure:

2015-04-17 15:22:35,459 INFO spawned: 'unicorn' with pid 94
2015-04-17 15:22:37,062 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-17 15:22:38,338 INFO exited: unicorn (exit status 1; not expected)
2015-04-17 15:22:39,342 INFO spawned: 'unicorn' with pid 98
2015-04-17 15:22:40,975 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-17 15:22:42,320 INFO exited: unicorn (exit status 1; not expected)
2015-04-17 15:22:43,324 INFO spawned: 'unicorn' with pid 102
2015-04-17 15:22:44,894 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-17 15:22:46,157 INFO exited: unicorn (exit status 1; not expected)
2015-04-17 15:22:47,160 INFO spawned: 'unicorn' with pid 106
2015-04-17 15:22:48,720 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-17 15:22:49,969 INFO exited: unicorn (exit status 1; not expected)
2015-04-17 15:22:50,972 INFO spawned: 'unicorn' with pid 110
2015-04-17 15:22:52,522 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-17 15:22:53,725 INFO exited: unicorn (exit status 1; not expected)
2015-04-17 15:22:54,729 INFO spawned: 'unicorn' with pid 114

in fact, the only way I can start the redmine to avoid the above is:

docker run --name=redmine -it --rm -p 80:80 -v /var/run/docker.sock:/run/docker.sock -v $(which docker):/bin/docker sameersbn/redmine:3.0.1

but this creates a whole new container called sameersbn/postgresql:latest which i don't really wish to run, as I prefer to see sameersbn/postgresql:9.4 in order to know the version.

Is there any easy way to determine what causes this? Thanks, Andrei

**Comment by linksonice** [comment]
in fact, the only way I can start the redmine to avoid the above is:

docker run --name=redmine -it --rm -p 80:80 -v /var/run/docker.sock:/run/docker.sock -v $(which docker):/bin/docker sameersbn/redmine:3.0.1

but this creates a whole new container called sameersbn/postgresql:latest which i don't really wish to run, as I prefer to see  sameersbn/postgresql:9.4 in order to know the version.

**Comment by mcondarelli** [comment]
Hi,
I have the same problem.
Exec-ing a shell in the failing container I tried to find reason for failure.
in /var/log/redmine/supervisor/unicorn.log I have four occurrences (one for each attempt) of the following log:
```
/usr/lib/ruby/2.1.0/psych.rb:370:in `parse':  (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`: (<unknown>): did not find expected key while parsing a block mapping at l ine 2 column 3. Bundler cannot continue.

 #  from /home/redmine/redmine/Gemfile:57
 #  -------------------------------------------
 #  if File.exist?(database_file)
 >    database_config = YAML::load(ERB.new(IO.read(database_file)).result)
 #    adapters = database_config.values.map {|c| c['adapter']}.compact.uniq
 #  -------------------------------------------
        from /usr/lib/ruby/2.1.0/psych.rb:370:in `parse_stream'
        from /usr/lib/ruby/2.1.0/psych.rb:318:in `parse'
        from /usr/lib/ruby/2.1.0/psych.rb:245:in `load'
        from /home/redmine/redmine/Gemfile:57:in `eval_gemfile'
        from /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/dsl.rb:34:in `instance_eval'
        from /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/dsl.rb:34:in `eval_gemfile'
        from /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/dsl.rb:10:in `evaluate'
        from /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/definition.rb:26:in `build'
        from /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler.rb:155:in `definition'
        from /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler.rb:123:in `setup'
        from /var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/setup.rb:18:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```
This seemed to point to some database problem, so I checked /home/redmine/redmine/config/database.yml and pronto! I found an error:
```
production:
  adapter: "mysql2"
  encoding: "utf8"
  reconnect: false
  database: "redmine"
  host: "172.17.2.16"
  port: 3306
  username: "redmine"
  password: ""...mypass...""
  pool: 5
```
notice password was double-quoted TWICE!
This seems to spawn from fact I had quoted it in the command line:
```
docker run --name=mysql-redmine -d \
   --env='DB_NAME=redmine' \
   --env='DB_USER=redmine' --env='DB_PASS="...mypass..."' \
   --volume=/srv/docker/redmine/mysql:/var/lib/mysql \
   sameersbn/mysql:latest
```
@linksonice : can You check if something similar is happening to You?

Removing quoting removes also the error, but, unfortunately, redmine refuses to run with an "Internal error" when I try to access the web.
Probably the second error is unrelated so, if I cannot find it I will open another ticket.

**Comment by sameersbn** [comment]
@mcondarelli glad that you got your issue resolved and thanks for posting your findings here. This should help other users as well. :+1:

**Comment by mcondarelli** [comment]
@sameersbn I am a bit confused though: how am I supposed to quote password in case it contains "strange" chars (or simply some whitespace)?

**Comment by sameersbn** [comment]
@mcondarelli you should treat `VAR=VALUE` as a single parameter and use `'` characters while specifying the env variables using `-e` option. As a result `-e 'VAR=some value'` will work just fine. Some character do need to be escaped though using the `\` character. This is basically a bash thing.

**Comment by morm** [comment]
This issue relates to any error in redmine config that set CRIT errors while redmine starts.
I came on it with REDMINE_SECRET_TOKEN less then 30 chars error

**Comment by jcormier** [comment]
Closing due to old age
