### ISSUE TITLE
sameersbn/redmine:3.0.1's  Initialization failed in OS X

### ISSUE THREAD

**Issue by redtankd** [sameersbn/docker-redmine#95]
the command is 

```
docker run -it --rm --name=redmine --link mysql-redmine:mysql \
-v ~/var/docker/redmine/redmine/:/home/redmine/data \
--entrypoint= sameersbn/redmine:3.0.1 
```

the output is

```
cp: cannot create regular file '/home/redmine/data/tmp/bundle/ruby/2.1.0/gems/rmagick-2.13.4/lib/RMagick.rb': File exists
```

no more output.

**Comment by ddiachkov** [comment]
It is a problem with case-insensitive filesystem. rmagick gem contains both `rmagick.rb` and `RMagick.rb` in the same directory. You can use disk image formatted with `Mac OS Extended (Case-sensitive, Journaled)` for storing redmine data.

**Comment by jcormier** [comment]
Closing due to old age
