### ISSUE TITLE
502 Bad Gateway error

### ISSUE THREAD

**Issue by poomalairaj** [sameersbn/docker-redmine#96]
I've been using this image for 2 weeks and I have integrated gitlab (mounted as a volume from sameersbn/gitlab container). The repository in redmine was working just fine initially.

Later I made some big changes in git repo which affects almost all the files in the repository. After this change, I could not access the repository tab in redmine. It loads around 30 seconds and then shows "502 Bad Gateway" error.

Can you please have  a look at this and help me resolve the problem?

**Comment by poomalairaj** [comment]
when I run top command inside the container while requesting repository page, ruby2.1 is utilizing 100% cpu and always at top until I get 502 gateway error. Could this help?

**Comment by poomalairaj** [comment]
Ok. I think I got it now. I just set environment variable UNICORN_TIMEOUT=600 and the problem is now solved.

**Comment by sameersbn** [comment]
@poomalairaj looks like your repository is large and redmine is taking time fetching the repo history.

**Comment by poomalairaj** [comment]
You are right. That may be the reason.
Hey you are doing a great job maintaining these awesome docker images. Keep up the good job. Thanks for giving us high quality docker images
