### ISSUE TITLE
Password parse issue, problematic '&'

### ISSUE THREAD

**Issue by ivanalejandro0** [sameersbn/docker-redmine#97]
I had a problem when creating/updating issues (internal error 500) when using a gmail account to send emails and after some debugging I realized that the problem was an "incorrect" password.
I used an env file with the following (I tried using the `-e` switch as well):
```
SMTP_USER='my_gmail_account@gmail.com'
SMTP_PASS='h3t2&C52V5!#207R6kL'
```

But on the `/home/redmine/redmine/config/initializers/smtp_settings.rb` file, inside the running container, I've found:
```
    :user_name            => "'my_gmail_account@gmail.com'",
    :password             => "'h3t2{{SMTP_PASS}}C52V5!#207R6kL'",
```

It seems that the `&` character is causing problems here.
This happens whether if I use quotes or not in the password field.
Note: the account and password are dummy ones :)

**Comment by sameersbn** [comment]
@ivanalejandro0 due to the nature of bash certain characters need to be escaped. `&` is one of them. stick a `\` character before the `&` -> `\&` and it should resolve the issue.

**Comment by ivanalejandro0** [comment]
I thought it could be because of that.

I'm not sure if someone should do something to fix this...
 1. docker: it makes sense to escape in the command line (`-e`), but maybe should/could read raw characters from the env file?
 1. this dockerfile: maybe you should handle the password differently since the `{{SMTP_PASS}}` string is being placed inside the password.

In any case, maybe it would make sense to note this in your docs in case of someone has the same issue. Or just close this issue since it can be tagged as 'misuse' and if someone else has this problem can be pointed towards this.

Thanks

**Comment by sameersbn** [comment]
@ivanalejandro0 the `&` issue is purely a bash thing and yes docker could probably handle such case if it was in the position to do so. Meaning adding something like -e "VAR=a&b" in the docker command is first interpreted by bash before it can be interpreted by docker. Using single quote helps in such cases. i.e. `-e 'VAR=a&b'`

Similarly nothing can be done about this in the docker image because it has already been interpreted by bash at this point.

**Comment by ivanalejandro0** [comment]
hmm, that's odd. I remember using single quotes and have redmine failing (before I realize which was the problem so I can't make sure).
Anyway, this was mainly a user problem so feel free to close this.
